- cvxpy/atoms/__init__.py
- cvxpy/atoms/harmonic_mean.py
- cvxpy/atoms/pnorm.py
- cvxpy/tests/test_atoms.py
- cvxpy/tests/test_constant_atoms.py
- cvxpy/tests/test_problem.py
- doc/source/tutorial/functions/index.rst
Adds a concave (but not actually a norm) branch of `pnorm` for values of `p < 1`.
> Add pnorm with p < 1

- cvxpy/atoms/__init__.py
- cvxpy/atoms/partial_optimize.py
- cvxpy/expressions/variables/__init__.py
- cvxpy/expressions/variables/nonneg.py
- cvxpy/expressions/variables/variable.py
- cvxpy/tests/test_atoms.py
Redoing this, but for the develop branch.
> Adding partial_optimize functionality, a NonNegative variable class, and a small change to the Variable class.

- cvxpy/expressions/variables/symmetric.py
- cvxpy/problems/solvers/cvxopt_intf.py
> Py2 win64 fixes

- cvxpy/problems/solvers/mosek_intf.py
I have a working implementation - Steven is there any code to test it against CVXOPT and SCS?
> MOSEK SDP interface - initial working prototype (testing needed)

- cvxpy/constraints/semidefinite.py
- cvxpy/problems/solvers/mosek_intf.py
- cvxpy/tests/test_constant_atoms.py
The nosetest fails on one test. I tried to replicate it but can't find where in the tests it is. Can you give me the code that generates the error? I'll figure out what's wrong.
I have preliminary performance tests :)
10x10 SDP 
MOSEK 300ms
CVXOPT 2sec
20x20 SDP
MOSEK 2sec
CVXOPT 40sec
> fixed way SDP constraints were enforced in MOSEK + test

- cvxpy/constraints/leq_constraint.py
This can be use to form Lagrangian of a problem, if we are allowed to multiply variables.
> Add dual variables to constraints

- cvxpy/atoms/log_sum_exp.py
- cvxpy/constraints/exponential.py
- cvxpy/tests/test_constant_atoms.py
Hi Steven,
Small change here - CVXOPT seems to throw an error once in awhile?
Cheers,
Matt
> add axis parameter to log_sum_exp atom

- cvxpy/atoms/atom.py
- cvxpy/constraints/leq_constraint.py
- cvxpy/expressions/constants/constant.py
- cvxpy/expressions/leaf.py
- cvxpy/problems/objective.py
- cvxpy/problems/problem.py
- cvxpy/tests/test_constant_atoms.py
- cvxpy/tests/test_monotonicity.py
- cvxpy/tests/test_problem.py
- cvxpy/tests/test_sign.py
- cvxpy/transforms/partial_optimize.py
- cvxpy/utilities/canonical.py
Added a SizeMetrics object that serves as an attribute of Problems and contains information about the number of scalar variables, scalar eq and leq constraints, data values, and the maximum dimension of any data block. It is instantiated when the problem is instantiated.
Added a constants() method that functions mostly the same as the variables() and parameters() methods by recursively finding the Constant objects in the objective and constraints of the problem.
> Adding SizeMetrics object and constants() method for getting info about problems

- cvxpy/problems/solvers/mosek_intf.py
current version leaks memory, see
http://docs.mosek.com/7.0/pythonapi/Efficiency_considerations.html
for details.
> use "with" for mosek task and env to prevent memory leaks

- cvxpy/utilities/quadratic.py
this fixes some dimension mismatch bugs in quadratic util
> quadratic util bugfix

- examples/deadzone.py
- examples/fmmc.py
These are some minor changes to ensure Python 3 compatibility and silence PEP8 warnings while improving readability.
While I do not know whether such changes are welcome, I only fixed two examples, but I could try to fix more if you are interested.
> Fix few examples

- cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py
I have added "inaccurate" statuses for OSQP. They will be used in its next release.
> Added inaccurate statuses for OSQP

- cvxpy/problems/solvers/gurobi_intf.py
Based on a support case from a user, we at Gurobi are proposing these changes.  They seem to make a big improvement in Gurobi performance with cvxpy. This replaces a prior pull request, where the email address was not set correctly in my fork.
> Performance improvements for Gurobi

- cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
- cvxpy/tests/test_mosek_conif.py
This solves issue #449, I tested with two mosek versions, 8.1.34 and 8.1.41
> make 1.0 pass unit tests for mosek 8.0

- cvxpy/atoms/matrix_frac.py
This PR tries to solve an issue #560 I found when this project introduced CPLEX solver recently. 
it implements the first method @rileyjmurray proposed.
> FIX: asymmetric Q matrix in quadratic form

- .gitignore
- cvxpy/reductions/solvers/qp_solvers/qp_solver.py
Fix wrong dual variables returned by QP solvers.
Problem described in #591
Solution by @gbanjac described in https://github.com/cvxgrp/cvxpy/issues/591#issuecomment-428121241
> Fix dual variables in QP solvers

- cvxpy/atoms/elementwise/huber.py
- cvxpy/reductions/qp2quad_form/atom_canonicalizers/__init__.py
- cvxpy/reductions/qp2quad_form/atom_canonicalizers/huber_canon.py
- cvxpy/tests/test_qp.py
Now the Huber function is QP compatible.
I have to say the cvxpy 1.0 canonicalization system very intuitive! I did not imagine it to be so easy.
I copied most of what was already in the conic canonicalizer.
It gives the same results as the conic Huber canonicalization so it seems correct to me. I have also added a unit test.
FIxes #603
> Huber QP canonicalization

- setup.py
closes #594.
`__builtins__` can be a dict. see https://docs.python.org/2/reference/executionmodel.html
> handle builtin when it is a dict

- cvxpy/problems/solvers/gurobi_intf.py
- cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
Fixes #521. I have used the changes in #480 and added then to the QP interface as well.
> Fixed Gurobi statuses

- cvxpy/reductions/solvers/conic_solvers/scs_conif.py
I ran the test [`cvxpy/performance_tests/test_robustness.py`](https://github.com/cvxgrp/cvxpy/blob/941b1caf04dc16824e7d49fb2343eb70803c2c7e/cvxpy/performance_tests/test_robustness.py) with the [`yappi`](https://github.com/sumerc/yappi) performance profiler, and saw two functions — both in [`cvxpy/reductions/solvers/conic_solvers/scs_conif.py`](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/scs_conif.py) — taking a lot of resources:
* [`scaled_lower_tri`](https://github.com/cvxgrp/cvxpy/blob/941b1caf04dc16824e7d49fb2343eb70803c2c7e/cvxpy/reductions/solvers/conic_solvers/scs_conif.py#L48-L86)
* [`tri_to_full`](https://github.com/cvxgrp/cvxpy/blob/941b1caf04dc16824e7d49fb2343eb70803c2c7e/cvxpy/reductions/solvers/conic_solvers/scs_conif.py#L48-L86)
I …
> Vectorize scaled_lower_tri, tri_to_full

- examples/sdp.py
Just sending in a quick fix for this example because I was looking at it.
> Update sdp example to the latest interface.

- cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py
- cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
Some improvements from comments https://github.com/cvxgrp/cvxpy/issues/617#issuecomment-462909013 and https://github.com/cvxgrp/cvxpy/issues/617#issuecomment-463220105.
It still does't solve completely #617.
> CPLEX/Gurobi performance improvements from comments in #617

- cvxpy/atoms/quad_over_lin.py
- cvxpy/reductions/complex2real/atom_canonicalizers/__init__.py
- cvxpy/reductions/complex2real/atom_canonicalizers/matrix_canon.py
- cvxpy/tests/test_complex.py
Updated `quad_over_lin` to support complex entries in its first (matrix) argument.
> Added quad_over_lin complex atom and test

- cvxpy/reductions/solvers/defines.py
This simple change should fix issue #719.
> Do not include duplicates in installed_solvers()

- examples/notebooks/WWW/MIQP.ipynb
> MIQP example

- cvxpy/reductions/solvers/conic_solvers/cbc_conif.py
- doc/source/tutorial/advanced/index.rst
Added some CBC exit status messages,
I will also update the documentation to include the solver settings we can actually set with cvxpy
> cbc mip status extension

- cvxpy/reductions/solvers/conic_solvers/conic_solver.py
This commit vectorizes the construction of the spacing matrix. I'm pretty confident it's correct, but tests at HEAD (without this commit) are failing so it's not easy for me to verify correctness empirically. That said, without this commit, I see 2 errors and 2 failures for test_scs.py, and that's still true with this commit.
> Vectorize construction of spacing matrix

- cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
This PR implements the transition to the public, stable matrix friendly API of Gurobi's gurobipy.  This is a backwards compatible change, but we may consider to drop the usage of the temporary API functions starting with `_v811_` for reasons of code hygiene once Gurobi version 8.1.1 is no longer the widespread version.
I verified locally through `nosetests` that the change does not increase the number of failed tests (some were failing already in master).
> Update for Gurobi v9 API

- cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
Checked out from rileyjmurray's PR (#860)
> Fix exponential cone for MOSEK

- cvxpy/reductions/solvers/solving_chain.py
QP solvers like OSQP can take many iterations for LPs. For example,
for the l1-regularized SVM example
https://www.cvxpy.org/examples/machine_learning/svm.html,
OSQP can take > 20,000 iterations to converge (so a solver error is thrown),
whereas an IPM like ECOS is much faster.
> Default to conic solvers for LPs

- cvxpy/atoms/affine/reshape.py
- cvxpy/tests/test_shape.py
> Cast lists to tuples in reshape atom

- cvxpy/problems/problem.py
- doc/source/api_reference/cvxpy.problems.rst
> Problem docs improvement

- cvxpy/reductions/solvers/conic_solvers/scs_conif.py
AA (without stabilization) sometimes diverges.
Related: https://github.com/cvxgrp/scs/issues/129
> Restart SCS without AA if solution is inaccurate

- cvxpy/reductions/solvers/conic_solvers/cplex_conif.py
- cvxpy/reductions/solvers/conic_solvers/scs_conif.py
- cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py
This pull request contains various bug fixes, cleanup, and preparation for the CPLEX 12.10 release.
I'd appreciate feedback from someone who knows more about CVXPY internals.
> Fix cplex 201911

- cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
- doc/source/tutorial/advanced/index.rst
The bfs kwarg for MOSEK was not documented.
> Basis identification and basic solution retrieval from MOSEK

- conda-recipe/meta.yaml
- continuous_integration/AppVeyor/deploy_windows.ps1
- continuous_integration/Travis/deploy_script.sh
This is a preliminary attempt at resolving #937. I tested basic conda builds (and ``readme_renderer`` installs) on my machine. I won't be able to run tests with my TravisCI account until probably the middle of next week (my account there is somehow broken). In order to avoid delay I'm merging in these changes now.
> CI deployment fixes

- doc/source/examples/applications/MM.rst
- doc/source/examples/applications/parade_route.rst
- doc/source/examples/dqcp/concave_fractional_function.rst
This should fix issue #925 and issue #928.
> Fix some examples in the documentation

- examples/notebooks/dqcp/hypersonic_shape_design.ipynb
Python notebook developed with Akshay to highlight constrained minimization of a quasilinear objective function for an aerospace shape design example.
> Add aerospace shape design example to dqcp examples section

- doc/source/faq/index.rst
> Fixed link to CVXPY paper

- cvxpy/expressions/expression.py
Addresses https://github.com/cvxgrp/cvxpy/issues/980#
> Change use of * as matmul to UserWarning

- cvxpy/reductions/canonicalization.py
- cvxpy/reductions/complex2real/complex2real.py
- cvxpy/reductions/cvx_attr2constr.py
- cvxpy/reductions/flip_objective.py
- cvxpy/reductions/matrix_stuffing.py
- cvxpy/reductions/solvers/bisection.py
- cvxpy/reductions/solvers/intermediate_chain.py
- cvxpy/reductions/solvers/solving_chain.py
This change brings in the commits from the 1.0.30 branch, which should remove circular imports, to master.
> Fix circular imports

- doc/source/examples/dgp/power_control.rst
The code of line 70 missed a [k]
> Fix a problem of p[k]

- doc/source/install/index.rst
and fix broken link.
conda is a package/environment management system, anaconda is a distribution
> Anaconda --> conda in install docs

- cvxpy/performance_tests/test_warmstart.py
- cvxpy/tests/test_dgp.py
- cvxpy/tests/test_dgp2dcp.py
- cvxpy/tests/test_interfaces.py
- cvxpy/tests/test_quad_form.py
- cvxpy/tests/test_suppfunc.py
Fix some code that resulted in deprecation warnings, and other code that didn't follow unit testing conventions ...
> clean up some tests

- examples/MMCF.ipynb
@SteveDiamond Based on our earlier discussions, I am submitting this pull request so the example on Multi-commodity Network Flow Problem can be merged.
> Additional example on commodity flow

- cvxpy/problems/xpress_problem.py
- cvxpy/reductions/solvers/conic_solvers/xpress_conif.py
- cvxpy/reductions/solvers/defines.py
- cvxpy/reductions/solvers/qp_solvers/xpress_qpif.py
- cvxpy/tests/test_conic_solvers.py
- cvxpy/tests/test_examples.py
- cvxpy/tests/test_mip_vars.py
- doc/source/install/index.rst
- doc/source/related_projects/index.rst
- doc/source/tutorial/advanced/index.rst
- examples/advanced/xpress_example.py
Adds bindings to FICO Xpress to solve linear, quadratic, and second-order cone problems.
> Add FICO Xpress to set of solvers

- cvxpy/problems/problem.py
- cvxpy/settings.py
- cvxpy/tests/test_derivative.py
This is a small PR, to add a warning for inaccurate solutions.
> Warning for inaccurate solutions

- doc/source/tutorial/dqcp/index.rst
Only occurrence I found from a quick search.
> fix a tutorial typo

- cvxpy/problems/problem.py
- cvxpy/tests/test_conic_solvers.py
- doc/source/contributing/index.rst
- doc/source/tutorial/advanced/index.rst
- doc/source/updates/index.rst
Self-explanatory. @SteveDiamond let me know if any changes are needed before merging.
(I'll note the commit message is incorrect. The issue is 1122, not 1142.)
> resolve the four points mentioned in GitHub issue 1122.

- cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py
Reduce problem data tensor on first call to apply parameters.
An intermediate `ParamConeProg` is constructed when canonicalizing cone
programs; this `ParamConeProg` is never actually evaluated, so reducing
its tensor is unnecessary.
@sbarratt
> Lazily reduce problem data tensor

- cvxpy/reductions/matrix_stuffing.py
> Just an unused comment

- cvxpy/reductions/solvers/conic_solvers/xpress_conif.py
- cvxpy/reductions/solvers/qp_solvers/xpress_qpif.py
- doc/source/install/index.rst
The main change is improved performance for problems with many equality AND many inequality constraints. Previously Xpress added both classes of constraints as one, causing performance loss due to a Python loop. Now it only uses API functions. Other additions: statistics on CPU time and objective value; an rST entry.
> Xpress speed improvements

- pyproject.toml
In theory this should fix #1229.
> use oldest supported numpy in pyproject.toml

- pyproject.toml
- setup.py
This might help with #1229 (per the suggestion from @BastiaanvG )
> python-version-specific numpy versions in pyproject.toml

- cvxpy/cvxcore/src/LinOpOperations.cpp
> two fewer copies in cvxcore

- cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py
- cvxpy/reductions/utilities.py
- cvxpy/tests/test_constraints.py
NonPos is not working correctly in the current master. This change fixes the problem.
> Fix NonPos

- cvxpy/problems/problem.py
- cvxpy/tests/test_problem.py
as discussed in https://github.com/cvxgrp/cvxpy/issues/966
> param_dict and var_dict

- cvxpy/problems/problem.py
Only print that compilations will take less time when parameters are involved
> Minor edit to verbose compilation output

- cvxpy/__init__.py
Fixes #1308.
I did not add any tests, as I could not find any similar ones (but I did check locally that it indeed works :blush: ). Let me know if it's okay.
> Add USER_LIMIT status to init so that it can be accessed with cvxpy.USER_LIMIT

- cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
> Cache ParamProg in MOSEK interface

- doc/source/install/index.rst
Some small improvements I happened across while reading through the [install page](https://www.cvxpy.org/install).
> Minor install doc improvement

- cvxpy/atoms/affine/reshape.py
- cvxpy/cvxcore/python/canonInterface.py
- cvxpy/expressions/constants/callback_param.py
- cvxpy/expressions/constants/constant.py
- cvxpy/expressions/constants/parameter.py
- cvxpy/expressions/leaf.py
- cvxpy/expressions/variable.py
- cvxpy/problems/param_prob.py
- cvxpy/problems/problem.py
- cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py
- cvxpy/reductions/qp2quad_form/qp_matrix_stuffing.py
- cvxpy/transforms/indicator.py
- examples/advanced/circuits.py
- examples/advanced/numpy_test.py
- examples/advanced/optimal_control.py
- examples/extensions/mixed_integer/assign.py
- examples/extensions/mixed_integer/card.py
- examples/extensions/mixed_integer/choose.py
- examples/extensions/mixed_integer/noncvx_variable.py
- examples/extensions/ncvx/boolean.py
- examples/floor_packing.py
- examples/flows/commodity_flow.py
- examples/flows/leaky_edges.py
- examples/flows/max_flow.py
Includes some alphabetizing of import lines.
> More types

- cvxpy/problems/objective.py
Adds a name field to objective base class.
> A tiny PR to fix #1314

- cvxpy/atoms/__init__.py
- cvxpy/atoms/elementwise/loggamma.py
- cvxpy/tests/test_atoms.py
This adds the approximation of the log-gamma function from #228. I followed the naming convention from scipy.
> loggamma approximation

- cvxpy/atoms/axis_atom.py
- cvxpy/atoms/elementwise/ceil.py
- cvxpy/expressions/leaf.py
- cvxpy/interface/numpy_interface/ndarray_interface.py
- cvxpy/interface/numpy_interface/sparse_matrix_interface.py
See https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Fixes #1334
> Use builtin types instead of deprecated numpy aliases

- cvxpy/reductions/solvers/conic_solvers/scs_conif.py
Issue Link: #1474 
```py
n_sec = 20
np.random.seed(315)
mu = np.random.random(n_sec)
random_mat = np.random.rand(n_sec, n_sec)
C = np.dot(random_mat, random_mat.transpose())
x = cp.Variable(n_sec)
prob = cp.Problem(cp.Minimize(cp.QuadForm(x, C)), [cp.sum(x) == 1, 0 <= x, x <= 1, x @ mu >= np.max(mu) - 1e-6])
prob.solve(cp.SCS)
```
Tested under SCS version `2.1.4` and `1.2.6`.
> Fix SCS requirement issue (Issue #1474)

- CONTRIBUTING.md
- README.md
- conda-recipe/meta.yaml
- doc/source/community/index.rst
- doc/source/conf.py
- doc/source/contributing/index.rst
- doc/source/examples/index.rst
- doc/source/faq/index.rst
- doc/source/index.rst
- doc/source/install/index.rst
- doc/source/related_projects/index.rst
- doc/source/tutorial/advanced/index.rst
- doc/source/tutorial/dgp/index.rst
- doc/source/tutorial/dqcp/index.rst
- doc/source/updates/index.rst
- setup.py
I updated the documentation as requested by NumFOCUS. I pointed developers more clearly to the discord and linked to the code of conduct and governance. I also removed some of the old "news" items to clean up the front page.
> Documentation changes

- doc/source/contributing/index.rst
> Document isort on website

- cvxpy/expressions/expression.py
- cvxpy/tests/test_expressions.py
> Update Expression.curvature to include log-log curvature

- PROCEDURES.md
This PR adds the PyPI release procedure as a follow-up tp #1598.
> [doc] PyPI release procedure

- cvxpy/atoms/affine/upper_tri.py
- cvxpy/problems/problem.py
> [doc] Fix code blocks

- doc/source/tutorial/advanced/index.rst
Docfix for Attributes section in the advanced section
> Docfix leaf documentation in attributes docs

- cvxpy/atoms/axis_atom.py
- cvxpy/atoms/norm1.py
- cvxpy/atoms/pnorm.py
- cvxpy/tests/test_grad.py
Fix bugs in gradient computation.
Issue link (if applicable): https://github.com/cvxgrp/dccp/issues/75
> Fix bugs in gradient computation

- cvxpy/reductions/solvers/conic_solvers/cbc_conif.py
Handle new CyLP statuses added in https://github.com/coin-or/CyLP/pull/150
@tkralphs
> CBC: Handle new CyLP statuses

- doc/source/install/index.rst
- setup.cfg
Add `extras_require` mapping solver names to the pip-installable distribution providing it
> pip install cvxpy[GLOP,XPRESS]

- cvxpy/reductions/solvers/conic_solvers/glop_conif.py
- cvxpy/reductions/solvers/conic_solvers/pdlp_conif.py
> Fix TypeError in GLOP and PDLP interfaces

- cvxpy/problems/problem.py
> update error message for mixed-integer problems

- CONTRIBUTING.md
make it easier to just copy-paste
> minor update on code example of benchmark run

- CONTRIBUTING.md
Issue link (if applicable): https://github.com/cvxpy/cvxpy/issues/1653
This is a small adaption to the docs to let users know that in some cases isort might not behave as expected, which indicates that the config was not picked up correctly. 
@yasirroni suggested making `pre-commit` the default. I have the slight feeling that the current approach of "regular" installation still provides a lower hurdle for inexperienced users. 
cc: @rileyjmurray @yasirroni [@erelsgl](https://github.com/erelsgl)
> [Docs] Adapt isort documentation

- doc/source/examples/dgp/max_volume_box.rst
Fix typo in max volume example
Issue link (if applicable): #1786
> Fix typo in max volume example

- .github/workflows/build.yml
This will not upload files if they already exist on pypi. As a result, the upload jobs will pass rather than fail.
> Add check to pypi uploads

- cvxpy/atoms/quad_form.py
- cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py
- cvxpy/tests/test_quad_form.py
I made a small mistake in the tests.
> Follow up with assume PSD

- cvxpy/atoms/affine/trace.py
- cvxpy/tests/test_atoms.py
Improve sign analysis for trace when argument is PSD/NSD. 
> Trace sign analysis 

- continuous_integration/install_dependencies.sh
- continuous_integration/test_script.sh
Starting by simplification of dependency installation. Many cases are meanwhile obsolete.
Issue link (if applicable): CI failing, e.g. in #1840 #1867 #1872
> [CI] Fix dependency installation

- cvxpy/tests/test_problem.py
> Minor test formatting fix.

- .github/workflows/scorecards.yml
Signed-off-by: Joyce Brum <joycebrum@google.com>
Upgraded the scorecard-action to 2.0.6
Issue link (if applicable): Closes #1925
> Fix action error by upgrading scorecard action to 2.0.6

- .github/workflows/test_backends.yml
- cvxpy/cvxcore/python/canonInterface.py
Get the new backend workflow working (it only executed the first time after merging the backend PR).
> Fix backend workflow

- doc/source/related_projects/index.rst
Mention CVXPYgen in related projects.
> cvxpygen in related projects

- cvxpy/constraints/exponential.py
- doc/source/api_reference/cvxpy.constraints.rst
- doc/source/index.rst
- doc/source/updates/index.rst
Adding the release notes for 1.3 to the web docs.
> Release notes 1.3

- .github/workflows/build.yml
> Redeploy 1.3

- doc/source/tutorial/functions/index.rst
Change `x` to `X` in second `tv` function definition
Issue link (if applicable): N/A
> Update Atomic Functions Docs

- cvxpy/atoms/elementwise/power.py
- cvxpy/reductions/dcp2cone/dcp2cone.py
- cvxpy/tests/test_conic_solvers.py
Adds special case handling for power in the objective for the quadratic objective + conic constraints canonicalization path.
Issue link (if applicable): #2059
> Fix bug with quadratic objective and conic constraints

- .devcontainer/devcontainer.json
- .devcontainer/startup.sh
- doc/source/contributing/index.rst
- doc/source/install/index.rst
This makes it faster and easier to start developing CVXPY by preconfiguring the codespace.
To test:
Click on the `Code` button in this PR and `Create codespace on adds-devcontainer`.
Docs:
> Adds devcontainer support

- doc/source/faq/index.rst
- doc/source/tutorial/advanced/index.rst
- doc/source/tutorial/dcp/index.rst
Replaces some Python 2 print statements with functions.
There are a few more places in larger examples, but these would need a larger overhaul.
> Fixes Python 2 print statements

- cvxpy/__init__.py
This adds Objective as a top level import, to facilitate type hinting.
Issue link (if applicable): #2109
> Add objective as top level import

- .github/workflows/build.yml
> [CI] Use build instead of setup.py

- cvxpy/reductions/solvers/conic_solvers/copt_conif.py
- cvxpy/reductions/solvers/qp_solvers/copt_qpif.py
> Map imprecise status of COPT to optimal_inaccurate status of CVXPY

- PROCEDURES.md
> Updates PROCEDURES

- doc/source/tutorial/advanced/index.rst
I found some spots in the solver documentation which can be improved from my point of view:
1. Xpress solver has some issues with formatting (please find screenshot attached).
2. The IBM cplex link refers to a general ibm product website ([Old link](https://www.ibm.com/products?ibmTopics%5B0%5D%5B0%5D=cat.topic%3AConsultingServices&ibmTopics%5B1%5D%5B0%5D=cat.topic%3AECommerce)) and I referred to a more specific cplex related side ([New link](https://www.ibm.com/docs/en/icos)).
> Fix solver docu

- cvxpy/interface/scipy_wrapper.py
Meant to fix this before we merged...
> Fixes place holder in scipy_wrapper.py deprecation

- .github/workflows/build.yml
- README.md
- doc/source/index.rst
- requirements.txt
- setup.py
Adds Clarabel as a dependency/requirement.
> Add clarabel requirement

- cvxpy/lin_ops/canon_backend.py
> Follow-up backend 1.4 release prep

- cvxpy/interface/scipy_wrapper.py
- doc/source/updates/index.rst
Adds release notes and fixes the type of Warning being raised in scipy_wrapper.
> Prep for 1.4 release

- PROCEDURES.md
- doc/source/index.rst
> Bumps version number in docs and updates procedures

- doc/source/index.rst
- setup/versioning.py
> Preps for 1.5

- cvxpy/reductions/solvers/defines.py
Fixes https://github.com/cvxpy/cvxpy/issues/2257
> change conic solver preference order

- doc/source/examples/index.rst
- doc/source/short_course/index.rst
Fixing all links to the cvx_short_course
See issue #2263
> Fixing links to cvx_short_course

- continuous_integration/install_dependencies.sh
- pyproject.toml
For https://github.com/bodono/scs-python/issues/77; @phschiele @SteveDiamond you can try the CI on this PR, hopefully it works.
> Use oldest-supported-numpy

- doc/source/install/index.rst
- doc/source/tutorial/advanced/index.rst
This fixes the links to NAG website which was restructured.
> updating NAG website links in doc

- cvxpy/problems/problem.py
Scalarizes the constraint count instead of just reporting the number of constraints.
> Fixes how constraints are recorded in verbose=True

- .pre-commit-config.yaml
- cvxpy/interface/matrix_utilities.py
- cvxpy/lin_ops/tree_mat.py
- cvxpy/problems/problem.py
- cvxpy/reductions/cone2cone/affine2direct.py
- cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
- cvxpy/transforms/indicator.py
- pyproject.toml
Thanks @PTNobel for the ping about https://numpy.org/devdocs/numpy_2_0_migration_guide.html
I ran `ruff check . --preview` locally, as the "NPY201" rule is still in preview. Nevertheless, I added it to the linting rules so it will become active at some point.
> Use new NumPy API

- cvxpy/expressions/constants/constant.py
- cvxpy/tests/test_expressions.py
Adds functionality to give constants names.
Issue link (if applicable): https://github.com/cvxpy/cvxpy/discussions/2322
@pgkirsch @rileyjmurray
> Named constants

- doc/source/_static/css/styling.css
- doc/source/conf.py
- doc/source/tutorial/constraints/index.rst
- doc/source/tutorial/solvers/index.rst
The changes made in #2312 were overwritten by the advanced features refactor.
This PR re-introduces those documentation changes on the newly introduced Daqp solver interface.
Other minor changes:
- renaming css file to ``styling.css``
- hiding a duplicated title page on the left navigation bar
- adding important message for attributes and their effect on dual variables.
> Daqp solver info and other doc updates

- PROCEDURES.md
- doc/source/conf.py
This PR adds the minor cvxpy version 1.4 as a dropdown option in the docs.
It also fixes the hyperlink for the latest doc.
> update versions in the dropdown for the new theme

- cvxpy/settings.py
- setup.py
Configures build for Pyodide.
Issue link (if applicable): https://github.com/pyodide/pyodide/pull/4587#discussion_r1509971530
> Pyodide build

- .github/workflows/build.yml
- continuous_integration/install_dependencies.sh
The XPRESS installation has failed in master.
Using this opportunity to update package installs according to current availability on PyPI/conda.
Also adds tests for Python 3.12.
> [CI] Update dependency installs during test

- .github/workflows/build.yml
Follow-up to #2399.
The new version requires unique artifact names.
> [CI] Fix build wheels artifact upload

- .github/workflows/scorecards.yml
Scorecard action is failing after (partial) workflow updates.
Update the complete action according to the upstream recommendations:
https://github.com/ossf/scorecard/blob/main/.github/workflows/scorecard-analysis.yml
See https://github.com/ossf/scorecard-action for more information.
> Updates scorecard action

- README.md
Just realized that Clarabel was missing from the list of solvers in the text.
> [Docs] Small README update

- PROCEDURES.md
We did not mention the GitHub releases yet in our `PROCEDURES` file.
> [Doc] Adds GitHub release description to PROCEDURES

- cvxpy/reductions/canonicalization.py
- cvxpy/reductions/dgp2dcp/dgp2dcp.py
- cvxpy/reductions/dqcp2dcp/dqcp2dcp.py
- cvxpy/reductions/solvers/bisection.py
- cvxpy/tests/test_dqcp.py
Changes DQCP canonicalization to fix several bugs.
#2373
#2386
> Fix DQCP bugs

- README.md
- doc/source/index.rst
Per discussion with Philipp, added Parth and removes duplicate Philipp to README and index.rst.
> Updates notable contributors

- cvxpy/tests/test_coeff_extractor.py
- cvxpy/utilities/coeff_extractor.py
See below for bug description in line.
Issue link (if applicable): Closes #2437
> [Bug] Fixes QP canonicalization

- README.md
fix link to "Choosing a solver" in README.md (was not updated in #2309)
> DOC: Fix link in README.md

- .github/workflows/build.yml
- doc/source/index.rst
- doc/source/updates/index.rst
- setup/versioning.py
Adds the change log and the fixes to the cvxpy-base build in the release/1.5.x branch.
> Preps for 1.6.0

- cvxpy/reductions/solvers/solving_chain.py
This PR updates the wording of the `ECOS_DEP_DEPRECATION_MSG` `FutureWarning` to address issue #2442.
> Clarify ECOS_DEP_DEPRECATION_MSG, including how to suppress the warning. (#2442)

- doc/source/examples/applications/min_condition_number_by_scaling.rst
- doc/source/examples/index.rst
- examples/notebooks/WWW/min_condition_number_by_scaling.ipynb
Added an example "Minimizing condition number by scaling"
> Added Minimizing condition number by scaling example

- continuous_integration/install_dependencies.sh
This check didn't do anything, because the correct syntax would have been 
```
&& [[ "$RUNNER_OS" != "MacOs" ]]
```
Removed it, less logic in the file.
> [CI] Remove unnecessary check

- README.md
> Fix broken citation URL in README.md

- .github/workflows/build.yml
- cvxpy/reductions/solvers/qp_solvers/xpress_qpif.py
Explanation in title. Noticed this in the most recent CI builds.
Related [dcoumentation](https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/COLS.html) for the changed attribute.
ADDITIONAL CHANGE: deleting sonarcloud build because it is causing problems. 
> fix issue in xpress interface for ``prob_.attribute``

- doc/source/contributing/index.rst
This PR removes completed projects and introduces new ones ahead of the august 2024 community call. 
> Updating wishlist with new projects

- cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
The array is unused in the code path for any currently supported version of Gurobi (>= v9.5) so can be removed to avoid unnecessary overhead. Additionally, in Python 3.12, creating this array triggers a [memory leak due to a bug in gurobipy](https://support.gurobi.com/hc/en-us/articles/27635574446353-Memory-leak-in-gurobipy-with-Python-3-12), so it would be good to remove it from cvxpy to reduce user impact.
Figured I'd start with a minimal change, but I'm happy to do a larger rewrite to remove the old workarounds in `gurobi_qpif.py`.
> Avoid unnecessarily creating numpy array of Var objects

- cvxpy/tests/test_expressions.py
- cvxpy/utilities/key_utils.py
Thanks @jonathanberthias for the suggestions!
> Applying suggestions for improvement on string repr of special index

- continuous_integration/install_dependencies.sh
This PR changes the install instructions for pyscipopt in hopes of fixing recent CI issues.
It also adds some minor changes to installing sdpa-python as well as cleaning up redundancy within the installation conditions.
> CI: Refactoring installation of dependencies

- doc/source/tutorial/solvers/index.rst
This fixes the links to the NAG website which has been restructured.
> Updating link to NAG website in documentation

- .github/workflows/build.yml
#2585 refactored the split between regular/base images and introduced an issue with artifact upload naming.
> Fix artifact upload

- continuous_integration/install_dependencies.sh
> CI: avoid installing pyscipopt and cylp for all python versions

- .github/workflows/build.yml
- continuous_integration/install_dependencies.sh
also updates the ubuntu version to 22.04.
final change is updating the numpy/scipy versions to their latest.
> CI: updating CI for diffcp new release

- README.md
- cvxpy/tests/test_quantum_rel_entr.py
- doc/source/contributing/index.rst
- doc/source/tutorial/advanced/index.rst
- doc/source/updates/index.rst
> DOC: Updating wishlist for new release (1.6)

- cvxpy/reductions/solvers/conic_solvers/diffcp_conif.py
I bumped the minor version on diffcp because of the new features, and that broke our version check code.
> Fixes diffcp imports

- README.md
- doc/source/conf.py
- doc/source/index.rst
- setup/versioning.py
CVXPY 1.6 just got released!! This PR is just setting up a prerelease for 1.7.0 according to the instructions in procedure.md
I also added a discord badge for the README.
> preps 1.7.0

- README.md
- doc/source/index.rst
Update maintainers and core contributors list
> Update maintainers and core contributors list

- .github/workflows/build.yml
- cvxpy/tests/test_quantum_rel_entr.py
Issue link (if applicable): https://github.com/cvxpy/cvxpy/issues/2677
> Skip the quantum test (for Windows and Python 3.13)

- cvxpy/atoms/inv_prod.py
This fixes the following broken snippet:
```python
x = cp.Variable()
t = cp.inv_prod(x)
assert t.curvature == 'CONSTANT'
```
I'm open to other ways to fix this and overall I'm not sure the implementation is correct at all:
1. Why are we summing the shape and not producting it together?
> Fixes `cp.inv_prod(cp.Variable()).curvature`

- doc/source/functions/functions_table.rst
> Fix norm(X, 2) in functions table

- cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
- cvxpy/tests/test_conic_solvers.py
Updates for clarabel v0.10.0. Adds warm start functionality to wrapper.
> Updates for clarabel v0.10.0. 

- cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
A followup to #2710 that should fix the Mosek interface.
> Fixes mosek interface

- doc/source/updates/index.rst
> Patch 1.6.1 release notes

- cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py
- cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
- cvxpy/tests/solver_test_helpers.py
- cvxpy/tests/test_conic_solvers.py
> Send variable bounds to Gurobi

- cvxpy/reductions/solvers/qp_solvers/xpress_qpif.py
- [] New feature (backwards compatible)
> patch empty breaking empty rownames for xpress>=9.5

- cvxpy/reductions/solvers/conic_solvers/qoco_conif.py
Added apply function to qoco_conif.py. This addition is necessary to add QOCOGEN to cvxpygen.
> Added apply function to qoco_conif.py

- cvxpy/atoms/dotsort.py
- cvxpy/reductions/eliminate_pwl/canonicalizers/dotsort_canon.py
- cvxpy/reductions/qp2quad_form/canonicalizers/__init__.py
- cvxpy/reductions/solvers/conic_solvers/highs_conif.py
- cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
- cvxpy/reductions/solvers/solving_chain.py
- cvxpy/tests/test_conic_solvers.py
- cvxpy/tests/test_qp_solvers.py
Fixes https://github.com/cvxpy/cvxpy/issues/2836
- [N/A] Add our license to new files.
> [HIGHS conif] Maps dual solution back to dual variables

- doc/source/install/index.rst
- doc/source/tutorial/solvers/index.rst
As title. 
Issue link (if applicable): https://github.com/bodono/scs-python/pull/136
> Adds SCS cuDSS, fixes a typo in the SCS docs, and adds CuClarabel install.

- doc/source/api_reference/cvxpy.atoms.affine.rst
- doc/source/index.rst
- doc/source/install/index.rst
- doc/source/tutorial/constraints/index.rst
- doc/source/updates/index.rst
This PR adds some docs to the cvxpy website.
More things to add in docs:
- conic quadratic standard form
- docstrings for new atoms?
- some examples for multiple attributes
> DOC: prep for 1.7.0 release

- cvxpy/utilities/citations.py
- doc/source/tutorial/solvers/index.rst
Added CuClarabel citation and repo link
> Added CuClarabel citation and repo link

- cvxpy/atoms/__init__.py
- cvxpy/atoms/affine/trace.py
- cvxpy/reductions/complex2real/canonicalizers/__init__.py
- cvxpy/reductions/dgp2dcp/canonicalizers/__init__.py
- cvxpy/tests/test_atoms.py
Implement Trace(AB) using vdot for performance efficiency. Move trace to trace_internal and use trace as a wrapper function that determines when to use vdot for a faster computation `vdot(A,B)` versus fall back to traditional trace `trace_internal`
Reference: https://github.com/cvxpy/cvxpy/discussions/2359
In experimental testing we see 
- 7x improvement on canonicalization of the following problem reducing execution time from 7.46 seconds to 1.05 seconds
- We also see 10x improvement in ``semidefinite_programming.SemidefiniteProgramming.time_compile_problem``
```py
import time
np.random.seed(0)
n = 500     # dimension (number of variables)
N = 100    # number of samples
A = np.random.randn(n, n)
true_cov = A @ A.T + n * np.eye(n)  # SPD matrix
X = …
```
> Implement Trace(AB) using vdot for performance efficiency

- cvxpy/atoms/affine/unary_operators.py
- cvxpy/tests/test_expressions.py
Correct string representation of NegExpression
Issue link (if applicable): #2806
> Correct string representation of NegExpression

- README.md
> Fix benchmark link

- cvxpy/reductions/solvers/conic_solvers/xpress_conif.py
> add feasible as solver states for xpress

- cvxpy/reductions/solvers/conic_solvers/xpress_conif.py
- cvxpy/reductions/solvers/qp_solvers/xpress_qpif.py
> Passing original variable names and constraint ids to improve debugging
