README.md
Just a quick PR to add syntax highlighting to the readme.
Instead of
```
from cvxpy import *
```
We have 
```python
from cvxpy import *
```
=> Readme: syntax highlighting

cvxpy/atoms/affine/add_expr.py, cvxpy/atoms/affine/index.py, cvxpy/atoms/atom.py, cvxpy/atoms/elementwise/power.py, cvxpy/atoms/geo_mean.py, cvxpy/constraints/leq_constraint.py, cvxpy/problems/objective.py, cvxpy/tests/test_atoms.py, cvxpy/tests/test_constraints.py, cvxpy/tests/test_objectives.py
This function allows one to create a (shallow) copy of an atom, with an optional ARGS parameters to change the args of the atom.
This commit includes a a generic `copy()` function for all atoms and 4 specific `copy()` functions for AddExpression, index, power, and geo_mean.
=> Implement copy function for each atom

cvxpy/problems/problem_data/matrix_data.py, cvxpy/tests/test_problem.py
Previously we couldn't pickle problems that are already solved, as `MatrixCache.F` is a function that cannot be pickled. I changed `MatrixCache.F` to be a function object (thanks to `functools.partial()`) to fix this. This should allow pickling and sending solved problems through `multiprocessing`.
=> Change MatrixCache.F to allow pickling solved problems.

conda-recipe/meta.yaml, cvxpy/problems/problem.py, cvxpy/settings.py, cvxpy/tests/test_problem.py, cvxpy/transforms/__init__.py, cvxpy/transforms/separable_problems.py, doc/source/install/index.rst, setup.py
If problem is separable, we split it into smaller problems and solve them in parallel.
To enable the option, run `problem.solve(parallel=True)`.
I cache the separable problems (as a list) by decorating `problem._separable_problems` with `lazyprop`. I'm still not sure how I should detect if the objective or constraint has changed to recompute these separable problems.
=> Implement solving separable problems in parallel

examples/notebooks/WWW/parade_route.ipynb
The parade route example doesn't run the last cell correctly since `xsol` isn't defined. This simply fixes that. Now the notebook runs without error for me.
I suppose to verify, you can download and run the file.
https://raw.githubusercontent.com/jwkvam/cvxpy/fix-parade-route/examples/notebooks/WWW/parade_route.ipynb
=> in parade route example, store solution as `xsol`

cvxpy/problems/solvers/glpk_mi_intf.py, cvxpy/tests/test_solvers.py
Resolves #251 for GLPK_MI. Params need to be explicitly set to cvxopt.glpk.options rather than cvxopt.solvers.options since glpk.ilp is not part of cvxopt LP solvers.
=> GLPK_MI setting solver params

cvxpy/atoms/pnorm.py, cvxpy/tests/test_constant_atoms.py
Hi Steven,
This makes it much easier to write sum-of-norms regularization e.g. without unrolling the sum (for example, network lasso paper you dont need |E| terms, http://web.stanford.edu/~hallac/Network_Lasso.pdf)
This is consistent with how linalg.norm() works, although i just added the code for p=2 for now.
Cheers,
Matt
=> add axis parameter to pnorm(x, 2)

cvxpy/atoms/geo_mean.py, cvxpy/tests/test_problem.py
@SteveDiamond, my changes in geo_mean.py to detect and handle row and column vectors differently might be a hack. Is there a better way to do that?
=> Fix geo_mean bug where row vector input (hstack) wasn't working properly.

cvxpy/atoms/quad_form.py, cvxpy/tests/test_problem.py, cvxpy/tests/test_quad_form.py
Some changes to quad_form and related test scripts.
1. Allow asymmetric P: This change is not necessary, but since ``x^T P x`` is a scalar anyway, the specification is unambiguous even when P is asymmetric. This is handled by setting ``P = (P+P^T)/2`` internally and should not touch the original data.
2. Allow indefinite P, but with a warning message: Currently quad_form rejects P with both positive and negative eigenvalues. The behavior of quad_form doesn't change when P is positive or negative semidefinite. With the proposed change, users can use indefinite P, but will get a warning message when that happens. quad_form will then return a difference of convex function. More specifically, when ``P = M1*M1^T - M2*M2^T``, ``quad_form(x, P)`` returns ``sum_squares(M1^T * x) - …
=> quad_form to allow indefinite and asymmetric matrices

cvxpy/problems/solvers/mosek_intf.py, cvxpy/tests/test_solvers.py, doc/source/tutorial/advanced/index.rst
I recently ran into an issue where cvxpy would return infeasible solutions despite reporting an optimal solution status when using MOSEK. Since I wanted to play around with the optimizer parameters, I checked the cvxpy docs and realized there was currently no way to override MOSEK's default parameters, so I hacked up a quick patch to add support for doing so.
=> Add support for tuning MOSEK optimizer parameters

cvxpy/atoms/atom.py, cvxpy/expressions/constants/callback_param.py
Doesn't change much, but is helpful for codegen.
=> callback params now store the atom they represent, not just cb function

continuous_integration/install.sh
According to [the installation issues related to CVXOPT v1.1.9](https://github.com/cvxopt/cvxopt/issues/79), we need SuiteSparse to install CVXOPT. This pull request edits continuous_integration/install.sh to do so.
Based on [the discussion about having the option to fetch SuiteSparse automatically](https://github.com/cvxopt/cvxopt/issues/80), we shouldn't need it for long. Until then, this prepares SuiteSparse.
=> Prepare SuiteSparse to install CVXOPT for testing on CI services

examples/consensus_admm.py
The consensus ADMM example was missing two variables: gamma (for
weighting the L_1 norm) and NUM_PROCS (the number of threads of the
multiprocessing pool).
Related: since I've noticed multiple examples with similar issues (i.e. missing problem variables), would the maintainers prefer a bulk PR that attempts to update all the example scripts? Or one PR per example?
=> example: consensus ADMM: add missing variables

examples/admm_lasso.py
Similar to #324, this PR fixes an issue in the ADMM Lasso example where variables gamma and NUM_PROCS were previously undefined.
@SteveDiamond Looks like I may have been mistaken about how many examples needed updating. At the moment, it seems only ADMM Lasso had the same issue.
=> examples: ADMM Lasso: fix missing variables

cvxpy/problems/solvers/solver.py, cvxpy/tests/test_problem.py
Provide a specific error indicating why a given solver was rejected
rather than a generic "could not solve problem" error.
Before/After:
```
(cvxpy) [~/quantopian/cvxpy]@(master:7deee4d172)$ python repro.py
Traceback (most recent call last):
File "repro.py", line 11, in <module>
problem.solve(solver='SCS')
File "/home/ssanderson/quantopian/cvxpy/cvxpy/problems/problem.py", line 207, in solve
return self._solve(*args, **kwargs)
File "/home/ssanderson/quantopian/cvxpy/cvxpy/problems/problem.py", line 319, in _solve
solver.validate_solver(constraints)
File "/home/ssanderson/quantopian/cvxpy/cvxpy/problems/solvers/solver.py", line 137, in validate_solver
"The solver %s cannot solve the problem." % self.name()
cvxpy.error.SolverError: The solver SCS cannot solve the problem.
(cvxpy) …
```
=> ENH: Clearer error when rejecting a solver.

cvxpy/atoms/quad_form.py
Previous version divides w by scale even when scale is very small. The following lines generate several numpy warnings. This should stop numpy complaining about w_scaled containing invalid values.
=> correct behavior for very small scale value

cvxpy/problems/solvers/mosek_intf.py, cvxpy/tests/test_solvers.py
An update to the Mosek interface which takes into account the basic solution ``mosek.soltype.bas`` in addition to ``mosek.soltype.itr``. Hopefully resolves issues #335, #327. Serves the same purpose as proposed PR #328.
=> Basic solution in Mosek

.gitignore, cvxpy/expressions/variables/bool_var.py
After upgrading cvxpy from version 0.3.4 to 0.4.10 the mixed integer optimisation using ECOS_BB seems to be failing with an error "ValueError: Invalid sign for Bool value". The problem is caused by the method is_positive() which now returns True. Bool is neither positive nor negative though. 
The method is_negative() override returns the same value as the base class version (Variable class) so it's redundant. 
Original issue:  https://github.com/cvxgrp/cvxpy/issues/364
=> fixed issue 364

cvxpy/expressions/variables/bool_var.py, cvxpy/expressions/variables/int_var.py, cvxpy/expressions/variables/nonneg.py, cvxpy/expressions/variables/variable.py, cvxpy/tests/test_expressions.py, cvxpy/tests/test_mip_vars.py
Addresses #368.
I've chosen to show the name of the variables only if it was provided while variable initialization; otherwise there is no benefit from seeing it.
Also, I've not update the `repr` for `Symmetric` and `Semidef` variables because their `repr` do not conform to the default pattern currently.
I'll be happy to make any stylistic changes.
=> EHN Show names in repr, if provided.

cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py
CVXPY was doing matrix refactorization on a simple lasso example even when warm_start was enabled. This is the code:
from cvxpy import *
m = 20
n = 10
A = np.random.randn(m, n)
b = np.random.randn(m)
x = Variable(n)
gamma = Parameter(nonneg=True)
obj = sum_squares(A*x - b) + gamma*norm1(x)
prob = Problem(Minimize(obj))
gamma.value = 100.
for i in range(20):
prob.solve(warm_start=True, rho=10., verbose=True)
print("Solve time:", prob.solver_stats.solve_time)
gamma.value = gamma.value / 2
The bug was in comparing current constraint matrix with the cached data.
=> Fixed the bug with warm start

cvxpy/problems/solvers/cbc_intf.py, examples/tsp_mip.py
Not ready to merge!
I think commit ef5f95477 broke Cbc (mip_tsp.py breaks after changes needed for 1.0).
The problem is rooted in:
model.addConstraint(x[idxs] >= 0)
where *lhs* will not have the same dimension as the problem, needed for this overloaded-usage.
I still feel somewhat uneasy with cylp (and it's nearly non-happening development), but i made use of the ```A * x >= 0``` approach in the past (with success), while explicit usage of bound-setters crashed (maybe i should recheck that). In regards to this usage, the sparse-matrix approach i used here should be quite efficient.
I also changed the calls in regards to solving for Cbc and Clp, as i realized a few weeks ago, that preprocessing never seemed to be used (Cbc was slower than GPLK and i wondered why). One should probably check …
=> Fixed and improved Cbc-interface

cvxpy/atoms/log_sum_exp.py
`log_sum_exp` is erroneously marked as non-increasing and positive.
This seems to have been introduced in
https://github.com/cvxgrp/cvxpy/commit/9366ccb54440ae0354f52cfbd14f30cba371b4db#diff-e6d9effeb355db619cf5bf6d59da6685
=> Fix for log_sum_exp

cvxpy/tests/test_atoms.py, cvxpy/tests/test_domain.py, cvxpy/tests/test_expressions.py, cvxpy/tests/test_problem.py, cvxpy/tests/test_sign.py
1. `test_sign.py` failed because the name of unittest's method setUpClass() was wrong. This is now fixed.
2. I renamed `assertAlmostEquals()` to `assertAlmostEqual()` and `assertEquals()` to `assertEqual()`. Those are [deprecated aliases](https://docs.python.org/3/library/unittest.html#deprecated-aliases).
=> Fixes to the tests

cvxpy/CVXcanon/tests/python/364A_scripts/material_blend.py, cvxpy/atoms/affine/add_expr.py, cvxpy/atoms/affine/affine_atom.py, cvxpy/atoms/affine/hstack.py, cvxpy/atoms/atom.py, cvxpy/atoms/elementwise/elementwise.py, cvxpy/atoms/elementwise/maximum.py, cvxpy/constraints/constraint.py, cvxpy/constraints/exponential.py, cvxpy/constraints/nonlinear.py, cvxpy/constraints/second_order.py, cvxpy/expressions/expression.py, cvxpy/expressions/leaf.py, cvxpy/problems/problem_data/matrix_data.py, cvxpy/problems/solvers/glpk_mi_intf.py, cvxpy/problems/solvers/ls_intf.py, cvxpy/reductions/complex2real/atom_canonicalizers/aff_canon.py, cvxpy/reductions/complex2real/complex2real.py, cvxpy/reductions/solvers/conic_solvers/conic_solver.py, cvxpy/reductions/solvers/conic_solvers/ls_conif.py, cvxpy/reductions/solvers/conic_solvers/mosek_conif.py, cvxpy/tests/test_nonlinear_atoms.py, cvxpy/tests/test_scs.py, cvxpy/tests/test_shape.py, cvxpy/transforms/indicator.py, cvxpy/transforms/scalarize.py, cvxpy/utilities/canonical.py, cvxpy/utilities/key_utils.py, cvxpy/utilities/shape.py, cvxpy/utilities/sign.py
This PR is an evolution of #453.
1. When using the `any()`, `all()`, `sum()`, ... Python built-in functions, it's more efficient to pass the parameters as [generator expressions](https://www.python.org/dev/peps/pep-0289/) than as list comprehensions. For example, if `any()` gets any `True` value for the generator, it can avoid to compute all the other elements. I systematically replaced all unneeded list comprehensions with generator expressions.
2. The return values of some functions like `is_constant()`, `is_convex()`, `is_zero()` [don't change](https://gitter.im/cvxgrp/cvxpy?at=5abc2ed57c3a01610d85ec1a) between invocations. They can be cached for any expression, in order to avoid useless recomputations. This should mitigate some of the problems about the …
=> Efficiency: use generator expressions, cache expression properties

cvxpy/reductions/cvx_attr2constr.py
Fixes #493 . I'm convinced this was caused by some change in scipy.
=> Fix scipy instantiation of diagonal matrices

MANIFEST.in
Makes sure that the `COPYING` file is included in `setup.py sdist` files.
=> include COPYING in source distributions

.gitignore, cvxpy/atoms/elementwise/entr.py
Looks like the entropy atom returns infinity with scalars independently from them being or not in the domain. I made a small fix.
Problem was raised [here](https://stackoverflow.com/questions/50991294/infinity-objective-value-given-by-cvxpy-on-a-convex-program).
=> Fix entropy atom with scalars

cvxpy/reductions/solvers/conic_solvers/mosek_conif.py, cvxpy/tests/test_mip_vars.py
A fix for the Mosek interface. It corrects two situations when solving a problem with integer variables in Mosek resulted in ``SolverError``:
1. When the problem is infeasible - now returns ``s.INFEASIBLE``.
2. When an integer solution was found, but is not optimal - now returns ``s.OPTIMAL_INACCURATE``. I'm not sure this is the best status here, but I don't see a better one. It seems consistent with #480. This happens for example when a time limit was set for the solver.
=> Fix MIP solution statuses in Mosek

cvxpy/reductions/solvers/conic_solvers/cplex_conif.py
This was accidentally introduced with the addition of cplex_conif.py
(a new file from pull request #506).
=> Replace license with Apache 2.0 in cplex_conif.py

.travis.yml, setup.py
This is not still enough, since `scs` and `ecos` have the same problem. Also used `find_packages` instead of listing all the packages manually.
=> lazy import numpy for header injection

cvxpy/expressions/leaf.py
I passed in a 102x102 PSD Parameter whose smallest eigenvalue was 1e-4, but the numerical error caused by the reconstruction in `project` made it think the matrix wasn't PSD. This changes `project` to just return the (symmetrized) array if it doesn't actually need to change.
Also be a little more efficient by dividiing by 2 inplace, and using broadcasting instead of constructing a diagonal matrix and calling `dot` with it.
=> more efficient project() for PSD/NSD

cvxpy/reductions/solvers/conic_solvers/mosek_conif.py, doc/source/tutorial/advanced/index.rst
This adds an optional filename where MOSEK will dump the task data, for example
```
prob.solve(solver=MOSEK, save_file="dump.opf")
```
It is useful if the users can dump the problem for debugging esp. if the optimizer failed or crashed. Occasionally can be used for checking how cvxpy transformed the problem.
Online docs updated accordingly.
Tested in python 2.7 and 3.5.
=> Option to dump task file from MOSEK

cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
This should speedup the Gurobi interface by using numpy indexing instead of list comprehensions.
Related to #617
=> Removed list comprehensions in Gurobi QP interface

cvxpy/atoms/elementwise/abs.py
Hi,
I noticed that the absolute value atom has a few mistakes especially if the shape of the argument is (). This turns up in cases such as defining x = cvx.Variable(), setting y = cvx.abs(x), and querying for y.grad.
I've fixed this issue by setting row and col to 1 if either the inner or outer shapes are ().
=> Fixed subgradient calculation for absolute values

cvxpy/atoms/affine/unary_operators.py
The bug reported in issue #608 is just an issue with printing unary operators. This fix puts parens around unary operator arguments.
=> fix for issue #608

cvxpy/atoms/affine/diag.py, cvxpy/atoms/cummax.py, cvxpy/atoms/elementwise/abs.py, cvxpy/atoms/elementwise/maximum.py, cvxpy/atoms/log_det.py, cvxpy/atoms/matrix_frac.py, cvxpy/atoms/max.py, cvxpy/atoms/pnorm.py, cvxpy/cvxcore/python/canonInterface.py, cvxpy/tests/test_interfaces.py
This addresses #567 and is an expanded version of #637.
I introduced no changes in tests or examples, but otherwise I think that I got most cases where `np.matrix` is used. The test suite passes locally, but this clearly offers no guarantee, as I can already see that I have a few places where more fixing is required.
=> RF: Change np.matrix to np.array in several places.

cvxpy/atoms/__init__.py
The `diff_pos` atom is not exposed, but should be.
=> Expose `diff_pos`

cvxpy/atoms/affine/affine_atom.py, cvxpy/atoms/affine/cumsum.py, cvxpy/constraints/utilities.py, cvxpy/expressions/variable.py, cvxpy/reductions/solvers/conic_solvers/conic_solver.py
It's better to directly create a CSC matrix, than to create a COO only to convert it to a CSC after.
=> Avoid useless COO -> CSC sparse matrix convertions

cvxpy/atoms/elementwise/minimum.py, cvxpy/atoms/min.py, cvxpy/atoms/quad_form.py, cvxpy/interface/numpy_interface/ndarray_interface.py, cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py, cvxpy/tests/test_atoms.py, cvxpy/tests/test_constant_atoms.py, cvxpy/tests/test_constraints.py, cvxpy/tests/test_convolution.py, cvxpy/tests/test_dgp2dcp.py, cvxpy/tests/test_domain.py, cvxpy/tests/test_examples.py, cvxpy/tests/test_expressions.py, cvxpy/tests/test_grad.py, cvxpy/tests/test_interfaces.py, cvxpy/tests/test_linear_cone.py, cvxpy/tests/test_matrices.py, cvxpy/tests/test_mip_vars.py, cvxpy/tests/test_problem.py, cvxpy/tests/test_qp.py, cvxpy/tests/test_quadratic.py, cvxpy/tests/test_scs.py, cvxpy/tests/test_semidefinite_vars.py, cvxpy/tests/test_solvers.py, cvxpy/tests/test_super_scs.py
Trying to fix as many `DeprecationWarning` as possible.
The bulk of this PR is the deprecation of `numpy.matrix` (#567, #638).
There are also some assertion methods which need to be replaced.
=> Replace deprecated functions calls

cvxpy/atoms/atom.py, cvxpy/problems/problem.py, cvxpy/problems/xpress_problem.py, cvxpy/utilities/canonical.py, cvxpy/utilities/deterministic.py
I have been trying to make CVXPY behavior deterministic. I know that for Python 3.6+ the insertion order in dictionaries should be preserved. However, operations like `set` [do not preserve ordering](https://stackoverflow.com/a/54545521/9753175). I replaced the operations to compute the unique elements in a list with something that should preserve the ordering.
With the changes I propose here, I can get a deterministic behavior with MOSEK but not with GUROBI. You can try the mwe in https://github.com/cvxgrp/cvxpy/issues/624#issuecomment-479962141. I guess it is related to the QP canonicalization but I am not really sure.
Any idea why? It would be great to have this problem solved at least for Python 3.6+.
Fixes https://github.com/cvxgrp/cvxpy/issues/624
=> Make cvxpy deterministic

doc/source/tutorial/advanced/index.rst
Fixes a syntax error in the OSQP solver's argument list
=> OSQP takes max_iter instead of max_iters as an argument

cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py
Missing status code for "LP relaxation is dual infeasible" from CVXOPT: https://github.com/cvxopt/cvxopt/blob/master/src/C/glpk.c#L462
=> Missing status code in cvxopt STATUS_MAP

cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py
In `cplex_qpif.py`, we should check that `inverse_data.is_mip` is `False`
before calling `get_num_barrier_iterations()`.
=> Fix issue #747

cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
We can avoid the `tocoo()` conversion on the quadratic part in the Gurobi path if there are no quadratic terms. Avoids an unnecessary allocation of a potentially big matrix of zeros.
=> Minor optimization for Gurobi

doc/source/tutorial/advanced/index.rst
Previously, "probdata" variable was constructed
but not passed to SCS. Instead, "data" was passed,
which contained more elements than required.
Now get_problem_data result is renamed to "probdata",
and "data" is constructed, so scs.solve(data, cones)
actually uses constructed dictionary.
=> tutorial/advanced: use both "data" and "probdata" variables

continuous_integration/Travis/install_dependencies.sh, continuous_integration/Travis/test_script.sh, continuous_integration/osqp_version.py, cvxpy/cvxcore/python/cvxcore.py
this avoids the warning that `imp` has been deprecated in Python 3.4
=> Copy swig import helper from branch 1.1

doc/source/tutorial/functions/index.rst
At https://www.cvxpy.org/tutorial/functions/index.html#operators, there is an extra `are`.
=> Remove extra verb from the operators subsection at the atomic functions section

cvxpy/cvxcore/python/cvxcore.i
This should be the correct license paragraph as it is taken from the corresponding [cvxcore init file](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/cvxcore/python/__init__.py)
=> Fix license in cvxcore.i (#834)

continuous_integration/AppVeyor/configure_conda_and_install_cvxpy.ps1
Installing SCS from conda-forge instead of from pip seems to fix the appveyor build.
https://ci.appveyor.com/project/StevenDiamond/cvxpy/builds/28230656
Related: #788
=> install scs from conda-forge

cvxpy/__init__.py, cvxpy/cvxcore/python/canonInterface.py, cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py, cvxpy/reductions/solvers/conic_solvers/diffcp_conif.py, cvxpy/reductions/solvers/conic_solvers/scs_conif.py, cvxpy/tests/test_derivative.py
When differentiating, keep zero entries in problem data that are affected by parameters
=> Keep zeros

cvxpy/__init__.py, cvxpy/atoms/suppfunc.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/__init__.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/suppfunc_canon.py, cvxpy/reductions/solvers/conic_solvers/mosek_conif.py, cvxpy/reductions/solvers/conic_solvers/scs_conif.py, cvxpy/tests/test_mosek_conif.py, cvxpy/tests/test_suppfunc.py, cvxpy/transforms/__init__.py, cvxpy/transforms/suppfunc.py, cvxpy/utilities/coeff_extractor.py
This PR focuses on the content of my accidental merge from earlier today. It also contains fixes to the MOSEK interface.
Users can get a handle on a ``SuppFunc`` object by calling ``sigma = cvxpy.suppfunc(x, constrs)``. From there, ``SuppFuncAtom`` objects are generated by evaluating the ``SuppFunc`` object. So a user could write ``sigma(y) <= 1``, and this generates a ``SuppFuncAtom`` object and a cvxpy inequality constraint in the same line of code.
It may seem odd to have two separate classes for this feature. This is necessary because cvxpy doesn't consider convex sets as first-class objects. After quite a bit of thinking, I think the best way to represent a convex set in cvxpy is with a pair ``(expr, constrs)``, where this pair stands in for ``S = {val : constraints in constrs can be …
=> support functions (transform, and atom)

cvxpy/reductions/solvers/conic_solvers/diffcp_conif.py, cvxpy/tests/test_scs.py
This PR allows to warm-start SCS in diffcp. Note that the `warm_start` option in diffcp now conflicts with the standard cvxpy `warm_start` option which is True/False.
Also, it would be good to check the type of the `warm_start` entry in diffcp to avoid errors:
https://github.com/cvxgrp/diffcp/blob/2e0d3f7337e19509bd312272ed59be1f93104ff2/diffcp/cone_program.py#L248-L251
=> Allow warm-start in diffcp

cvxpy/atoms/affine/upper_tri.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/lambda_max_canon.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/log_det_canon.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/matrix_frac_canon.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/normNuc_canon.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/sigma_max_canon.py, cvxpy/tests/test_atoms.py, cvxpy/tests/test_complex.py
This PR addresses the issues mentioned in #877. Fewer variables and fewer equality constraints are introduced in the compilation process. The bmat atom is used more often.
The only questionable part of this PR is the introduction of a ``vec_to_upper_tri`` function in ``upper_tri.py``. If you want me to make this function an actual *atom*, or to write documentation for it, let me know. Tests for this function have been added to ``test_atoms.py``.
I did not write additional tests for any of the existing atoms (``normNuc``, ``lambda_max``, ``sigma_max``, ``matrix_frac``).
=> improve SDP-atom canonicalization efficiency (#877)

cvxpy/transforms/scalarize.py
when i used cp.max i encountered a bug so i tried to fix it by just using atoms.maximum instead of atoms.max_elemwise
=> Updated max transform function in scalarize function

cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py
Passing `QCPDual=False` to Problem.solve(solver="GUROBI") instructs gurobi not to calculate the dual values, but cvxpy will still try to extract they from the solution leading to a KeyError. At least with my models, they don't actually seem to be used at all, and just skipping their extraction here appears to work fine. This can save a couple minutes of compute.
=> Don't get extract dual from gurobi if it's not available

cvxpy/expressions/expression.py, cvxpy/tests/test_dgp.py
Modify __add__ such that expr + 0 returns expr (similarly for 0 + expr);
this makes it possible to use Python's builtin sum when constructing LLCPs.
Fixes #883
=> Drop zero arguments in addition

cvxpy/atoms/atom.py, cvxpy/reductions/dqcp2dcp/dqcp2dcp.py, cvxpy/tests/test_dqcp.py
Fixes a bug in DQCP analysis in analyzing monotone real functions; DQCP
analysis previously did not check whether the argument of a scalar function
was also scalar. This bug caused DQCP analysis to be too permissive, incorrectly
labeling things as DQCP and causing the reduction to fail in surprising ways.
As an extension, this change adds the vector atoms cp.max and cp.min to the
DQCP atom library, letting users take the max or min of quasiconvex or
quasiconcave expressions. Previously, only the elementwise cp.maximum and
cp.minimum atoms were allowed.
Fixes #904
=> DQCP: Fix detection of monotone real functions

cvxpy/expressions/constants/constant.py, cvxpy/tests/test_quad_form.py
Follow up from https://github.com/cvxgrp/cvxpy/issues/929#issuecomment-579972424
For eigenvalues with very small magnitude, scipy recommends using shift-invert mode to solve an equivalent eigenvalue problem with large magnitude eigenvalues: https://docs.scipy.org/doc/scipy/reference/tutorial/arpack.html#shift-invert-mode.
The motivation for this pull request is that I had run into PSD matrices in quadratic forms that had eigenvalues that were (according to eigsh) ~-5e-9, just outside the tolerance. Enabling shift-invert mode fixed the issue.
=> Enable shift-invert mode for finding small eigenvalues

cvxpy/atoms/lambda_max.py, cvxpy/atoms/lambda_sum_largest.py, cvxpy/atoms/log_det.py
Hi, I added symmetry checks for the arguments of some matrix atoms which require symmetric input (like @rileyjmurray suggested in issue #932).
=> Symmetry checks for matrix atoms

cvxpy/constraints/exponential.py, cvxpy/constraints/second_order.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/kl_div_canon.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_linear_cone.py
General issues resolved:
* #936, by adding some dedicated tests for SOC constraints with the axis option. 
* While implementing the above tests it became clear that SOC with axis=0 was not recovering dual variables properly. This is now fixed for most solvers (I'll elaborate on this below).
* A standing TODO for ExpCone tests and vectorization.
* SOC and ExpCone input casting to cvxpy Expressions.
* A compilation inefficiency in ``kl_div_canon``. 
Details on SOC changes
------------------------
This PR modifies a test called ``socp_2`` and introduces a test called ``socp_3``.
* The modification to ``socp_2`` was to use ``SOC(expr2, expr1)`` in lieu of ``cp.norm(expr1) <= expr2``. The effect is that ``socp_2`` now meaningfully tests for conic dual variables, while before it did not.
* The …
=> ExpCone and SOC testing. Bugfix for SOC axis settings.

cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py, cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
This PR has some tweaks for dual value computation (#948), a workaround for a bug in gurobipy 8.1.1, and better verbosity control (both #900).  nosetests ran through clean on my machine.
=> Minor polish

cvxpy/atoms/__init__.py
Previously, transpose was only exported via the `T` method on the Expression class. This exposes the `transpose` atom under the `cvxpy` namespace. (So a user can write `cp.transpose(expr)` if they want to.)
Fixes #964
=> Expose the transpose atom

cvxpy/reductions/solvers/conic_solvers/cplex_conif.py
If the supporting linear equality constraint was empty, we were
setting the RHS to 0, but we should have been using the RHS given in
vec[i].
With this change, the test_cplex_socp_2 and test_cplex_socp_3 tests
should now pass. This is for #920.
=> Fix bug with RHS values in cplex_conif.py:add_model_soc_constr

cvxpy/reductions/dgp2dcp/atom_canonicalizers/quad_over_lin_canon.py, cvxpy/tests/test_dgp2dcp.py
The quad_over_lin canon was previously missing a transformation. Because
the sum_squares atom is implemented using quad_over_lin, this lead to
errors when the sum_squares atom was used in a DGP program.
Issue #982 surfaced this problem.
=> [DGP] Fix quad_over_lin canon

cvxpy/atoms/atom.py, cvxpy/problems/param_prob.py, cvxpy/problems/problem.py, cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py, cvxpy/reductions/dqcp2dcp/dqcp2dcp.py, cvxpy/reductions/inverse_data.py, cvxpy/reductions/qp2quad_form/qp_matrix_stuffing.py, cvxpy/reductions/solvers/conic_solvers/cplex_conif.py, cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py, cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py, cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py, cvxpy/reductions/solvers/qp_solvers/qp_solver.py, cvxpy/reductions/solvers/solver.py, cvxpy/reductions/solvers/solving_chain.py, cvxpy/tests/test_conic_solvers.py, cvxpy/utilities/coeff_extractor.py
Work in progress to add parametric QPs.
Things needed:
I think the easiest way to define quad forms in DPP is to keep them as `sum_squares(S @ x)` where `S` is a matrix in `R`. This might make the first step way easier.
=> [WIP] Add ParamQuadProg

cvxpy/reductions/solvers/solving_chain.py, cvxpy/tests/test_dgp2dcp.py
Evaluate parameters when solving log-log convex programs. DGP requires a
specialized DPP ruleset to ensure the corresponding DCP program is
DCP. We haven't worked that ruleset out yet, so for now always evaluate the
parameters.
=> [DGP] Always eval params

cvxpy/reductions/dgp2dcp/atom_canonicalizers/parameter_canon.py, cvxpy/tests/test_dgp2dcp.py
Parameters in a DGP problem are converted into new parameters in a DCP
problem, via Dgp2Dcp. Before this change, the names of the original parameters
were not properly propagated to the new parameters, leading to an error when
the DCP problem was printed. Users don't interact with the output of
Dgp2Dcp directly, but this bug showed up during internal testing.
Note that the code path in parameter_canon.py is not currently exercised by problem.solve(), since we evaluate parameters for DGP problems as of ed5dd6a355f3c4dae3de385f25b9925a878b9ac2. However, I'd like to eventually (maybe soon) support DPP for DGP problems, so I'm keeping this code around instead of deleting it.
Riley or Steven, a review from just one of you should be fine. It's a very small change.
=> [DGP] Propagate Parameter names in Dgp2Dcp

cvxpy/atoms/affine/binary_operators.py, cvxpy/atoms/one_minus_pos.py, cvxpy/reductions/dgp2dcp/atom_canonicalizers/eye_minus_inv_canon.py, cvxpy/tests/test_dgp2dcp.py
The canonicalization of eye_minus_inv was previously incorrect. This was
discovered during internal testing. A test is added to ensure that
checks for correctness of the canonicalization.
=> [DGP] Fix canonicalization of eye_minus_inv atom

cvxpy/cvxcore/src/ProblemData.hpp, cvxpy/reductions/solvers/conic_solvers/conic_solver.py, cvxpy/tests/ram_limited.py, cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_curvature.py
@SteveDiamond following our slack thread, here's a PR containing a test to cause a cvxcore overflow error. I created a new file within ``cvxpy/tests`` which won't be discovered by automatic testing suites. The intention is that we execute that file with command line arguments only when necessary. The current file contains a test which takes about 100GB RAM; the overflow happens in Eigen. To see what's going on in Eigen you're going to need to execute the python test script within GDB, and make sure cvxcore was built without GCC compiler optimizations (change line 50 of setup.py to use flag ``"-O0"``).
[One of these commits](https://github.com/cvxgrp/cvxpy/commit/2698c33f2641a53e75c8cc274d1c416a777ae665) modified ``cvxpy/cvxcore/src/ProblemData.hpp``. Our normal test suite passed after …
=> a test for cvxcore overflows (and other minor changes)

cvxpy/problems/problem.py, cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py, cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py, cvxpy/reductions/solvers/qp_solvers/qp_solver.py, cvxpy/settings.py, cvxpy/tests/test_param_quad_prog.py
I have made a few fixes for the QP solvers.
These are quite standard:
- The `apply` function in the `QpSolver` class was rewriting the `data` dict and, therefore, deleting the `ParamQuadProg` element inside. This means that CVXPY was reparsing QPs all the times, also with parametric programs.
- I have deleted the `apply` function in `osqp_qpif.py` so that it uses the one defined in `QpSolver`
I would like to ask **your feedback** on this:
- Gurobi can return the solution if it hits the maximum time `TimeLimit`. I have assigned this case to the status `s.USER_LIMIT`. This situation happens when solving long mixed-integer programs: the solver has a feasible solution but it hasn't proven its optimality yet. At the moment, CVXPY just discards that solution and throws an error. With this PR …
=> QP Solvers Fixes

doc/source/examples/applications/ant_array_min_beamwidth.rst, doc/source/examples/applications/clock_mesh.rst, doc/source/examples/applications/consensus_opt.rst, doc/source/examples/applications/fault_detection.rst, doc/source/examples/applications/fir_chebychev_design.rst, doc/source/examples/applications/l1_trend_filter.rst, doc/source/examples/applications/max_entropy.rst, doc/source/examples/applications/nba_ranking.rst, doc/source/examples/applications/nonneg_matrix_fact.rst, doc/source/examples/applications/robust_kalman.rst, doc/source/examples/applications/sparse_solution.rst, doc/source/examples/derivatives/structured_prediction.rst, doc/source/examples/dgp/power_control.rst
Hello! First and foremost: thank you for the great library.
Some equations seem to not display correctly in the examples, see [this page](https://www.cvxpy.org/examples/applications/robust_kalman.html) for an example
Here's what it looks like in Firefox:
Changing the lines to `.. math::` seems to do the trick:
I also have a question. I see that the files below are identical:
```
./examples/notebooks/WWW/robust_kalman.ipynb
./doc/source/examples/applications/robust_kalman.rst
```
**Question.** Is the `.rst` the result of a manual export from the notebook, or is it automated? If it's not automated, I think it would be better to have the code in one place and automate this.
=> Change raw latex to math so equations display correctly

cvxpy/reductions/solvers/solving_chain.py, cvxpy/tests/test_dpp.py
Canonicalizing (eg Dcp2Cone) non-DPP problems with params led to incorrect behavior
Fixes #1044
=> Eval params early

cvxpy/problems/problem.py, cvxpy/reductions/solvers/conic_solvers/ecos_conif.py, cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py, cvxpy/reductions/solvers/conic_solvers/scs_conif.py, cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py, cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py, cvxpy/settings.py, cvxpy/tests/test_problem.py
We currently cache the OSQP/SCS results dicts in problem._solver_cache. This
is useful when debugging a call to solve. This
change also caches the ECOS results dict and the entire Gurobi model;
this makes it possible to inspect the solver's performance
programmatically, without looking at the verbose output.
We should implement similar changes for all solvers, in a future change. It might be
a good idea to expose cached solver information in a public API in a
future PR.
=> Cache auxiliary output for some solvers

cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py, cvxpy/tests/test_conic_solvers.py
The conic interface to Gurobi processes the linear constraints through a DOK sparse matrix, which can easily induce a big overhead.   Consider the following example:
```
import numpy as np                                                              
import scipy as sp                                                              
import cvxpy as cp                                                              
import time                                                                     
m = 500                                                                         
n = 5000                                                                        
b = np.random.rand(m)                                                           
for d in np.linspace(0.1, 0.8, 3): …
```
=> Remove Gurobi conic interface bottleneck

cvxpy/cvxcore/python/canonInterface.py, cvxpy/reductions/solvers/conic_solvers/conic_solver.py, cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
The larger optimization problems using the conic solver were being rejected due to a negative dimension. This arose from the int32 datatype being used. I changed a couple int32 data types to int64 data types so the overflows wouldn't occur. This completely fixed the problems and the solvers seem to be running without any other changes. This fix can definitely be implemented individually in other solvers but I will look through the code in the future to try and cast all int32 types to int64 types to avoid this problem.
=> Big data bug fixes

cvxpy/expressions/constants/constant.py, cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py, cvxpy/reductions/solvers/kktsolver.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_expressions.py, doc/source/faq/index.rst, doc/source/tutorial/advanced/index.rst
CVXOPT lets users pass a function handle which implements an algorithm to solve linearized KKT systems. This PR exposes that functionality to CVXPY users, and resolves #1042.
Under this PR, a user can now select a KKT solver by specifying one of six strings, or a custom function handle.
* The strings correspond to five cvxopt built-in solvers, and the "robust" solver which is part of the cvxpy source code.
* Users are directed to a specific part of cvxpy source code to determine how to implement a KKT solver of their own.
This functionality is only really relevant when a user is confident that a given cvxpy formulation leads to a suitably structured cone program. So from a practical perspective, I wouldn't recommend using this feature with nonlinear cvxpy atoms. If someone wants to take …
=> Add support for custom kkt solvers in cvxopt interface

cvxpy/atoms/__init__.py, cvxpy/atoms/geo_mean.py, cvxpy/atoms/inv_prod.py, doc/source/api_reference/cvxpy.atoms.other_atoms.rst, doc/source/tutorial/functions/index.rst
Adding in the (somewhat surprising!) new atom `inv_prod` equal to
```
(Π x)⁻¹
```
for some vector `x`, as per @akshayka 's recommendation.
=> Adding reciprocal product as a new convex atom

cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_cone2cone.py
The unit tests previously had ``@skipunless`` decorators, which checked if an MI-SOCP solver is installed. Now that ECOS_BB is back, that list had to be explicitly updated to exclude ECOS_BB from a test where it gave an incorrect (suboptimal) solution. 
Excluding ECOS_BB does not indicate the cone2cone reduction is broken, since the test passes when other MI-SOCP solvers are installed.
My plan is to merge this PR once CI tests pass.
=> Change cone2cone unittest to reflect ECOS_BB change

doc/source/tutorial/dqcp/index.rst
Just a simple addition of `is` to make the sentence more understandable
> An expression `is` quasiconcave under DQCP if it is one of the following
this PR addresses this issue https://github.com/cvxgrp/cvxpy/issues/1083
=> addressing doc typo issue: dqcp typos #1083

cvxpy/reductions/qp2quad_form/atom_canonicalizers/power_canon.py
Replace a dense identity with a sparse one in `power_canon` for QPs.
=> replace np.eye with sp.eye in qp2quadform

setup.py
I tried to do a clean build from src of cvxpy in a fresh Python 3.9 virtual environment using pyenv on Windows/WSL2+Debian 10.4.
I was receiving the following error (gcc/g++ = 8.3.0):
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Icvxpy/cvxcore/src/ -Icvxpy/cvxcore/python/ -Icvxpy/cvxcore/include/Eigen -I/home/jason/.pyenv/versions/3.9.0/envs/cvxpy_contrib/include -I/home/jason/.pyenv/versions/3.9.0/include/python3.9 -I/tmp/pip-build-env-ndldwnnq/overlay/lib/python3.9/site-packages/numpy/core/include -c cvxpy/cvxcore/python/cvxcore_wrap.cpp -o build/temp.linux-x86_64-3.9/cvxpy/cvxcore/python/cvxcore_wrap.o -O3
In file included from /usr/include/c++/8/tuple:39,
from /usr/include/c++/8/functional:54,
from cvxpy/cvxcore/src/../include/Eigen/Core:153, …
```
=> remove Eigen from include path

cvxpy/reductions/solvers/conic_solvers/diffcp_conif.py
Forces `diffcp` to use `SCS`, since the `diffcp` conic interface already assumes this.
=> force SCS in diffcp

cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py
It exports Variable's `.name` property as variable name to Cplex. It is useful when debugging an infeasibility as Cplex will actually print the variable name. It gets even more useful when combined with the conflict refiner (PR #1168). 
This has two main limitations at the moment:
1. Cvxpy actually creates lots of variables under the hood, sometimes just copying ones created by the user. This often does not preserve the user-specified names. I'll try to address parts of this issue with future PRs.
2. It only works for variables and not for constraints. They are more complex to tackle. That is a story for another time I guess.
=> Cplex variable names

.travis.yml, CONTRIBUTING.md, appveyor.yml, conda-recipe/meta.yaml, continuous_integration/AppVeyor/configure_conda_and_install_cvxpy.ps1, continuous_integration/Travis/install_dependencies.sh, continuous_integration/Travis/test_script.sh, continuous_integration/appveyor_install.ps1, cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_constant_atoms.py, cvxpy/tests/test_quad_form.py, doc/source/contributing/index.rst, doc/source/install/index.rst, examples/advanced/numpy_test.py
This PR closes #1157 . It replaces nose with pytest, more specifically:
- CI/CD scripts and documentation have been changed.
- I changed the order of `flake8` and the tests. The rationale is that flake8 should go first since it's faster, causing the build to fail fast if there is an error with syntax.
- There are some differences in `cvxpy/tests/test_constant_atoms.py`, but the git diff is mostly syntax. The only real change is that I use the `pytest.mark.parametrize` decorator on the `test_constant_atoms` function.
=> Replace nose with pytest

cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py
numpy arrays need to have conforming shapes before checking for
elementwise equality
=> Check shape before checking equality in osqp interface

cvxpy/problems/problem.py, cvxpy/reductions/solvers/solving_chain.py, cvxpy/tests/test_custom_solver.py, doc/source/tutorial/advanced/index.rst
Allows the use of custom solvers in `cvxpy`. This can be helpful when prototyping new solvers, writing official solvers for `cvxpy`, or developing custom solvers tailored to a specific application. 
To use a custom solver, one has to implement a solver class that is a child of `QpSolver` or `ConicSolver`. Then an instance of this new solver class is passed to `problem.solve(solver=.)`. Note that conflicts with existing solvers are avoided because custom solvers are specified by passing objects that are instances of the `Solver` class, while standard solvers are specified via strings (e.g. "OSQP"). Furthermore, when a user specifies a custom solver, then no standard solvers are suggested as "candidates" via `cvxpy`. That was done on purpose for simplicity.
```python
from …
```
=> Allow for custom solvers

doc/source/tutorial/advanced/index.rst, doc/source/updates/index.rst
This might also help somebody who is using 1.1.0 <= CVXPY < 1.1.6 and is
wondering why ECOS_BB is not installed.
=> Add hint to docs about changes to ECOS_BB

cvxpy/expressions/leaf.py
I was trying to get the domain of an expression and was surprised that it always returned an empty array. After some investigation I found out that the domain property function in `leaf.py` always returns an empty array instead of the calculated domain (see changed line). To me this looks like a clear mistake/bug. I'm just a bit worried that no one noticed this since the part of the codebase is already over 3 years old.
Also, it seems like this isn't the only mistake in regard to returning the correct domain. For example, this is now correct after the change:
``` python
X = cp.Variable((3, 3), PSD=True)
constraints = []
objective = cp.Minimize(cp.norm(X, 2))
prob = cp.Problem(objective, constraints)
all_domains = objective.args[0].domain  # domain of the objective …
```
=> Return correct domain

cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_conic_solvers.py
This fixes #1191, which occurs because there is no status code 'infeasible' in CVXOPT/GLPK.  
The test case added is an MIP that is infeasible but integer relaxable and triggers the status 'infeasible problem' in GLPK. 
I particularly want to stress, that I did only add this test for solver='GLPK_MI', since I don't have other solvers installed and the test might be an edge case where some solvers are failing. Still, it would be interesting to see what other solvers have to say about this test, which is interesting in itself.
=> 1191 fix cvxopt status

cvxpy/tests/test_problem.py
Fixing pypy failure uncovered in https://github.com/conda-forge/cvxpy-feedstock/pull/46
=> do not use builtins as a dict

cvxpy/reductions/cone2cone/affine2direct.py, doc/source/updates/index.rst
This resolves #1226, and will be included in the release of CVXPY 1.1.8. The web documentation source files have been updated to make note of this fix.
=> Bugfix for affine2direct: SolverErrors weren't being raised

cvxpy/problems/problem.py
The corresponding issue for this PR can be found here: #1232 
While the change is only one line, I followed the contributing guidelines:
A UT which checks exactly this scenario is likely not relevant for most users and indeed would be quite tricky to include.
=> Allow single MI solver != ECOS_BB [issue 1232]

cvxpy/cvxcore/python/canonInterface.py
In issue #1160, @akshayka and @rileyjmurray were disucssing ways to speed up `reduce_problem_data_tensor()`.
Using [line_profiler](https://github.com/pyutils/line_profiler) I have profiled the optimization problem stated in the issue, narrowing down the lines consuming most of the CPU time:
```
Total time: 124.153 s
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
111         2         17.0      8.5      0.0      old_row_to_new_row = {
112         2    5266879.0 2633439.5      4.2          unique_old_row[i]: i for i in range(unique_old_row.size)
113                                               }                                        
...
119  10043002   21723051.0      2.2     17.5      for i in …
```
=> Performance improvement for reducing problem data tensor [issue 1160]

cvxpy/error.py, cvxpy/expressions/expression.py, cvxpy/tests/test_expressions.py, doc/source/updates/index.rst
This addresses #1238 and is intended to supersede #1239. It removes side-effects of our existing warnings for accessing matmul through ``*`` and introduces a new ``MatmulWarning`` class for that purpose.
This PR also updates the web doc source to mention the importance of cvxpy 1.1.10 for the numpy installation issue.
=> Matmul warning

cvxpy/atoms/affine/diag.py, cvxpy/tests/test_atoms.py
This PR adds @SteveDiamond 's proposed improvement for the `is_nonneg()` check in the `diag_mat` class, as per discussion in #1213. Also, the tests are extended to cover this case.
=> Extend is_nonneg() of diag_mat to check if arg is psd [issue 1213]

cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
Quick fix #1194 . 
It looks like Gurobi does not create the attributes BarIterCount and IterCount when the problem is large.
=> Use try/except to get Gurobi iterations 

cvxpy/atoms/quad_form.py, cvxpy/tests/test_grad.py
This resolves 1260 by calling ``np.conj(P).T`` instead of ``P.H``, which only works for numpy matrices. I added a test based on issue 1260 as well.
=> Fix issue 1260

cvxpy/atoms/affine/reshape.py, cvxpy/tests/test_atoms.py
This change fixes a bug in the canonicalization of C-style reshape.
Previously a transpose was omitted when reshaping matrices.
This change also removes a stray `print` statement.
See the change for an example of a `reshape` that previously did not work.
=> Fix bug in C-style reshape

cvxpy/reductions/solution.py, cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py, cvxpy/tests/test_conic_solvers.py
A fix for #1177, following our discussion.
Here is a brief summary.
Sometimes Gurobi hits the time limit before finding a solution or proving that the problem is infeasible or unbounded. Currently cvxpy raises an unexpected exception in this case, as it tries to unpack a solution.
1. that cvxpy stops raising an unexpected exception,
2. to be able to identify this case so that the user could retry with a higher time limit.
1. map this case to `INFEASIBLE_INACCURATE` status (and not to `USER_LIMIT`, as it is in `SOLUTION_PRESENT` list, and then tries to unpack a solution at each given opportunity resulting in another unexpected exception),
2. pass `attr` with details from the solver to `failure_solution`.
1. cvxpy returns successfully with status `INFEASIBLE_INACCURATE`,
2. the solver …
=> Gurobi: fix for when time limit is hit with no solution

cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
Added gurobi warm start using the `Start` attribute (see [docs](https://www.gurobi.com/documentation/9.1/refman/start.html)).  
It's related to https://github.com/cvxgrp/cvxpy/issues/849 This PR makes Gurobi store the model in cache and it uses it to retrieve the previous solution.
This is an example for a random MIQP. We reuse the previous solution on the exact same problem, but it can be applied to more complicated cases.
```python
np.random.seed(0)
m, n = 80, 30
A = np.random.rand(m, n)
b = np.random.randn(m)
print("Solve\n---")
x = cp.Variable(n, integer=True)
objective = cp.Minimize(cp.sum_squares(A @ x - b))
prob = cp.Problem(objective)
prob.solve(solver=cp.GUROBI, verbose=True)
print("\n\nSolve again\n---")
prob.solve(solver=cp.GUROBI, …
```
=> Gurobi warm start

cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py, cvxpy/tests/test_qp_solvers.py
Similar to my recent fix in #1270 for [gurobi_conif.py](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py), we have encountered the same issue in [gurobi_qupif.py](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py) this time. It is also documented in issue #1176. This PR should fix it.
The changes are **identical** to the one in #1270 **up to the following differences**:
1. the scope of the changes is [gurobi_qupif.py](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py) instead of [gurobi_conif.py](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py),
2. there was no need to explicitly pass `attr` with …
=> Gurobi: fix for when time limit is hit with no solution (QP case)

cvxpy/problems/problem.py, cvxpy/tests/test_problem.py
As described in issue #1280 and discussed with @SteveDiamond, this commit allows CVXPY to properly handle expressions that are just `bool` values (`True` or `False`). This happens at the level of the `Problem()` constructor, replacing these values with equivalent valid expressions (which are respectively either always True or False).
The commit replaces a stub unit test with an actual passing unit tests.  
Flake8 passes without event.
Pre-change benchmarks:
```
========================================================================================================= test session starts =========================================================================================================
platform win32 -- Python 3.7.4, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: …
```
=> Implement handling of `bool` valued constraints

cvxpy/atoms/affine/add_expr.py, cvxpy/atoms/elementwise/power.py, cvxpy/atoms/geo_mean.py, cvxpy/expressions/leaf.py, cvxpy/reductions/chain.py, cvxpy/reductions/solvers/solving_chain.py, cvxpy/utilities/canonical.py
When `[]` or `{}` or any other mutable type is used as a default argument, this can have unexpected results as discussed [here](https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html) and [here](https://stackoverflow.com/questions/26320899/why-is-the-empty-dictionary-a-dangerous-default-value-in-python) for reasons explained [here](https://web.archive.org/web/20200221224620/http://effbot.org/zone/default-values.htm).
Rather than relying on programmer discipline not to abuse these default arguments, it is generally considered best practice to default value the arguments to `None` and check this within the function body.
This PR fixes all the instances I found, excluding the `doc/` subdir, which I assume consists largely of upstream code.
=> Switch to using safe default arguments

cvxpy/cvxcore/python/cvxcore.py, cvxpy/interface/base_matrix_interface.py, cvxpy/lin_ops/lin_op.py, cvxpy/lin_ops/lin_utils.py, cvxpy/problems/param_prob.py, cvxpy/problems/problem.py, cvxpy/reductions/cone2cone/affine2direct.py, cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py, cvxpy/reductions/inverse_data.py, cvxpy/reductions/qp2quad_form/qp_matrix_stuffing.py, cvxpy/reductions/reduction.py, cvxpy/reductions/solution.py, cvxpy/reductions/solvers/conic_solvers/conic_solver.py, cvxpy/tests/solver_test_helpers.py, cvxpy/transforms/suppfunc.py, cvxpy/utilities/canonical.py, cvxpy/utilities/coeff_extractor.py, doc/source/conf.py, doc/sphinxext/docscrape.py, doc/sphinxext/numpydoc.py, examples/advanced/circuits.py, examples/advanced/numpy_test.py, examples/advanced/optimal_control.py, examples/advanced/test.py, examples/floor_packing.py, examples/flows/max_flow.py
There are a number of instances where the code says:
```
class foo(object):
```
this PR switches them all to
```
class foo:
```
As explained [here](https://stackoverflow.com/questions/4015417/why-do-python-classes-inherit-object), the first form was necessary for Python 2, but is not needed in Python 3. Since CVXPY requires Python >=3.5, this pattern is no longer necessary.
=> Classes do not need to inherit from object in Python3

cvxpy/problems/problem.py, cvxpy/reductions/chain.py
For performance reasons it's usually best to avoid performing string interpolation for loggers. If the logger is not emitting messages, then the interpolation is not performed and time is saved. If the logger is emitting, the logger functions handle the interpolation.
=> Use lazy interpolation for logging

cvxpy/atoms/elementwise/ceil.py, cvxpy/atoms/lambda_sum_largest.py, cvxpy/atoms/log_det.py, cvxpy/atoms/norm_inf.py, cvxpy/problems/problem.py, cvxpy/settings.py, cvxpy/tests/test_atoms.py, cvxpy/tests/test_complex.py, cvxpy/tests/test_problem.py, cvxpy/transforms/partial_optimize.py
This PR sets prob.value to prob.objective.value when a solution is present. I had to fix a number of .value functions for individual atoms. The solutions I chose were not always the most elegant, so I'm open to improvements.
=> Set prob.value to prob.objective.value

cvxpy/reductions/solvers/conic_solvers/ecos_bb_conif.py, cvxpy/reductions/solvers/conic_solvers/ecos_conif.py, cvxpy/reductions/solvers/conic_solvers/scs_conif.py
Fixes #1322.
I have taken this opportunity to pass solver stats for ECOS and SCS as well when there is no solution (similar to [gurobi_conif.py](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py)).
=> Populate solver_stats for ECOS_BB, ECOS & SCS

cvxpy/cvxcore/src/cvxcore.cpp
Fixes
```
cvxpy/cvxcore/src/cvxcore.cpp: In function ‘ProblemData build_matrix(std::vector<const LinOp*>, int, std::map<int, int>, std::map<int, int>, int)’:
cvxpy/cvxcore/src/cvxcore.cpp:183:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::pair<const LinOp*, int> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
183 |   for (int i = 0; i < constraints_and_offsets.size(); ++i) {
|                   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Fix loop variable data type

cvxpy/expressions/constants/constant.py, cvxpy/tests/test_dgp.py
Sparse constants cannot be elementwise positive, since they generally have many entries which are zero. So in particular they shouldn't be used in DGP.
Without this change, the `is_pos` method fails with an error (a raised Python exception) on sparse constants.
In the future it might be possible to have an overloaded notion of sparsity for DGP, where the zero entries actually represent the value 1.
=> Disallow sparse constants in DGP

cvxpy/atoms/affine/vstack.py, cvxpy/tests/test_atoms.py
This fixes #1338 by solving the edge case when vstack is applied to a mix of elements with shape () and elements with shape (1,).
=> Fix edge case for vstack

cvxpy/cvxcore/src/LinOpOperations.cpp
Fixes
```
cvxpy/cvxcore/src/LinOpOperations.cpp: In function ‘Tensor get_rmul_mat(const LinOp&, int)’:
cvxpy/cvxcore/src/LinOpOperations.cpp:729:7: warning: variable ‘arg_cols’ set but not used [-Wunused-but-set-variable]
729 |   int arg_cols;
|       ^~~~~~~~
```
But you may want to just drop the `arg_cols` variable here.
=> Suppress warning about unused variable

cvxpy/atoms/elementwise/logistic.py
Connected to this question on Stack Overflow: https://stackoverflow.com/questions/67062485/overflow-while-using-logistic-function-in-cvxpy.
Current implementation of logistic atom overflows when one of the elements in the input vector exceeds ~710 due to np.exp invocation. Atom evaluation doesn't have this problem - it uses np.logaddexp to handle big values.
I've rewritten gradient implementation to utilize np.logaddexp call, which prevents overflow from happening. First we calculate the solution in the logarithmic scale, and only after we take an exponent of the resulting value.
=> Logistic atom - improved gradient calculation

pyproject.toml
the only version number that matters for ABI interface purposes is the first minor version number. Therefore, use flexible versions here to allow pip to select a newer version of numpy if it so wishes. This speeds up the install time on linux for python 3.9 because a pre-built numpy wheel for 1.19.0 does not exist at that python version, but 1.19.5 does exist.
=> use flexible numpy version in pyproject.toml

.github/workflows/build.yml, README.md, continuous_integration/GitHub/install_dependencies.sh, doc/source/install/index.rst, setup.py
@rileyjmurray @SteveDiamond as per discussion in #1375, this PR drops Python 3.5 support from the CI and updates the docs.
=> Remove Python 3.5 references

.github/workflows/build.yml
We do not build the wheels using openmp at the moment, thus the deployment fails for that config. 
This PR skips this step accordingly.
@SteveDiamond
=> Skip Deploy Step Openmp Build

cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py
I'm working on a model with > 10k SOC constraints. The model updates are adding 60s and there's a warning from Gurobi that says
```
Warning: excessive time spent in model updates.
```
In the for loop while adding SOC constraints, there's a Gurobi `model.update()` that's causing this.
Since you're not using the model to get anything between adding these constraints and then optimizing, there's no real reason to have it there at all.
=> remove model update within soc constraint for loop

.github/workflows/build.yml, continuous_integration/install_dependencies.sh, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_conic_solvers.py
This is the follow-up to #1413.
The following solvers are added to the CI:
Platform | XPRESS | CPLEX | CBC | SCIP
-- | -- | -- | -- | --
Linux 3.6 | yes | yes | yes | no
Linux 3.7 | yes | yes | yes | no
Linux 3.8 | yes | yes | yes | no
Linux 3.9 | yes | no | yes | yes
macOS 3.6 | yes | yes | yes | no
macOS 3.7 | yes | yes | yes | no
macOS 3.8 | yes | yes | yes | no
macOS 3.9 | yes | no | yes | yes
Windows 3.6 | yes | yes | no | yes
Windows 3.7 | yes | yes | yes | yes
Windows 3.8 | yes | yes | yes | yes
Windows 3.9 | yes | no | yes | yes
I have added a short description of the exclusion criteria to the code, such that one can easily see when those restrictions are lifted in the future.
=> More Solvers for CI

cvxpy/reductions/solvers/conic_solvers/scipy_conif.py, cvxpy/tests/test_conic_solvers.py
Adding dual variables when the SciPy solver is used with methods "highs", "highs-ds" or "highs-ipm" and the Scipy version is >= 1.7.0 . Linked to Issue #1425 .
=> Adding dual variables for SciPy LP solver interfaces #1425

cvxpy/tests/test_atoms.py, cvxpy/tests/test_complex.py, cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_constraints.py, cvxpy/tests/test_convolution.py, cvxpy/tests/test_derivative.py, cvxpy/tests/test_dgp2dcp.py, cvxpy/tests/test_domain.py, cvxpy/tests/test_dpp.py, cvxpy/tests/test_dqcp.py, cvxpy/tests/test_examples.py, cvxpy/tests/test_expressions.py, cvxpy/tests/test_grad.py, cvxpy/tests/test_nonlinear_atoms.py, cvxpy/tests/test_problem.py, cvxpy/tests/test_qp_solvers.py, cvxpy/tests/test_quad_form.py, cvxpy/tests/test_semidefinite_vars.py
As suggested by @SteveDiamond, this PR defines solvers for all tests which currently don't specify a solver.
The idea is that a test should not depend on the users' setups.
=> Specify solvers in tests

continuous_integration/install_dependencies.sh
Since Github action secrets are not copied to forks, the CI fails on PRs after adding Mosek.
This PR skips the Mosek install in case the secret is not available. It is not an ideal solution, as there is some chance that a test only fails on Mosek after the PR is merged.
=> [CI] Only install Mosek if license is available

setup.py
I know `-Wall` was already in here, but it seemed complete to add it.
Nothing worrisome came up with the addition of the new warnings.
=> Add some aggressive compilation warning settings

cvxpy/reductions/solvers/conic_solvers/scs_conif.py
Matching the string is somewhat brittle. Matching the status values should be more robust and more backwards compatible.
=> Update SCS status map to use status vals rather than string matching

cvxpy/reductions/solvers/conic_solvers/diffcp_conif.py, cvxpy/tests/test_derivative.py
This PR adds ECOS support within `DIFFCP` calls from CVXPY.  It is done by passing the solver-specific option `solve_method`, for example,
```python
problem.solve(requires_grad=True, solver=cp.DIFFCP, solve_method="ECOS")
```
As expected, it does not support warm-starting, but it can be much more reliable than SCS for some problems.
This  PR depends on https://github.com/cvxgrp/diffcp/pull/42 (the returned ECOS info needs to match SCS format).
I have modified the `test_derivative.py` file to test also ECOS (and excluded the exponential cone examples).
=> Added ECOS support in DIFFCP

cvxpy/expressions/constants/constant.py, cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py, cvxpy/tests/test_expressions.py, cvxpy/tests/test_problem.py, cvxpy/tests/test_quad_form.py
This fixes #1451. The only change to non-test code is to apply a keyword argument to SciPy's ``eigsh`` so that it returns eigenvalues sorted by value rather than absolute value. Some earlier tests should have caught the bug in #1451, but they tested Parameter objects rather than Constant objects.
We should revisit this in the near future. The largest or smallest eigenvalues returned by ``eigsh`` when running in shift-invert mode are sorted differently than if we don't use shift-invert mode. Although (updated!) tests are passing, we should take a more careful look to make sure we won't run into issues with this different sorting. 
We should also add tests for semidefiniteness based on the Gershgorin Circle Theorem, as I mentioned in #1451.
Edit: I've marked this as work-in-progress to make …
=> Fix Constant.is_psd() and Constant.is_nsd()

cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py, cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_qp_solvers.py, doc/source/tutorial/advanced/index.rst
Adds support for Gurobi Environments: https://www.gurobi.com/documentation/9.1/refman/environments.html
Environments store configuration parameters, licensing information, and provide other capabilities.  This is critical for Gurobi ISV licenses, which may not have a license file that is set via an environmental variable.
The environment is specified in the cp.solve() method with an optional 'env' argument that is detected in the solver_opts dict.  StandardTests are employed to detect changes to the parameters in the resulting model.  The StandardTest methods were modified to return a SolverTestHelper rather than None.  Although the tests only use two of these methods, all methods were modified to consistency and to encourage re-use of these StandardTests.
=> Support for Gurobi Environments

cvxpy/problems/problem.py, cvxpy/reductions/dqcp2dcp/dqcp2dcp.py, cvxpy/reductions/dqcp2dcp/sets.py, cvxpy/reductions/solvers/bisection.py, cvxpy/tests/test_problem.py
Problem canonicalization fails silently when an expression is included
in a problem's list of constraints.
This change modifies the Problem constructor to check that each
constraint is in fact a Constraint (or a bool)
Previously DQCP included lazily evaluated
constraints in the constraint list. This change modifies the DQCP
reduction to store the lazy constraints elsewhere.
Fixes #1462
=> Validate constraints on problem creation

cvxpy/problems/problem.py, cvxpy/reductions/dqcp2dcp/inverse.py, cvxpy/reductions/solvers/bisection.py, cvxpy/tests/test_dqcp.py
- Add inverse operator for (signed) abs, fix operator for ratio (fixes #1477)
- Flip user specified bisection limits when flip objective is used
=> Fixes for DQCP

cvxpy/reductions/dqcp2dcp/dqcp2dcp.py, cvxpy/reductions/dqcp2dcp/inverse.py, cvxpy/reductions/dqcp2dcp/sets.py, cvxpy/tests/test_dqcp.py
Edge case in which a user takes a sum/cumsum of a scalar atom.
=> Implement trivial inverses for some more atoms

.github/workflows/build.yml, doc/source/install/index.rst, setup.py
Discussion: #1478 
@SteveDiamond as discussed, this additional action publishes `cvxpy-base` on PyPi, i.e. without any solvers preinstalled.
I have done a test run on [TestPyPI](https://test.pypi.org/project/cvxpy-base/), which worked well.
It can be tried using:
```
pip install scipy
pip install --index-url https://test.pypi.org/simple/ cvxpy-base
```
It would only run with the next tagged release, but one could upload the current 1.1.15 version by disabling the `${{env.DEPLOY == 'True'}}` checks for one commit.
I have added a small section to the docs as well.
=> [CI] Build cvxpy-base (Issue 1478)

.github/workflows/build.yml
@SteveDiamond The default shell for Windows is `pwsh`, so `$PYPI_USER` is not recognized, leading to the error `twine upload: error: argument -u/--username: expected one argument`.
=> [CI] Fix Windows deploy for cvxpy-base

doc/source/contributing/index.rst, doc/source/index.rst
* Add meta description to homepage.
* Greater emphasis on community.
* Highlight Github discussions.
I think it's beneficial for the community to have two forums, one for real-time conversation (Discord), and one for slower, more in-depth conversation (Discussions). Discussions also frees us from SO's moderation, which sometimes closes questions that I think are relevant (such as this one: https://stackoverflow.com/questions/69768609/constraining-a-variable-to-convex-combination-of-two-variables-cvxpy).
We have already gotten some interesting feature requests from Discussions, which have been promoted to Github issues.
=> Edits to doc homepage

cvxpy/expressions/constants/constant.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_expressions.py, cvxpy/utilities/eigvals.py
This resolves #1532 by starting checks for PSD/NSD-ness with the method in https://en.wikipedia.org/wiki/Gershgorin_circle_theorem. If that test passes, then we bypass ARPACK.
=> Gershgorin circle theorem PSD/NSD checks

pyproject.toml
Adding this config, one can call
```
pytest
```
instead of 
```
pytest cvxpy/tests
```
The former also so far added tests from `cvxpy/examples/extensions/mixed_integer/tests/test_vars.py`, which fail (at least in my case).
Additionally, the tests from the examples folder could be moved to `cvxpy/tests`, if they are still relevant.
=> Specify tests paths

cvxpy/tests/test_atoms.py
Issue: #1543 
Python 3.10 prepends the class name to the `__init__()` in the error message, so I use a slightly more generic test.
This should unblock @h-vetinari. As a follow-up, Python 3.10 could also be included in the CI.
=> Fix test failing under Python 3.10

cvxpy/problems/problem.py, cvxpy/reductions/solution.py, cvxpy/reductions/solvers/conic_solvers/cplex_conif.py, cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py, cvxpy/reductions/solvers/conic_solvers/nag_conif.py, cvxpy/reductions/solvers/conic_solvers/scip_conif.py, cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py, cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py, cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py, cvxpy/reductions/solvers/qp_solvers/xpress_qpif.py, cvxpy/settings.py, cvxpy/tests/test_conic_solvers.py, doc/source/tutorial/advanced/index.rst, doc/source/tutorial/intro/index.rst
This resolves #1071.  I added a user-facing ``INFEASIBLE_OR_UNBOUNDED`` status. I also changed GUROBI and CPLEX interfaces (conic and QP) to automatically re-solve when they encounter such a status. The documentation has been updated so that users can set ``reoptimize=False`` when using these solvers and get the ``INFEASIBLE_OR_UNBOUNDED`` status directly. I'm open to discussion on what the default behavior here should actually be.
=> User-facing "infeasible or unbounded" status

cvxpy/reductions/complex2real/complex2real.py, cvxpy/tests/test_complex.py
Fixes #1133 and #1090. Right now the complex2real reduction fails when a solver returns no dual variables (as happens with mixed-integer programs). The solution was just to check if dual variables were present before trying to parse them.
I also did a find-and-replace to replace "cvx" with "cp" in test_complex.py.
Note: I closed a PR of the same name that had messy commit history
=> Have complex2real handle absence of dual variables

cvxpy/tests/test_dpp.py
Issue #1241 reported two test errors. One of those was ``test_ecos_bb_mi_lp_2``, which is a known failure case for ECOS_BB and has since been disabled by default. The other issue was that tolerances in ``test_sum_matrix`` (in ``test_dpp.py``) were too stringent. This sets more reasonable tolerances for ``test_sum_matrix`` (and other tests in that file) and so should close #1241.
=> reduce accuracy requirement in test_sum_matrix

cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
I propose two changes in the MOSEK log output.
1. Remove automatic printing of infeasibility report/certificate. Since cvxpy does not pass names to MOSEK, this was not very useful in the first place (one has to know the mapping from cvxpy variables to the ``x`` variable in MOSEK to understand the report). Now that CVXPY dualizes continuous problems it is simply impossible even for a fairly expert user to immediately relate that report to the original problem. And that report can have lots of rows, obscuring the interesting part of the optimization log.
2. If we go verbose and log is enabled at all I see no reason why presolve log should be specifically disabled. It is just a few lines and sometimes can actually be informative.
=> Change logging in MOSEK

doc/source/tutorial/dqcp/index.rst
product of two nonnegative concave (not qccv) functions is qccv
=> Fix typo in DQCP docs

cvxpy/reductions/solvers/conic_solvers/cplex_conif.py
Given the current attention to remote code execution, it's probably a good time to remove the `eval()` statement while setting CPLEX parameters.
Admittedly, it would be quite a niche use case to get user input for solver parameters, but better safe than sorry.
=> CPLEX parameter setting

examples/notebooks/WWW/Channel_capacity_BV4.57.ipynb
This PR aims to fix the bugs mentioned in https://github.com/cvxpy/cvxpy/issues/1578
Also, it uses `@` instead of the deprecated `*` for matrix-matrix multiplication
Note that `xlogy(P, P)` is actually `e-based`, and `cp.entr(y)` is also `e-based`. I think base-2 makes more sense (considering the fact that the original code has already used `P*np.log2(P)`, which is `2-based`).
=> Fix bugs in the example of Channel Capacity

.github/workflows/build.yml
The latest PyPI release is missing the source: https://pypi.org/project/cvxpy/#files
This PR sets the missing environment variable. 
Unfortunately, this means you'd need to trigger the wheel build again @SteveDiamond .
=> Fix missing source deploy

continuous_integration/install_dependencies.sh
The free Gurobi license has expired for Python 3.6, leading to unrelated test failures in #1606.
> gurobipy.GurobiError: License expired 2022-01-13
=> [CI] Remove Gurobi for Python 3.6

.github/workflows/docs.yml, .pre-commit-config.yaml, PROCEDURES.md, continuous_integration/doc_is_latest.py, continuous_integration/doc_write_versions.py, doc/source/conf.py, doc/themes/version_selector.html
This PR enables deploying multiple versions of the web documentation as a second follow-up to #1598.
Whenever the action is triggered:
1. The docs are built
2. The docs are deployed into a `version/MAJOR.MINOR` folder (overwriting if already exists) on the `gh-pages` branch
3. If the version of the current build is greater or equal to the highest previously deployed version, the docs are also deployed to the root of the `gh-pages` branch.
4. A file called `versions.json` in the root of the `gh-branch` is created or updated, which lists all currently deployed version
5. A dynamic version selector will reflect the changes in 4., such that one can always switch between all deployed versions
I have experimented with the setup in my fork, see [here](https://phschiele.github.io/cvxpy/) (I'll …
=> [doc] Multi-version documentation deployment

continuous_integration/install_dependencies.sh
This PR tries to fix recent test failures outlined in the issue below 
(second PR as the first branch was not based on the current master).
Issue link (if applicable): #1626 
Python 3.6:
The `dataclasses` module seems to be no longer available. This feature was introduced in Python 3.7, but a backport to 3.6 is available.
pyscipopt:
A new version was released yesterday: https://anaconda.org/conda-forge/pyscipopt/files
Limiting the version to get the tests passing again until the interface has been fixed.
=> WIP: Build failures: Python 3.6, and SCIP

cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py, cvxpy/reductions/solvers/conic_solvers/glpk_conif.py, cvxpy/reductions/solvers/conic_solvers/glpk_mi_conif.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_conic_solvers.py
When no constraints are specified, the GLPK_MI and GLPK solvers would previously fail. Here we convert missing constraint matrices from `None` into trivial matrices that are valid for use by `cvxopt.glpk`.
Issue link (if applicable): https://github.com/cvxpy/cvxpy/issues/1614
```
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/allen/work/community/cvxpy, configfile: pyproject.toml
collected 11 items                                                                                                                                                         
cvxpy/tests/test_benchmarks.py …
```
=> Fix: GLPK with no constraints

doc/source/tutorial/advanced/index.rst
Docfix for the DPP ruleset. I'm not entirely sure this captures what the paragraph was trying to say, but there was definitely something wrong with the documentation beforehand (e.g. ``x`` is definitely not variable-free).
=> docfix for Advanced Features / DPP

cvxpy/interface/scipy_wrapper.py
I fixed a scipy deprication warning which is reported in #1654
> cvxpy\cvxpy\interface\scipy_wrapper.py:17: DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
=> Fix scipy deprecation warning

cvxpy/cvxcore/src/Utils.cpp, cvxpy/tests/test_benchmarks.py
See discussion on https://github.com/cvxpy/cvxpy/issues/1668. The pruning in `Utils.cpp:mat_vec_mul` is causing order of magnitude slow-downs on some problems.
I've added a new benchmarking test -- this change takes its run time on my machine from ~8.4 seconds to ~0.7 seconds.
Closes #1668 
I think there is still discussion on #1668 about whether we want this change, but the consensus seems to be moving towards yes, so I thought I'd open a PR.
=> Remove pruning added by 9672acf

cvxpy/reductions/eliminate_pwl/atom_canonicalizers/cumsum_canon.py, cvxpy/tests/test_problem.py
Fixed the axis bug in cumsum() by adding special cases to https://github.com/cvxpy/cvxpy/blob/master/cvxpy/reductions/eliminate_pwl/atom_canonicalizers/cumsum_canon.py
Issue link (if applicable): Issue #1678
=> Updated cumsum_canon.py for axis bug

cvxpy/reductions/eliminate_pwl/atom_canonicalizers/cummax_canon.py, cvxpy/reductions/eliminate_pwl/atom_canonicalizers/cumsum_canon.py, cvxpy/tests/test_problem.py
Changed the `test_cumsum_axis()`, added a new unit test for `test_cummax_axis()` and updated the `cummax_canon` for axis bug.
Issue link : #1678
=> Updated cumsum test, added cummax test, fix cummmax

cvxpy/expressions/expression.py, cvxpy/tests/test_numpy.py
Following up on #1647 
This code is supposed to not raise an error on anything that used to succeed (which was just the `np.hstack`/`np.vstack` equivalents I believe); however, by adding the `__array_function__` method NumPy is now assuming we can handle everything and when we say we can't (i.e. we return `NotImplemented`) it chooses to errors instead of creating an array of objects as it used to. The error message has changed on a number of things to say that we have a `TypeError` instead of an `AttributeError`.
If breaking code that constructs arrays with `np.hstack` and `np.vstack` is not acceptable, (`np.array` will still work though) then we can probably just eliminate the `__array_function__` implementation, but I don't see any easy way to generate the warning while preserving old …
=> Adds error for mixing NumPy and CVXPY

cvxpy/atoms/geo_mean.py, cvxpy/tests/test_power_tools.py, cvxpy/tests/test_problem.py, cvxpy/utilities/power_tools.py
My change to ``dyad_completion`` in PR #1687 wasn't enough to solve all the ``geo_mean`` bugs now reported #1685. A full fix required making ``dyad_completion`` recursive. Previous test cases never hit this new recursive code path. I added a new file for unit tests relating to ``cvxpy.utilities.power_tools.py``. 
Note: only one of the new tests hits the new code path. The other test is there to help us address #1223.
=> more fixes for geo_mean canonicalization #1685 (follow-up on PR #1687)

cvxpy/atoms/log_sum_exp.py, cvxpy/tests/test_atoms.py
Stephen Boyd noticed that log_sum_exp of a non-negative value has unknown sign, where it should be non-negative. This PR fixes the sign error.
=> Fix sign error with log_sum_exp

cvxpy/cvxcore/src/LinOpOperations.cpp
Fixes the warnings issue described in #1690
=> Fix assertion sign comparison issues in LinOpOperations.cpp

cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_mip_vars.py
We add a new test `StandardTestLPs.test_mi_lp_5`. This test fails with CBC because of https://github.com/coin-or/CyLP/issues/81
#1703 attempts to fix it.
https://trac.sagemath.org/ticket/31962#comment:48
=> cvxpy/tests: Add test for infeasible boolean problem

cvxpy/reductions/solvers/conic_solvers/cbc_conif.py, setup.cfg
A new '''cylp''' release, https://pypi.org/project/cylp/0.91.5/, fixes the broken integer infeasibility detection with CBC (#1705). Thanks @tkralphs! 
We set a corresponding lower version bound in `extras_require` for '''cylp'''.
Also remove handling of a misspelled cylp problem status (#1707). The typo has not made it into a cylp release.
=> Cylp update

doc/source/api_reference/cvxpy.atoms.affine.rst, doc/source/api_reference/cvxpy.atoms.rst, doc/source/api_reference/cvxpy.problems.rst, doc/source/conf.py, doc/source/contributing/index.rst, doc/source/examples/applications/censored_data.rst, doc/source/examples/applications/fault_detection.rst, doc/source/examples/applications/l1_trend_filter.rst, doc/source/examples/applications/parade_route.rst, doc/source/examples/basic/mixed_integer_quadratic_program.rst, doc/source/faq/index.rst, doc/source/index.rst, doc/source/related_projects/index.rst, doc/source/tutorial/advanced/index.rst, doc/source/tutorial/dqcp/index.rst, doc/source/tutorial/functions/index.rst, doc/source/updates/index.rst
This resolves #1710 and #1713. I also added material that explains the precise meaning of "atom" in cvxpy's code base, slightly changed some text formatting, and moved a bit of content around within a single ``.rst`` file.
This PR is pulling into the release/1.2.x branch. If merged, then I'll tag the commit with "doc1.2.0-update" (currently the name of this branch) and manually trigger a doc build with GitHub actions. The build will happen with the unreleased version of 1.2.1, which is functionally equivalent to 1.2.0 (the only difference is version flags in setup.py). I made a change to sphinx's ``conf.py`` to make sure the patch number doesn't appear in metadata for the web documentation.
Once web docs are fixed on this branch I'll propagate changes to master.
=> web documentation updates

cvxpy/reductions/solvers/conic_solvers/scip_conif.py, doc/source/install/index.rst, setup.cfg
This PR makes three changes relating to SCIP:
* it narrows the scope of the "try" step in a try-except block within ``SCIP._solve``.
* it checks for the existence of solutions before trying to access the model objective value (fixing a problem reported in #1702),
* it specifies a version limit that pyscipopt < 4.0.0.
That third point is a follow-up on PR #1628. It turns out that tests fail when pyscipopt 4.x is installed (note: pyscipopt 3 works exclusively with SCIP 7, and pyscipopt 4 works exclusively with SCIP 8). The specific test I saw fail used the problem defined by ``socp_1(axis=0)`` in ``solver_test_helpers.py``. SCIP incorrectly claimed that the problem was infeasible.
=> Bugfixes for the SCIP interface

cvxpy/constraints/__init__.py, cvxpy/constraints/finite_set.py, cvxpy/reductions/discrete2mixedint/valinvec2mixedint.py, cvxpy/reductions/solvers/conic_solvers/scip_conif.py, cvxpy/reductions/solvers/solving_chain.py, cvxpy/tests/test_valinvec2mixedint.py, doc/source/api_reference/cvxpy.constraints.rst, doc/source/install/index.rst, setup.cfg
These changes add support for a `finiteSet` constraint class, that allows for restricting a variable to a given set of arbitrary (finite) lengths, composed of any real quantities. These changes are motivated by the [issue](https://github.com/cvxpy/cvxpy/issues/1590) --- in this PR, only support for DCP problems is offered, I would be open to working on extending the same to DGP problems as well.
A short rundown of the files changed/added:
1. The `cvxpy/constraints/MI_FS.py` file houses the structure of the new constraint class itself.
2. `cvxpy/reductions/discrete2mixedint/valinvec2mixedint.py` consists of the `Canonicalization` class for the `finiteSet` constraint, in addition to the concerned canonicalization method (`exprval_in_vec`, wrapped around `finite_set_canon`)
3. The change to …
=> Finite sets

cvxpy/tests/test_gurobi_write.py
Based on setup.py and requirements, gurobi is no mandatory.
Thus, we need to skip test gurobi write if not exist
- [v] Bug fix
- [v] Add our license to new files.
- [v] Check that your code adheres to our coding style.
- [v] Write unittests.
- [v] Run the unittests and check that they’re passing.
=> Skip test gurobi write if not exist

cvxpy/constraints/finite_set.py, cvxpy/reductions/discrete2mixedint/valinvec2mixedint.py, cvxpy/tests/test_valinvec2mixedint.py
As discussed, this PR is a follow-up to #1740, containing the following changes:
- ~Using @rileyjmurray 's suggested implementation as the default. I believe this was accidentally changed in 2eab70c974300b8901943994fc50c1c57a389bfa Renamed the functions to improve readability~ This was intentional, see comment below
- Small refactoring to reduce code duplication as suggested 
- Adding a few more tests
- Parametrizing the tests to use both canonicalization functions (+ one test to check that using the default works)
- Skipping the tests if GPLK-MI is not installed as suggested by @SteveDiamond [here](https://github.com/cvxpy/cvxpy/pull/1740#issuecomment-1094513642)
- Special handling for the case where `len(vec) == 2`, as `z[1:] <= z[:-1]` failed in that scenario
- Added a suggestion for …
=> Follow-up FiniteSet

cvxpy/atoms/length.py, cvxpy/tests/test_dqcp.py
The length atom is too strict about non-zeros. It should consider values with magnitude below a numerical tolerance zero.
Issue link (if applicable): #1760
=> Fix bug with length atom

cvxpy/atoms/affine/reshape.py, cvxpy/expressions/expression.py, cvxpy/tests/test_expressions.py, cvxpy/utilities/shape.py
This pull request follows the discussion in issue #1784, which replaces calls to np.prod in expression.py and reshape.py with calls to functools.reduce, as recommended by @phschiele 
Performance improvement of hstack.
=> replace np.prod with utilities.shape.size_from_shape to improve performance

.github/workflows/build.yml
Added CI changes to build M1 wheels to 1.2.x release branch.
After this PR is merged, we need to undo the "prepare for next release" commit, trigger a deploy, and then redo the "prepare for the next release commit". I can create separate PRs for this, or it can be done directly in the release branches.
=> [CI] Build wheels for M1 (release/1.2.x)

.github/workflows/build.yml
Added CI changes to build M1 wheels to 1.1.x release branch.
After this PR is merged, we need to undo the "prepare for next release" commit, trigger a deploy, and then redo the "prepare for the next release commit". I can create separate PRs for this, or it can be done directly in the release branches.
=> [CI] Build wheels for M1 (release/1.1.x)

cvxpy/reductions/solvers/conic_solvers/scip_conif.py
This PR addresses fixes a typo and hides the warning for having the wrong version of SCIP on import.
Issue link (if applicable): #1805
=> Hide SCIP warning.

doc/source/tutorial/functions/index.rst
In the table of elementwise functions, clarify that CVXPY's `abs()` function supports complex numbers.
See: https://www.cvxpy.org/_modules/cvxpy/atoms/elementwise/abs.html
Issue link (if applicable): N/A
=> [doc] Clarify that abs() supports complex numbers

cvxpy/atoms/quad_form.py, cvxpy/tests/test_quad_form.py
Adds an argument to quad_form to skip checking that P is PSD.
=> Assume PSD argument to quad_form

cvxpy/atoms/sign.py, cvxpy/tests/test_dqcp.py
The sign function is only quasilinear when applied to univariate input. Currently the function is marked as quasilinear for inputs of any dimension.
Issue link (if applicable): #1828
=> Fix DQCP issue with sign function

cvxpy/atoms/affine/diff.py, cvxpy/tests/test_atoms.py
There was a bug in diff that made it impossible to use on some arrays with dimension 1.
Issue link (if applicable): #1834
=> Fix bug with diff

cvxpy/tests/test_mip_vars.py
Failing test creates downstream issues like no coverage reports.
Issue link (if applicable): #1815
=> [CI] Skip XPRESS test

README.md
Add two badges to point to:
- Sonarcloud (coverage)
- Benchmark page
=> Add Coverage and benchmark badges

cvxpy/atoms/__init__.py, cvxpy/atoms/tr_inv.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/__init__.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/tr_inv_canon.py, cvxpy/tests/test_atoms.py, examples/ex_tr_inv.py
Hello, since the current cvxpy does not support the atomic operation 
$$\operatorname{trace}\left( \operatorname{inv}\left( X \right) \right)$$
where $X$ is PSD, but I need that feature in my research work. I designed the atomic operation and contributed it to the cvxpy community. Our main work is to demonstrate that 
$$\operatorname{trace}\left( \operatorname{inv}\left( X \right) \right)$$
is convex and to implement an equivalent cone form of it. In addition, we provided an example in "examples/ex_tr_inv.py"
The code we submitted in
1. "cvxpy/atoms/tr_inv.py"
2. "cvxpy/reductions/dcp2cone/atom_canonicalizers/tr_inv_canon.py"
3. "cvxpy/reductions/dcp2cone/atom_canonicalizers/tr_inv_canon.py"
4. "cvxpy/atoms/__init__.py"
5. "cvxpy/reductions/dcp2cone/atom_canonicalizers/__init__.py"
6. …
=> contribute a atomic operation of trace(inv(X))

.github/workflows/build.yml, continuous_integration/test_script.sh
Tests are failing bc our current macOS runner is deprecated and will be removed soon.
=> [CI] Bump macOS runner

cvxpy/atoms/dotsort.py, cvxpy/problems/problem.py, cvxpy/tests/test_custom_solver.py
Looks like there was a new release of flake8 that requires a few small changes to make the linters pass again:
=> Fix linters

.github/workflows/build.yml, continuous_integration/test_script.sh, cvxpy/atoms/dotsort.py, cvxpy/constraints/second_order.py, cvxpy/problems/problem.py, cvxpy/reductions/solvers/conic_solvers/copt_conif.py, cvxpy/reductions/solvers/conic_solvers/scipy_conif.py, cvxpy/reductions/solvers/defines.py, cvxpy/reductions/solvers/qp_solvers/copt_qpif.py, cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_constraints.py, cvxpy/tests/test_custom_solver.py, cvxpy/tests/test_problem.py, cvxpy/utilities/versioning.py, doc/source/install/index.rst, doc/source/tutorial/advanced/index.rst
This PR points to the `bugfix/soc_resid` branch and adds handling for the edge cases, taking inspiration from @rileyjmurray 's code in the issue and the mosek docs.
(The linters were failing here, so I merged the master into this branch. Merge master into ``bugfix/soc_resid`` to get rid of the noise in this PR).
=> Suggestion SOC residual

cvxpy/atoms/quad_form.py, cvxpy/tests/test_grad.py
Implement a fix for retrieving gradient of quad_form for a two-dimensional optimization problem.
Current unit test for gradient of quad_form still passes. I added an additional unittest for multidimension quad_form gradient.
Fix for https://github.com/cvxpy/cvxpy/issues/1837
New test would fail under the original code:
=> fix gradient for multidimensional quad form

cvxpy/reductions/solvers/conic_solvers/glop_conif.py, cvxpy/reductions/solvers/conic_solvers/pdlp_conif.py, cvxpy/tests/test_conic_solvers.py
Fixes #1858
I looked for examples of tests that check that the time limit is actually hit but didn't find any. These are potentially flaky, but still useful to check that the time limit is actually enforced.
=> Fix time_limit_sec for GLOP and PDLP

README.md
cvxpy requires Python 3.7+, as stated on the [Installation Guide](https://www.cvxpy.org/install/index.html) and in [setup.py](https://github.com/cvxpy/cvxpy/blob/v1.2.1/setup.py#L227).
=> Update README to reflect Python 3.7+ requirement

cvxpy/expressions/constants/parameter.py, cvxpy/expressions/leaf.py, cvxpy/expressions/variable.py
This pull requests improves typing annotations. The main changes are:
- adds `int` as a valid type for shape argument in `cp.Parameter()` and `cp.Variable()`
- using [`__future__.annotations`](https://peps.python.org/pep-0563/), we can simplify the typing annotations
=> Typing annotation improvements

continuous_integration/install_dependencies.sh, cvxpy/reductions/solvers/conic_solvers/glop_conif.py, cvxpy/reductions/solvers/conic_solvers/pdlp_conif.py, setup.cfg
The code remains compatible with both 9.3 and 9.4. Also place conservative upper bounds on the supported version because the ortools API may change in any point release.
Closes #1868
=> Update PDLP interface for ortools 9.4

cvxpy/atoms/norm.py, cvxpy/tests/test_atoms.py
Signed-off-by: KerimovEmil 
Raising an error for non-supported string arguments into norm atom, and handling the fro norm.
Addressing issue: https://github.com/cvxpy/cvxpy/issues/1865
=> Adding edge case handling for string inputs into norm

cvxpy/reductions/solvers/conic_solvers/scs_conif.py
Switches SCS timings from milliseconds to seconds.
Issue link (if applicable): #1878
=> Switch SCS timings to seconds

cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py
[Warm start example](https://www.cvxpy.org/tutorial/advanced/index.html#warm-start) with osqp is currently not working with the same speed as in the docs. The problem is the incorrect comparison of the shapes of A, which leads to a new factorization even if the problem did not change at all.
```
import numpy
m = 2000
n = 1000
numpy.random.seed(1)
A = numpy.random.randn(m, n)
b = cp.Parameter(m)
x = cp.Variable(n)
prob = cp.Problem(cp.Minimize(cp.sum_squares(A @ x - b)),
[x >= 0])
b.value = numpy.random.randn(m)
prob.solve()
print("First solve time:", prob.solver_stats.solve_time)
prob.solve(warm_start=True)
print("Second solve time:", prob.solver_stats.solve_time)
```
leads currently to
```
First solve time: 9.593317918
Second solve time: 4.873378319
```
while after …
=> fix osqp warm start

cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_conic_solvers.py
Fixes tests that started failing once Mosek 10 was deployed.
=> Fix tests that started failing with Mosek 10

.github/workflows/build.yml
> The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
Noted by @SteveDiamond
=> [CI] Bump Ubuntu runner

.github/workflows/scorecards.yml, README.md
I've configured the OpenSSF Scorecard Github Action with the scorecard.yml file in the .github/workflow folder.
Besides, I've added the [badge](https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/) to readme file, which is completely optional but could be intersting to keep.
Issue link (if applicable): Closes #1891
=> Add the OpenSSF Scorecard Github Action

cvxpy/__init__.py, cvxpy/reductions/solvers/defines.py, cvxpy/tests/test_conic_solvers.py
Tiny follow up to #1888 , allowing the usage `cp.CLARABEL`.
Also just a small note on adding CLARABEL at index 0 of `CONIC_SOLVERS` in `solvers/defines.py`:
This implicitly makes CLARABEL (if installed) the default solver for supported problems. As soon as CLARABEL is being 
added as a dependency, this _could_ cause some regressions for users simply calling `.solve()`, which we should be aware of.
Again, many thanks to @goulart-paul for the great contribution.
=> Add clarabel to cvxpy/__init__.py

cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py, cvxpy/tests/test_conic_solvers.py
When setting `use_quad_obj=False` a `TypeError` is raised for Clarabel. 
Like in the SCS interface, we need to delete the key before parsing the options.
=> Allow setting use_quad_obj=False for Clarabel

cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py, cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py, cvxpy/reductions/solvers/utilities.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_qp_solvers.py, doc/source/tutorial/advanced/index.rst
This adds the ability to specify an initial guess for Gurobi from #1664.
Issue link (if applicable): #1664
=> Initial values for Gurobi

continuous_integration/install_dependencies.sh, cvxpy/reductions/solvers/conic_solvers/scip_conif.py, cvxpy/tests/test_conic_solvers.py, doc/source/install/index.rst, setup.cfg
This interface works with the latest pyscipopt and SCIP. It does not provide dual variables for SOCPs, only for LPs.
Issue link (if applicable): https://github.com/cvxpy/cvxpy/issues/1889
=> New SCIP interface

cvxpy/atoms/von_neumann_entr.py, cvxpy/reductions/cone2cone/approximations.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/__init__.py, cvxpy/tests/test_von_neumann_entr.py
This PR implements an alternate, approximate canonicalization pathway for the `von_neumann_entr` atom. 
I adapted the same series of semi-definite approximations that I have been implementing so far for the previous `Constraint` classes to get a representation for `von_neumann_entr`. 
The API for `von_neumann_entr` remains unchanged --- if the user wants to employ this approximate formulation in their program, then they can just pass in the usual parameters for the approximation along with the input matrix, like so: `atom=von_neumann_entr(N, (m, k))`.
Some documentation in `von_neumann_entr`'s docstring still remains, but other than that, this is mostly complete!
Thanks!
=> Approximate canonicalization for `von_neumann_entr`

cvxpy/expressions/leaf.py, cvxpy/expressions/variable.py, cvxpy/tests/test_expressions.py
Allow shapes to be passed as lists to be consistent with the NumPy API. 
Issue link (if applicable): #1921
=> Allow lists as shapes

cvxpy/atoms/elementwise/elementwise.py
=> SciPy 1.9 compatibility

cvxpy/atoms/tr_inv.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/tr_inv_canon.py, doc/source/api_reference/cvxpy.atoms.other_atoms.rst, doc/source/tutorial/functions/index.rst
Fixes #1932 
Note: I have changed the symbol of the argument from `A` to `X` to indicate that it is a variable, not a constant (more consistent with other atoms).
Docs:
and
=> [Doc] Add documentation for tr_inv

cvxpy/tests/test_mip_vars.py
When running the test suite with SciPy 1.9, the `TestMIPVariable` test fails, blocking #1936.
~We should probably investigate the root cause beyond excluding it from the tests, happy to create an issue for tracking this investigation.~ See #1938
=> [CI] Exclude failing SCIPY MIP test

pyproject.toml, setup.cfg, setup.py
This PR pins the setuptools version to the latest version that's used in the project's CI.
Resolves #1950 that was introduced due to https://github.com/pypa/setuptools/issues/3693
- ~~[ ] Add our license to new files.~~
- ~~[ ] Write unittests.~~
Test procedure:
- Install package from source with `python setup.py develop && pip install .`
- Run unit tests with `cd cvxpy/tests && pytest`
- Run benchmarks with ``
Test results:
- Unit tests: `852 passed, 289 skipped, 543 warnings in 41.25s`
- Benchmark: `9 passed, 3 skipped, 1 warning in 6.43s`
=> Pin setuptools version to fix installation with pip

cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py, cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
APIs for adding constraints has changed with gurobipy version 10, this PR has the necessary updates.  Also I removed references to a non-documented API in gurobipy version 8.1.1, which is no longer supported.
=> Adapt to API changes in gurobipy

cvxpy/reductions/dgp2dcp/dgp2dcp.py
Fix a typo in Dgp2Dcp example for the dcp_problem variable name.
=> Fix a typo in Dgp2Dcp example

cvxpy/constraints/__init__.py, cvxpy/constraints/exponential.py, cvxpy/reductions/cone2cone/approximations.py, cvxpy/reductions/dcp2cone/atom_canonicalizers/von_neumann_entr_canon.py, cvxpy/reductions/solvers/solving_chain.py, cvxpy/tests/test_cone2cone.py, cvxpy/tests/test_von_neumann_entr.py, doc/source/api_reference/cvxpy.constraints.rst
This renames the ``OpRelConeQuad`` and ``RelEntrQuad`` constraint classes to ``OpRelEntrConeQuad`` and ``RelEntrConeQuad``. It also introduces more informative warning messages.
=> Quad approx and vn entr improvements

doc/source/examples/applications/fault_detection.rst, examples/notebooks/WWW/fault_detection.ipynb
Numpy just released a new version that deprecated `np.int`. Removing two non-urgent cases in CVXPY codebase.
More urgent ecos PR is here: https://github.com/embotech/ecos-python/pull/45
Not marking this one as a bug fix, as it only affects one example
Issue link (if applicable): https://discord.com/channels/845323972962549790/845327242456203295/1054122743001526413
=> Remove usage of deprecated np.int 

cvxpy/reductions/solvers/conic_solvers/xpress_conif.py, cvxpy/tests/test_conic_solvers.py, doc/source/tutorial/advanced/index.rst
This change introduces option "save_iis" for the FICO Xpress conic solver. For infeasible problems, the user can choose if and how many IIS (Irreducible Infeasible Subsystems) should be returned together with the infeasibility result. Returning IIS is now off by default because of its performance impact.
If solver_opts['save_iis'] is positive, at most as many IISs are returned. If negative, all IIS are returned. If zero or not specified, no IIS is returned.
=> Add option for skipping generation of IIS

cvxpy/atoms/affine/trace.py, cvxpy/constraints/constraint.py, cvxpy/constraints/exponential.py, cvxpy/constraints/power.py, cvxpy/expressions/constants/constant.py, cvxpy/reductions/complex2real/canonicalizers/__init__.py, cvxpy/reductions/complex2real/canonicalizers/aff_canon.py, cvxpy/reductions/complex2real/canonicalizers/matrix_canon.py, cvxpy/reductions/complex2real/complex2real.py, cvxpy/reductions/cone2cone/approximations.py, cvxpy/tests/test_cone2cone.py, cvxpy/tests/test_constant_atoms.py, cvxpy/tests/test_expressions.py, cvxpy/tests/test_von_neumann_entr.py, cvxpy/utilities/linalg.py
@SteveDiamond @phschiele this is ready for review. Once this PR is merged we will have all the functionality I wanted ready for CVXPY 1.3. (There's still more to do, but it's reasonable to hold until CVXPY 1.4.)
The quadrature-based approximation of the operator relative entropy cone: ``OpRelEntrConeQuad``.
* This constraint class now accepts Hermitian input. Previously, it only accepted symmetric input.
* The ``TestOpRelConeQuad`` class  in ``tests/test_cone2cone.py`` has been rewritten.
The ``von_neumann_entr`` atom.
* This now accepts Hermitian input. Previously it only accepted symmetric input.
* The ``Test_von_neumann_entr`` class in ``tests/test_von_neumann_entr.py`` has been rewritten.
* Since its introduction into cvxpy's master branch,``von_neumann_entr``'s default …
=> Operator relative entropy and von Neumann entropy: allow Hermitian input

cvxpy/tests/test_constant_atoms.py
The build failures in https://github.com/cvxpy/cvxpy/actions/runs/3772470280/jobs/6413421816 happened even though ``(cp.xexp, cp.MOSEK)`` were added to the list of known solver errors in ``test_constant_atoms.py``. Upon further inspection, that's because the ``KNOWN_SOLVER_ERRORS`` list wasn't being checked in the appropriate way. This PR addresses that; I've confirmed that it correctly skips the case of ``('xexp', cp.MOSEK)`` (note the problematic atom has to be specified as a string now).
=> correct handling of KNOWN_SOLVER_ERRORS in test_constant_atoms.py

cvxpy/constraints/exponential.py, cvxpy/constraints/finite_set.py, cvxpy/constraints/nonpos.py, cvxpy/constraints/power.py, cvxpy/constraints/second_order.py, cvxpy/reductions/complex2real/complex2real.py, cvxpy/reductions/cone2cone/exotic2common.py, cvxpy/tests/test_complex.py, cvxpy/tests/test_constraints.py, cvxpy/utilities/canonical.py
PR #1978 (targeting CVXPY 1.3) included bugfixes for dual variable recovery in problems with complex expressions. The fixes involved adding tuples called ``UNIMPLEMENTED_REAL_DUALS`` and ``UNIMPLEMENTED_COMPLEX_DUALS`` to the ``Complex2Real`` class. These tuples consisted of certain Constraint classes. If the type of a Constraint object belonged to one of these tuples then dual variable recovery for that Constraint would be skipped.
@SteveDiamond started the process of porting this bugfix to CVXPY 1.1 and 1.2 ([link](https://github.com/cvxpy/cvxpy/pull/1955/commits/5be035253739bf6b0a0a76a14a264e7f3831ac62#diff-06ac9467275a4f02950ff75e8cc0f196fae9c2475e68ea88beb0b80606966a5aR38-R39)). It seemed to Steven that _additional_ constraint classes were needed in these new tuples.  At Steven's …
=> Bugfixes for dual variables in Complex2Real, check for real input to certain Constraint objects

cvxpy/atoms/quad_form.py, cvxpy/expressions/cvxtypes.py, cvxpy/expressions/expression.py, cvxpy/tests/test_expressions.py, cvxpy/tests/test_quad_form.py
Hi -- small QOL upgrade for my personal cvxpy usage to automatically turn native matmul into quadratic forms where applicable. See issue #1762. When expressions are being constructed, then some MulExpression are automatically turned into a QuadForm, when certain criteria hold. 
Notes: 
1) Does not handle associativity. If we have a constant vector c, then `1/2 * c.T @ c @ x.T @ A @ x` is technically a quadratic form `(1/2 * c.T @ c) * QuadForm(x, A)`, but will not be converted in the below change. 
Reasoning here is that the expression tree leading up to the quadratic form can be arbitrarily tall and would require a search for the right-most leaf (to avoid QuadForms in cases like `1/2 * (c.T @ (c @ (d.T @ (d @ x.T)))) @ A @ y`).  However, as long as parantheses are included around `x.T @ …
=> Support for Native Quadforms (x.T @ A @ x) 

.github/workflows/docs.yml, doc/source/conf.py, doc/source/related_projects/index.rst
Sphinx recently stopped automatically including jQuery, which is required by our site for the version selector. This PR adds jQuery back to the build.
https://www.sphinx-doc.org/en/master/changes.html
=> Add jquery back to sphinx build

cvxpy/atoms/affine/sum.py, cvxpy/tests/test_perspective.py
Same fix for PyPy as in #1208; also remove a relative import that makes the test suite fail to run against an out-of-tree `cvxpy`.
From https://github.com/conda-forge/cvxpy-feedstock/pull/75
=> Fixes for 1.3.0

cvxpy/tests/test_constant_atoms.py
Per @aszekMosek's [comment](https://github.com/cvxpy/cvxpy/pull/1978#issuecomment-1373480307) on the last operator relative entropy PR, our test case for ``xexp`` that fixes the input ``x = 0`` in ``xexp(x)`` results in an ill-posed conic formulation. That is, an arbitrarily small perturbation to the conic formulation can change the problem from feasible to infeasible. This change keeps the spirit of the test while avoiding that particular case.
=> remove ill-posed test case for xexp atom

.github/workflows/build.yml
Our current build process only builds wheels when we release.
Often, failures of these builds are unrelated to the code changes. When wheels are partially released to PyPI, we have to push a fix in a subsequent release. 
This change builds whenever we merge to master or a release branch (but not on every PR commit).
Regarding changes to the procedures, @h-vetinari you [mentioned](https://github.com/cvxpy/cvxpy/pull/1998#issuecomment-1370662440) that its possible to test pre-releases against your infrastructure. Could you create an example PR on the cvxpy feedstock repo that shows how this is done, then I could add a reference to that in the PROCEDURES document.
=> [CI] Build wheels on push

cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
Changes the order of operations when initializing the Mosek task: first process options and, in particular, attach the log handler (if verbose), then input data, then optimize.
Attaching the log handler before inputting allows the user to see if Mosek produces any warnings about the magnitude of the data which could be a potential hint in case of numerical issues later in the solver.
=> Attach Mosek log handler before inputting data

continuous_integration/install_dependencies.sh, pyproject.toml, setup.cfg, setup.py
Unpins setuptools so the latest version can be installed.
Issue link (if applicable): #2021
=> Unpin setuptools

cvxpy/reductions/dgp2dcp/canonicalizers/__init__.py, cvxpy/reductions/dgp2dcp/canonicalizers/pnorm_canon.py, cvxpy/tests/test_dgp2dcp.py
Ran into the following bug with p-norms in DGP problems.
In particular, the below assertion fails: 
```
x = cp.Variable(pos=True)
norm_expr = cp.norm(cp.Constant([3,4]), p=2)
prob = cp.Problem(cp.Minimize(norm_expr * x ** 2), [x >= 1])
solution = prob.solve(gp=True) # Correctly returns 5 
print(prob.solution.opt_val) # Incorrectly prints 5.8
assert np.isclose(prob.solution.opt_val, solution)
```
Looks like it's due to two issues:
1. In the DGP canon functions dict, the key for pnorms is the pnorm function wrapper, not the Pnorm class. 
2. Should be multiplication instead of exponentiation during the canonicalization process. 
$\ln\(||x||_p\) = \ln\(\(\sum |x_i|^p \)^\frac{1}{p} \) = \frac{1}{p} \ln \(\sum |x_i|^p\)$ 
Since we take the logs of all the leaves first and pass that in as args, …
=> P-norm issue with DGP problems

cvxpy/reductions/solvers/conic_solvers/mosek_conif.py, cvxpy/tests/test_conic_solvers.py, doc/source/tutorial/advanced/index.rst, examples/notebooks/WWW/Gini Portfolio.ipynb, examples/notebooks/WWW/Kurtosis Portfolio.ipynb
Tries to make Mosek parameters systematic. See https://github.com/cvxpy/cvxpy/issues/2023
Adds proper handling of the case where both parameter name and value are strings. Deprecates the use of constants from the Python API. Adapts the documentation and test accordingly.
Documentation mentions https://docs.mosek.com/latest/faq/faq.html#cvxpy  That link will be separately updated in the same style next time new Mosek docs are uploaded.
=> Cleanup in MOSEK parameters setting

cvxpy/constraints/finite_set.py, cvxpy/reductions/dgp2dcp/canonicalizers/__init__.py, cvxpy/reductions/dgp2dcp/canonicalizers/finite_set_canon.py, cvxpy/tests/test_valinvec2mixedint.py
Adds support for mixed-integer geometric programs, via the FiniteSet constraint.
Issue link (if applicable): #1590
@adishavit
The canonicalization is straightforward. I am not allowing the values of the finite set to be parameterized right now, because ``is_pos`` is only supported for leafs but it's needed here for more complex expressions, since theoretically the set values could be something like param1 + param2. I could hack around this though if the functionality is desired.
=> MI DGP support

cvxpy/reductions/cone2cone/affine2direct.py, cvxpy/tests/test_conic_solvers.py
There was a bug in the canonicalization chain with mosek that failed when both power cones and exponential cones were present.
Issue link (if applicable): #2042
=> Fix Mosek power cone

doc/source/examples/derivatives/fundamentals.rst, examples/notebooks/derivatives/fundamentals.ipynb
I found a small typo in the documentation. 
It is in the "derivative fundamental" sub-section. 
"sensitvity" -> "sensitivity"
=> fixing typo in documentation

cvxpy/atoms/__init__.py, cvxpy/atoms/affine/conv.py, cvxpy/tests/test_atoms.py, cvxpy/tests/test_convolution.py, doc/source/tutorial/functions/index.rst
The ``conv`` operator was extremely broken, and gave incorrect shape information. This PR fixes bugs in ``conv``, deprecates ``conv``, and adds a ``convolve`` atom that matches np.convolve.
@PTNobel
=> Fix conv and add convolve

cvxpy/problems/problem.py, cvxpy/tests/test_problem.py, doc/source/api_reference/cvxpy.problems.rst
Exposes the `compilation_time` attribute as a property of the `Problem`. I wanted to be able to access this programmatically in a project I was working on.
=> Add compilation time property

cvxpy/tests/test_constant.py, cvxpy/utilities/linalg.py
Adding a custom error message to `ArpackNoConvergence` during PSD check.
Issue link (if applicable):  #1995 
cc: @PTNobel
=> Improved psd check message

cvxpy/atoms/affine/reshape.py, cvxpy/tests/test_atoms.py
Allows replacing one dimension by -1 in reshape.
Issue link (if applicable): #1723
=> Allow -1 in reshape

.github/workflows/build.yml, pyproject.toml
Adding wheel build for `aarch64` to the CI.
Issue link (if applicable): #2048 
Tested the build successfully. Results can be found [here](https://github.com/cvxpy/cvxpy/actions/runs/4270415474) (bottom of page).
=> [CI] aarch64 wheels

cvxpy/constraints/constraint.py, cvxpy/tests/test_copy.py, cvxpy/tests/test_problem.py, cvxpy/utilities/canonical.py, doc/source/faq/index.rst
Resumes #2014. This PR can be used to work on the new semantics, and we can still decide which version to backport to 1.1, 1.2, 1.3, respectively. 
Implementation based on a suggestion by @michael-123123.
TODO: Documentation for new behaviour.
=> New deepcopy semantics

cvxpy/atoms/affine/binary_operators.py, cvxpy/tests/test_expressions.py
Right now the dimensions of quad_form are usually (1, 1). This is not right at all, and leads to errors such as #2065. However changing the dimension of quad_form probably needs to wait for the 1.4 release. This is a hotfix that resolves #2065 more narrowly.
=> Fix issue with matrix multiplication involving quad

cvxpy/reductions/solvers/conic_solvers/mosek_conif.py, cvxpy/tests/test_atoms.py
The current implementation casts PSD constraints to a dense array before passing them to mosek. This PR keeps the sparsity.
Issue link (if applicable):  #2051 
For reference, here is the script from the to reproduce the issue:
```py
import cvxpy
n = 130
np.random.seed(43)
Q = np.random.normal(loc=0, scale=1, size=(n, n))
X = cvxpy.Variable((n, n), symmetric=True)
constraints = [X[i, i] == 1 for i in range(n)] + [X >> 0]
objective = cvxpy.Minimize(cvxpy.trace(Q @ X))
problem = cvxpy.Problem(objective, constraints)
problem.get_problem_data(verbose=True, solver=cvxpy.MOSEK)
```
=> Mosek Interface: Keep sparsity for PSD constraints

cvxpy/tests/test_expressions.py, cvxpy/utilities/key_utils.py
Per the chat, we decided that `cp.Variable(4)[2.5]` should be an error. This is my first cut at making it one.
I wasn't exactly sure where to put the source of the error or how to structure it. My preference would be to whitelist certain types ala NumPy and validate them that way, but I figured I'd start by banning floats since that occurs the most (in code like `x[5/2]`).
It is worth noting we already have this error for arrays of floats:
```python
ipdb> cp.Variable(5)[2:][np.array([1.5])]
*** IndexError: arrays used as indices must be of integer (or boolean) type
```
Let me know if we should move it and how many unit tests this needs!
=> Initial cut at adding error on raw float keys and tuples of floats

.github/workflows/build.yml
The PYPI_BASE_PASSWORD environment variable was missing from the cvxpy_base build environment.
=> Fix cvxpy base pypi deployment

cvxpy/atoms/quad_form.py, cvxpy/tests/test_expressions.py
I adjusted the returned shape for 1-dimensional quadratic form and adjusted test_matmul_scalars. 
Found issue on this page: https://github.com/cvxpy/cvxpy/issues/2070
=> Change shape quadratic form 

doc/source/api_reference/cvxpy.atoms.affine.rst
Currently in the function scalar_product in https://www.cvxpy.org/api_reference/cvxpy.atoms.affine.html#scalar-product is mentioned as a class although, it is implemented as a function in binary_operators.py
=> Change scalar_product to function in api

doc/source/tutorial/advanced/index.rst
SCIPY documentation update: bounds should not be specified within scipy_options and should instead be specified through CVXPY.
=> SCIPY documentation update

cvxpy/reductions/solvers/conic_solvers/scipy_conif.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_conic_solvers.py
When using SciPy, if the solver reaches it's set time limit, a `SolverError` is raised. This change makes it so these instances are instead reported as `OPTIMAL_INACCURATE`. I think this behavior is more consistent with other solvers - this is at least how GLPK works currently.
I haven't added a unit test for this. Let me know if this seems necessary.
=> fix: scipy time limit raises SolverError

cvxpy/expressions/expression.py, cvxpy/tests/test_errors.py
This PR changes the text of the error that occurs when people run `builtins.abs(cp.Variable())` to explain what is wrong.
Since the text of error messages is not part of our backward compatibility guarantees, but their type is, this is backwards compatible.
=> Adds an error message on `builtins.abs(cp.Variable())`

cvxpy/reductions/solvers/conic_solvers/scip_conif.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_conic_solvers.py
I added conditions to check if timelimit for SCIP solver is reached and no solutions (feasible and/or optimal) are generated. If those conditions are met, solution status is set to SOLVER_ERROR. I also added the case if timelimit is reached and a non-optimal and feasible solution is generated to set OPTIMAL_INACCURATE. Additionally, I added a unit test to check for the SOLVER_ERROR case.
I found the issue here: https://github.com/cvxpy/cvxpy/issues/2050
=> Fix scip timelimit no solution

cvxpy/atoms/affine/diag.py, cvxpy/cvxcore/src/LinOp.hpp, cvxpy/cvxcore/src/LinOpOperations.cpp, cvxpy/lin_ops/canon_backend.py, cvxpy/lin_ops/lin_op.py, cvxpy/lin_ops/lin_utils.py, cvxpy/tests/test_atoms.py, cvxpy/tests/test_problem.py, cvxpy/tests/test_python_backends.py
Added an offset parameter to the diag atom. Now it is possible to extract an off-diagonal vector from a square matrix and make a square matrix with a vector on the off-diagonal. 
I had some questions regarding the `graph_implementation` method of the `diag_vec` and `diag_mat` classes. It is yet unclear to me what the graph_implementation is doing and I are not sure where I should add the offset parameter. Currently the code will fail if `diag_offset != 0`.
I was also wondering if I should add assert statements to ensure that the value of `diag_offset` is no more than the dimension of the input matrix or vector and would like to know where the best place to add it is.   
Issue link (if applicable): #808
=> Added the diag_offset parameter to the diag atom

cvxpy/reductions/solvers/conic_solvers/scipy_conif.py, cvxpy/tests/test_conic_solvers.py
When using scipy to solve a MIP, this change makes the solution's relative mip gap available in `Problem.solver_stats.extra_stats["mip_gap"]`
=> feat: retrieve mip gap from SCIPY solution

cvxpy/__init__.py, cvxpy/tests/test_cone2cone.py, cvxpy/tests/test_dqcp.py
Reductions are stated to not be in the public API
(https://www.cvxpy.org/api_reference/cvxpy.reductions.html#disclaimer, https://github.com/cvxpy/cvxpy/pull/2104#issuecomment-1509886345), but they are imported in the top-level `__init__.py`.
This change removes that import.
=> fix: remove reductions import in top-level __init__.py

cvxpy/reductions/solvers/conic_solvers/scipy_conif.py, cvxpy/tests/test_conic_solvers.py
This reverts commit 6eb5466ab0a90be20d74839dc993d489b96dcd19.
The MIP gap is not available with the interface we are using. Consequently the added tests fail. We didn't notice the regression because of unrelated failures in the CI.
=> Revert "feat: retrieve mip gap from SCIPY solution"

setup.py
`setup_requires` is outdated; the build dependencies are declared in `pyproject.toml`.
Also `setuptools` should not appear in `install_requires`; these are the runtime dependencies.
=> `setup.py`: Remove `setup_requires`, remove setuptools from `install_requires'

cvxpy/expressions/constants/constant.py, cvxpy/expressions/expression.py, cvxpy/expressions/variable.py, cvxpy/settings.py, cvxpy/tests/test_constant.py, cvxpy/tests/test_expressions.py
I made changes to three files:
<b>expression.py</b>: here I changed the expression toString method, by using [numpy.array2string](https://numpy.org/doc/stable/reference/generated/numpy.array2string.html) we are able to take advantage of formatting (floating point numbers with 2 decimals), and hiding additional elements (using edgeitems=2).
The last part of the if statement was added to bypass some tests that weren't passing for test_transpose.
```
self.value is not None and "\n" in name
```
This ensures that we only use numpy.array2string on expressions whose name are arrays. (For example, x.T.T wouldn't be affected as it's name doesn't contain a newline).
<b>variable.py</b>: expanded variable representation by including the variable name in addition to the variable shape. …
=> improve string representation, especially shortening expression.tostring

cvxpy/atoms/__init__.py
This resolves GitHub Issue #2092.
No new unit tests should be needed for this change. It's the kind of error that could happen with any atom whenever it's first contributed (although it's an unusual mistake and this is the first I've seen something like it).
=> Correct categorization of ``tr_inv`` atom.

cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
Clarabel would crash in the try/except block when using an old version.
=> Stop cvxpy from crashing when using an old version of clarabel

cvxpy/tests/test_conic_solvers.py
Trying to fix the CI after merging #2117.
Under windows, the test gives `cp.optimal` instead of `cp.optimal_inaccuracte`.
Looks like @rileyjmurray called it?
https://github.com/cvxpy/cvxpy/pull/2117#issuecomment-1530464403
=> Follow-up Mosek accept unknown

cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py, cvxpy/reductions/solvers/conic_solvers/mosek_conif.py, cvxpy/tests/test_conic_solvers.py
The Mosek simplex and dual simplex solver cannot be used right now due to a simple interface bug, fixed here. I also made the Clarabel interface a bit more robust because it was failing on my old Clarabel version.
=> Fix bug with calling Mosek simplex solver

cvxpy/problems/problem.py, cvxpy/tests/test_problem.py
I wanted to add a human-readable string representation to `SolverStats`. Using a `dataclass`, this comes for free.
The output for `extra_stats` depends on the solver. For example, ECOS and SCS give quite detailed information, other solvers point to the solution object or provide no further information.  If you think it is too unwieldy, we can remove `extra_stats` from the string. 
Before:
After:
=> Human-readable SolverStats

cvxpy/atoms/length.py, cvxpy/tests/test_dqcp.py
`cp.length` is nondecreasing for nonnegative arguments, and nonincreasing for nonpositive arguments.
=> Improves monotonicity logic for cp.length

doc/source/conf.py
The github fork banner has not been showing up properly for a while. This PR removes the banner.
I ran ``make html`` with this change and verified the banner is removed.
=> Remove github banner

.github/workflows/pr_benchmarks.yml
Currently, all PRs are benchmarked against `master`, which does not make sense for release PRs like #2151.
=> [CI] PR benchmark against base branch

cvxpy/constraints/nonpos.py, cvxpy/expressions/expression.py, cvxpy/reductions/complex2real/canonicalizers/__init__.py, cvxpy/reductions/complex2real/canonicalizers/inequality_canon.py, cvxpy/reductions/complex2real/complex2real.py, cvxpy/reductions/dcp2cone/canonicalizers/von_neumann_entr_canon.py, cvxpy/reductions/qp2quad_form/qp_matrix_stuffing.py, cvxpy/reductions/solvers/qp_solvers/qp_solver.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_constraints.py, cvxpy/tests/test_problem.py
I recently opened a GitHub Discussion about awkwardness with the NonPos constraint class: https://github.com/cvxpy/cvxpy/discussions/2153. This PR offers the solution where we deprecate NonPos in favor of NonNeg. It includes a deprecation warning, updates to tests, and changes to canonicalization code paths. NonPos constraints are still supported, but we never construct those constraints outside of our testing code.
=> Deprecate NonPos in favor of NonNeg

cvxpy/atoms/perspective.py, cvxpy/tests/test_perspective.py
**Summary:** Implementing support for s=0 in perspective functions by allowing users to pass in a recession function.
Currently, for the perspective transform $f_p$ of a function $f$, defined as $f_p(s, x) = sf(x/s)$, the [CVXPY list of atomic functions](https://www.cvxpy.org/tutorial/functions/index.html#:~:text=None-,perspective(f(x)%2Cs),-sf( ) says that it supports any $s$ where $s \geq 0$. However, actual support for the case where $s=0$ is not implemented, and would instead trigger an assertion error. One use case for motivating support for $s=0$ is when using perspective transforms in MILP problems with boolean $s$ - for example, a convex formulation of solving shortest paths over mixed discrete-continuous graphs [1].
The problem with the $s=0$ case is that the general perspective …
=> Support for s=0 in perspective functions

cvxpy/tests/test_scalarize.py, cvxpy/transforms/scalarize.py
The `scalarize` was untested and contained a small bug.
Here are some visuals for the tests :)
=> Fixes bug and adds tests for scalarize transform

examples/flows/incidence_matrix.py
Fixed bug in examples/flows/incidence_matrix described in #1609.  Basically, there were 3 bugs when running the example:
1. When loading a file using pickle the following error was raised: TypeError: a bytes-like object is required, not 'str'" 
2. When stacking variables  the following error was raised: "ValueError: All the input dimensions except for axis 0 must match exactly."
3. When subtracting the variable "flows" and the cvxopt.matrix "c"  the following error was raised:  "ValueError: Cannot broadcast dimensions  (378,) (378, 1)"
Moreover, I removed the dependency on cvxopt, and fixed minor style issues.
Issue link (if applicable): #1609
=> Fixed bug in incidence_matrix example

examples/flows/commodity_flow.py, examples/flows/create_graph.py, examples/flows/incidence_matrix.py, examples/flows/leaky_edges.py, examples/flows/max_flow.py
Fixed bugs, style issues, and removed the dependency on cvxopt in multiple flow examples (commodity_flow, create_graph, max_flow,  and leaky_edges).  This includes the changes suggested by [choltz95](https://github.com/choltz95) and [mmusallam19](https://github.com/mmusallam19) in #1926.
Issue link (if applicable): #1926
=> Fixed bugs in multiple flow examples

cvxpy/interface/scipy_wrapper.py
We automatically detect when `scipy_wrapper.py` actually does something and then raises a warning telling people to contact us. The hope is we will hear if there are cases not covered by our test suite that require scipy_wrapper to do something.
This might have a slight performance regression in cases where SciPy does expensive compute that we throw away, but those cases will result in warnings so we should hear about them and can correct them.
=> Deprecates `scipy_wrapper.py`

cvxpy/tests/test_quad_form.py
Following the discussion in https://github.com/cvxpy/cvxpy/discussions/2166#discussioncomment-6312195, I have created a new action that checks pre-releases once a week. 
Interestingly, it immediately caught a (small) test failure we would have encountered after the OSQP 1.0 release.
https://github.com/cvxpy/actions/actions/runs/5558476612/jobs/10153621071
This PR update the test to allow both versions of the error message.
=> Update test for OSQP 1

cvxpy/constraints/power.py, cvxpy/tests/test_constraints.py
Fixes small issue with `PowCone3D` when passing in naked floats as `alpha`.
Issue link (if applicable): [#2191](https://github.com/cvxpy/cvxpy/issues/2191)
=> `PowCone3D` fix

continuous_integration/install_dependencies.sh, cvxpy/reductions/solvers/conic_solvers/glop_conif.py, cvxpy/reductions/solvers/conic_solvers/pdlp_conif.py, setup.cfg
Updated glop and pdlp interfaces to work with or-tools 9.5 and 9.6.
Drops support for or-tools 9.3.
I tested both 9.5 and 9.6 locally.
Closes #2135
Closes #2052
Closes #2019
=> Update to support or-tools 9.5 and 9.6

cvxpy/expressions/constants/callback_param.py, cvxpy/tests/test_dpp.py, doc/source/api_reference/cvxpy.expressions.rst
Adds test and API reference for `CallbackParam`. Since it already is in the `cvxpy` namespace, we cannot make a breaking change to the class (e.g., switching from a callable to an expression).
Issue link (if applicable): #2211
=> CallbackParam Update

cvxpy/__init__.py, cvxpy/constraints/__init__.py, cvxpy/constraints/cones.py, cvxpy/constraints/exponential.py, cvxpy/constraints/power.py, cvxpy/constraints/psd.py, cvxpy/constraints/second_order.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_KKT.py
This PR introduces the `dual_cone` methods for every `Constraint` class (which support dual variable recovery, which is all of them, with the exception of `PowConeND` and `OpRelEntrConeQuad`). A complementary `dual_violation` method if also implemented for ease in actually performing the feasibility checks.
These methods are used to update the existing `check_dual_domains` method in `solver_test_helpers.py` --- all the existing tests in `test_KKT.py` remain the same as they were when introduced as part of the `check_stationary_lagrangian` PR, and they all pass.
Again, I haven't added documentation for this method yet since it just lives within the `SolverTestHelper` class as of now.
=> Adding functionality to cvxpy/tests: verifying dual feasibility for `Constraint` classes as part of the KKT conditions

.github/workflows/benchmarks.yml
The benchmark deploy step failed because of a missing secret: https://github.com/cvxpy/cvxpy/actions/runs/6027612733/job/16353179443
The secret allows to deploy to the `gh-pages` branch of `cvxpy/benchmarks` from `cvxpy/cvxpy`. These secrets must be passed to the reusable workflow explicitly.
=> [CI] Benchmark workflow needs to inherit secrets.

cvxpy/atoms/errormsg.py, cvxpy/atoms/geo_mean.py, cvxpy/expressions/leaf.py, cvxpy/tests/test_atoms.py
Many of my students wrote `geo_mean(x, y)` when they needed to write `geo_mean(hstack([x, y]))`. They would get a type error about strict inequalities not being allowed, and be stuck on how to fix the issue. This was disappointing because we encouraged them to pay a lot of attention to error messages, so having a bad error message undermined our ability to make this point.
In order, to guide users to the correct use of the atom, I added an error message when the second argument is $p$. Further, I went through the atoms table and did not find any other atoms who are both sensibly used as a multiple argument function (I think norm taking a vector input is obvious enough there's no need to warn on it) and had a second argument which wasn't what someone might naively think. If I missed any …
=> Adds a clear error message to address a common student misuse of geo_mean

cvxpy/atoms/sum_largest.py, cvxpy/tests/test_atoms.py
sum_largest and sum_smallest are not marked as piece-wise linear, which makes it so cvxpy thinks they can't be canonicalized to a QP.
=> Mark sum_largest and sum_smallest as piece-wise linear

cvxpy/problems/problem.py, cvxpy/reductions/solvers/solving_chain.py, cvxpy/tests/test_problem.py
This PR adds a FutureWarning when ECOS is called by default, since Clarabel will become the new default LP/SOCP solver in CVXPY 1.5.
=> Add deprecation warning for ECOS

cvxpy/atoms/__init__.py, cvxpy/atoms/affine/upper_tri.py, cvxpy/atoms/affine/wraps.py, cvxpy/atoms/norm.py, cvxpy/atoms/ptp.py, cvxpy/atoms/stats.py, cvxpy/expressions/expression.py, cvxpy/tests/test_atoms.py, cvxpy/tests/test_expression_methods.py, cvxpy/tests/test_expressions.py, doc/source/tutorial/functions/index.rst
Closes #2237 by cloning much of the [NumPy ndarray API](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).
Supersedes and closes #2150 
Notes on specific methods:
* I skipped `np.diagonal` because the RO API in NumPy made me feel that maybe we don't want to emulate it, and we don't support the optional arguments in diagonal yet
* `.flatten` uses the opposite ordering as numpy, but is consistent with our default
* `.max`, `.min`, `.prod` requires that `keepdims` be a keyword argument because NumPy has `out` as its second arg, and so this makes our API compatible with NumPy
* `.mean`, `.ptp`, `.std`, `.var` do not have a corresponding `cp.mean`, `cp.ptp`, `cp.std`, `cp.var` respectively
* I skipped .ravel, .repeat, .swapaxes, .take for no particular reason other than they …
=> New atoms and adds NumPy API methods

.github/workflows/build.yml, README.md, continuous_integration/install_dependencies.sh, pyproject.toml, setup.py, sonar-project.properties
To ensure cvxpy is usable with the newly released 3.12, we planned to ship cvxpy with a 3.12 wheel right away. 
I tested it locally and it works. Currently, our solvers do not have prebuilds for 3.12, but I managed to install all of them locally, except for SCS. I think the build would not go through if this was the case on the CI as well.
This PR also drops Python 3.7 support, as it has reached EOL (https://devguide.python.org/versions/).
=> Prepare for 3.12 / Drop 3.7

continuous_integration/install_dependencies.sh, cvxpy/reductions/solvers/conic_solvers/glop_conif.py, cvxpy/reductions/solvers/conic_solvers/pdlp_conif.py, setup.cfg
Updates GLOP and PDLP to support or-tools 9.7. Drops support for or-tools 9.4.
I tested the code locally on 9.6 and 9.7.
=> Support or-tools 9.7; drop 9.4

cvxpy/tests/test_conic_solvers.py
This time based test failed on some systems (e.g., here: https://github.com/conda-forge/cvxpy-feedstock/pull/80).
I add 10x the time and reduce the scope of the tests to make sure it does not raise an error.
cc: @h-vetinari
=> Fix / Partially remove flaky SciPy test

doc/source/api_reference/cvxpy.atoms.affine.rst, doc/source/api_reference/cvxpy.atoms.other_atoms.rst
Adds API reference for atoms introduced in #2238.
Also contains two unrelated fixes for `norm2` and `diff_pos`.
I have opted for a fully qualified declaration. 
Updates:
=> Docs new atmos api reference

cvxpy/problems/problem.py, cvxpy/tests/test_problem.py
When solving repeatedly with a different value of `use_quad_obj`, the compilation cache should be invalidated since the standard form changes.
=> Re-compile if quadratic objective usage changed

continuous_integration/install_dependencies.sh, cvxpy/reductions/solvers/conic_solvers/pdlp_conif.py, setup.cfg
Switches the PDLP interface to use `ortools.pdlp.python.pdlp` instead of `ortools.linear_solver.python.model_builder_helper`. This interface should be much faster because it passes the sparse constraint matrix directly via pybind11; no need to loop through the coefficients in python.
This PR bumps the minimum version of or-tools to 9.7. The PDLP interface has changed across versions, and it would be a pain to manage lots of version branches in the interface.
You may consider tagging a cvxpy release with https://github.com/cvxpy/cvxpy/pull/2251 included before merging this PR.
FYI @mizux @lperron @dapplegate
=> Major update of PDLP interface

cvxpy/reductions/solvers/conic_solvers/scip_conif.py
Makes it so that the SCIP solver will still return a solution if it hits the maximum number of iterations (consistent with timeout behavior).
Issue link: https://github.com/cvxpy/cvxpy/issues/2278
=> SCIP return solution if [total]nodelimit hit

.github/workflows/build.yml, continuous_integration/install_dependencies.sh, pyproject.toml
Various updates to the setup and build scripts:
- Use "oldest-supported-numpy". 
- Fix cvxpy-base build.
- Remove clarabel as an *optional* dependency. (Still kept as a *required* dependency.)
Issue link (if applicable): #2287
=> Test SCS Python 3.8 fix

cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py, cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
The CVXPY gurobi interface has special keyword arguments that are used in the interface but not gurobi itself. These were raising errors when passed on to gurobi.
=> Fix gurobi interface issues

CONTRIBUTING.md
Per a conversation [here](https://discord.com/channels/845323972962549790/1183448452357705749/1183448452357705749) with @SteveDiamond, I am opening a PR to update the CVX documentation to reflect usage of `ruff` instead of `flake8` and `isort`.
This change ensures the *Code Style* section in `CONTRIBUTING.md` matches the web docs @ https://www.cvxpy.org/contributing/index.html
=> [Docs] update contributing docs to reflect usage of ruff over flake8/isort

cvxpy/reductions/solvers/conic_solvers/scip_conif.py
Minor change for SCIP wrapper that reduces some O(n) lookups to O(1). The lookups get called as many times as there are variables by get_variable_type (in scip_conif.py). 
(Anecdotally, this reduced my create_variables() time from 10 minutes to 0.5 seconds.)
=> change some O(n) lookups in scip_conif.py to O(1)

cvxpy/reductions/solvers/conic_solvers/conic_solver.py
Compiling a "highly" parameterized linear program seems to hit a slow path involving a number of scipy sparse matrix multiplication operations within the ConicSolver reduction. By avoiding multiplication altogether for the trivial cases involving identity and negative identity operations, the initial compilation path for a parameterized linear program can be sped up by orders of magnitude.
As an example, for a relatively sparse problem with ~7k variables, ~20k constraints and ~7k parameters (all on the rhs of constraints), with this change the initial cvxpy compile time goes from ~140s to 0.4s (**350x speedup**).
pr_benchmark comments:
```
Benchmarks that have improved:
before           after         ratio
[8d1c56d4]       [987310df]
-         2.65±0s          2.40±0s     0.91 …
```
=> avoid sparse identity matrix multiply in conic_solver.py

cvxpy/expressions/expression.py, cvxpy/tests/test_expressions.py
This PR is in response to a feature request outlined in [Issue 1540](https://github.com/cvxpy/cvxpy/issues/1540). In summary, I have created a `curvatures` property which will return a list of all known curvatures of an expression. 
Open to suggestions on next steps - please see the issue link to discuss if further steps should be taken (if any).
=> Issue 1540 add expression curvatures property to return all curvatures

cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
As discussed on Discord this PR restores compatibility with Mosek 9, currently broken by the appearance of a symbol from Mosek >= 10 only.
@rileyjmurray
=> Restore Mosek 9 compatibility

cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
As discussed on Discord, this PR slightly modernizes the Mosek interface, getting rid of the ``env`` object (Mosek environment), which was only dragged around through the code, and instead only creating a Mosek task ``task``. A default global environment will be created internally by the library, once for the whole process. See https://docs.mosek.com/latest/pythonapi/environment-and-task.html for more info.
In practice this change will only make a difference for users of commercial floating licenses. They will have one license checkout per process, instead of per solve, ie. the user experience should only improve, judging from some communication we had with users in the past. In any case, should this ever come up as a problem, this is a business issue Mosek support takes responsibility …
=> Better integration with Mosek>=10; remove Mosek<=9 code

cvxpy/reductions/solvers/conic_solvers/scipy_conif.py, cvxpy/tests/test_conic_solvers.py
I have added LP/MILP statistics information when solving problems with the HiGHS solver. It is a really minor change. The stats are different for continuous and discrete problems so I added two different unit tests.
(By the way, I did all of this in 5 minutes with codespaces. It was amazing!)
=> Added HIGHS solver stats (LP/MILP)

pyproject.toml, requirements.txt
Removes pybind11 runtime dependency from `requirements.txt` and `pyproject.toml`.
Issue link (if applicable): resolves #2330
=> Removes pybind11 runtime dependency

cvxpy/reductions/solvers/conic_solvers/nag_conif.py, cvxpy/tests/test_conic_solvers.py
We have modified the wrapper for the NAG solver to allow quadratic objective information to be passed directly to the solver (without cone transformation). This was done to improve the performance.
Benchmark without changes:
================================================= test session starts =================================================
platform win32 -- Python 3.10.8, pytest-7.4.4, pluggy-1.4.0
rootdir: C:\Users\charlotte.silvester\nag\cvxpy
configfile: pyproject.toml
collected 12 items
cvxpy\tests\test_benchmarks.py ss-------------------------------------------------------------------------------
Compilation
-------------------------------------------------------------------------------
(CVXPY) Jan 31 12:52:42 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jan 31 12:52:42 PM: …
=> Adding quadratic objective support to NAG solver wrapper

cvxpy/tests/test_qp_solvers.py
Since this affected only a single test, I hardcoded the example. 
Deviation in the output because I rounded the data array to two digits.
Issue link (if applicable): resolves #2341
=> Fix QP tests

.github/workflows/build.yml
Looks like build is failing on master.
The cibuildwheel [changelog](https://cibuildwheel.readthedocs.io/en/stable/changelog/#v2165) suggests there was an incompatibility with the new Windows runners.
=> [CI] Update cibuildwheel

cvxpy/reductions/solvers/conic_solvers/sdpa_conif.py
The solver will accept `numpy.ndarray` as well as one of the sparse array formats (e.g. `csr_array` or `csc_array`) in `scipy.sparse` for each of `A`, `b` and `c`.
=> Address deprecation warning

cvxpy/reductions/cone2cone/soc2psd.py, cvxpy/reductions/solvers/conic_solvers/sdpa_conif.py, cvxpy/tests/solver_test_helpers.py, pyproject.toml
As mentioned in #2270, there are several invalid escape sequences in docstrings that can cause issues in newer Python versions. In particular, it (somehow only sometimes) can make the package raise exceptions on import. This PR adds a ruff rule to explicitly disallow these invalid sequences and applies the fixes from `ruff check --fix`.
Issue link: Fixes #2270
=> Fix invalid escape sequences in docstrings

doc/source/index.rst
This PR attempts to fix the capitalization of CVXPY in search engine results.
Google shows `CVXPy` as the site name, which is the wrong capitalization:
This PR follows the [Google developers instructions](https://developers.google.com/search/docs/appearance/site-names#how-site-names-in-google-search-are-created) to add structured data to the page.
Below is the section of the page source after the change.
=> Fixes Capitalization in Search Engine Results

cvxpy/problems/problem.py, cvxpy/tests/test_problem.py, doc/source/tutorial/solvers/index.rst
adds a solver-only verbose switch as kwarg.
the old behaviour is kept if the user does not provide `solver_verbose` as a kwarg.
https://github.com/cvxpy/cvxpy/issues/2353
=> add solver-only verbose switch as kwarg

cvxpy/atoms/quad_form.py, cvxpy/cvxcore/python/__init__.py, cvxpy/cvxcore/python/canonInterface.py, cvxpy/cvxcore/python/cppbackend.py, cvxpy/tests/test_linalg_utils.py, cvxpy/utilities/linalg.py
We recently discussed the possibility to run CVXPY within [Pyodide](https://pyodide.org). 
Pure Python wheels are directly supported, and since we a backend that only relies on SciPy, which is already supported by Pyodide, this should be fairly easy.
This PR moves all calls to the C++ backend into a separate file and makes the Eigen-based sparse Cholesky optional
=> Allow pure Python builds

cvxpy/atoms/__init__.py, cvxpy/atoms/affine/binary_operators.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_atoms.py, doc/source/api_reference/cvxpy.atoms.affine.rst
This PR attempts to introduce cp.vdot as a replacement for cp.scalar_product. 
In the issue below, it was suggested to not deprecate cp.scalar_product, but instead remove it from the documentation.
When running ``grep -ir "scalar_product"`` I saw that there were a lot of instances under ``cvxcore``, I am not sure if the code there also needs to be updated.
Issue link (if applicable): #2336
=> Replace cp.scalar_product with cp.vdot

cvxpy/reductions/solvers/defines.py, cvxpy/reductions/solvers/solving_chain.py
Adds the new warning for when ECOS is specified as a solver and makes Clarabel preferred, unless it is an SDP, then prefers SCS.
I still need to update the tests...
=> Next step of the ECOS deprecation

cvxpy/reductions/solvers/solving_chain.py, cvxpy/tests/test_convolution.py, cvxpy/tests/test_kron_canon.py
I saw that the summary of the tests had many warnings. This PR attempts to clean up a small subset of those warnings.
I was wondering if we should change all occurrences of using ECOS to CLARABEL in the tests, now that we are planning to change default solvers? 
=> removing some test warnings

.github/workflows/build.yml
We just updated `download-artifact` in #2394, but I missed that this is a breaking change that requires updating the `upload-artefact` action as well.
=> [CI] bump upload-artifact

cvxpy/lin_ops/canon_backend.py, cvxpy/tests/test_coeff_extractor.py, cvxpy/tests/test_python_backends.py, cvxpy/utilities/coeff_extractor.py
This PR should eventually contain the fix for #2402. 
Current status:
Issue link (if applicable): #2402
=> [Bug] Parametrized quad form broken when values are zero

cvxpy/reductions/solvers/conic_solvers/copt_conif.py, cvxpy/reductions/solvers/qp_solvers/copt_qpif.py, cvxpy/tests/test_copt_write.py
Add option `save_file` to enable writing out problem loaded into COPT to file.
=> Add option save_file

cvxpy/atoms/affine/binary_operators.py, cvxpy/atoms/affine/sum.py, cvxpy/atoms/norm_inf.py, cvxpy/atoms/prod.py, cvxpy/interface/numpy_interface/ndarray_interface.py, cvxpy/lin_ops/tree_mat.py, cvxpy/tests/test_constant.py, cvxpy/utilities/coeff_extractor.py
Fix the `.A` property of sparse matrices which is deprecated and will be removed in SciPy 1.14.0.
Issue link (if applicable): #2408
=> Fix issue #2408: `value.A` is deprecated and will be removed in scipy 1.14.0

cvxpy/reductions/eliminate_pwl/canonicalizers/maximum_canon.py, cvxpy/tests/test_canon_sign.py
This change fixes #2374, preserving the sign of arguments to `cp.minimum` and `cp.maximum` during canonicalization. 
Specific review desired on breadth / specificity / quality / naming of new unittest `test_canon_sign.py`; is it too narrow of a test? Other edge cases that ought to be included? 
Default benchmarks do appear to be somewhat slower. Is this acceptable? Do additional benchmarks need to be written and/or should iteration counts be increased to control somewhat for noise?
Issue link: #2374 
<details>
<summary>All tests are passing</summary>
```
cvxpy on  master via 🐍 v3.12.2 via 🅒 cvxdev 
❯ pytest                                  
=========================================== test session starts ===========================================
platform linux -- Python 3.12.2, …
```
=> Preserve expression sign in canonicalization of minimum and maximum

cvxpy/expressions/constants/constant.py, cvxpy/tests/test_constant.py
This addresses the discrepancy from the NumPy behaviour mentioned in #2317 by:
- emitting a warning
- adding a test case that makes sure any change in behaviour would be noticed
Issue link (if applicable): closes #2317
=> Adds warning for constants from nested lists

cvxpy/reductions/solvers/conic_solvers/xpress_conif.py
From the 9.4 release notes:
> Python:
New Python API to create variables that are linked to the problem, such that when their properties are modified, the Optimizer problem is updated. It is advised to update existing models to use the new API:
Instead of calling xpress.var(properties) and then adding the resulting variable to the problem with problem.addVariable(myvar), call problem.addVariable(properties) directly.
Instead of calling xpress.vars(indices, properties) and then adding the resulting dictionary or array of variables to the problem with problem.addVariable(myvars), call problem.addVariables(indices, properties) directly.
Instead of calling xpress.sos(properties) and then adding the resulting SOS to the problem with problem.addSOS(mysos), call problem.addSOS(properties) …
=> Fixes XPRESS interface

cvxpy/atoms/affine/conv.py, cvxpy/lin_ops/canon_backend.py, cvxpy/tests/test_atoms.py
Fixes bug with convolve where the input is a parameter by disabling DPP for convolve. This is the same approach taken with kron.
Issue link (if applicable): #2218
=> Fix convolve bug

cvxpy/atoms/norm_nuc.py, cvxpy/tests/test_grad.py
Fix nuclear norm gradient for non-square inputs
Issue link (if applicable): #2364
=> Fix nuclear norm gradient for non-square inputs

cvxpy/atoms/affine/add_expr.py, cvxpy/tests/test_atoms.py
I memory-profiled the script from #2385
Issue link (if applicable): Closes #2385
```py
x = [cp.Variable() for i in range(20000)]
expr = cp.sum(x)
```
I found the place that results in the quadratic memory consumption, changed in this PR.
The memory consumption is quadratic because we keep track of the (linearly) growing list of `arg_groups` of every subexpression.
It turns out that the only use of `arg_groups` was to make the copy more efficient, passing the groups instead of the (expanded) args. Turns out a neat trick is to simply pass `[self]` as args in the copy function, making it even more efficient than the original speedup.
Before:
```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
3  111.594 MiB  111.594 …
```
=> Reduce memory consumption for sum(list)

cvxpy/reductions/eliminate_pwl/canonicalizers/min_canon.py, cvxpy/tests/test_atoms.py
Cherry-picked @allenlawrence94's commit from #2419 so we can move forward with the 1.5 release.
Added @SteveDiamond's test case.
The `min` atom ignores the `keepdims` flag.
=> Fix keep dims for min atom

cvxpy/expressions/expression.py, cvxpy/tests/test_errors.py
Implementing @rileyjmurray's suggestion from #2282 that we should error when someone attempts inplace mutation of a CVXPY expression.
This is a breaking change for the following code:
```python
x = cp.Variable()
x += 1
``` 
It also improves the error message on code we broke a few releases ago:
```python
x = cp.Variable(4)
c = np.array([1, 2, 3, 4])
x += c
```
It is possible to not break the first code while improving the error messages on the other code.
Once we have consensus on what we want this to do, I'll write unit tests.
=> Implements inplace mutation error

cvxpy/atoms/quad_over_lin.py, cvxpy/reductions/solvers/solving_chain.py, cvxpy/tests/test_dpp.py
When the second argument to quad_over_lin is parameterized, the atom is DPP when canonicalized as an SOCP but not when canonicalized as a quadratic. This PR resolves the bug by making quad_over_lin not DPP in all cases whenever the second argument is parameterized.
Issue link (if applicable): #2433
=> Fix for issue with quad_over_lin parameters

cvxpy/atoms/quad_over_lin.py, cvxpy/tests/test_dpp.py
Quick follow-up to #2435, allowing DGP + DPP `quad_over_lin`.
Marked as bug as it should be considered part of #2435.
=> Adds back DGP + DPP quad_over_lin

cvxpy/lin_ops/canon_backend.py
Numpy's default integer type on Windows is int32. The implementation in flatten_tensor explicitly converts Python integers into int64, but in on place it does it after the damage has been done on Windows.
On Windows, `np.prod` returns an int32 when given a Python tuple of ints, but can be directed to work with int64 instead. This prevents an integer overflow for e.g. `np.prod((60000, 60000))`, which returns a negative number on Windows. Setting the dtype for `np.prod` explicitly fixes that.
=> Fix integer overflow on Windows in TensorRepresentation.flatten_tensor

cvxpy/atoms/elementwise/huber.py, cvxpy/tests/test_atoms.py
This change allows the M parameter in the huber function to be a parameter for DPP.
=> allow M to be a Parameter in the huber function

pyproject.toml
Now that NumPy 2.0 is officially available through pip, the build systems need to reflect this change to ensure a smooth user experience. 
Using the [build](https://pypi.org/project/build/) library I was able to test the new pyproject.toml build instruction which ran successfully. 
```
Successfully built cvxpy-1.6.0.tar.gz and cvxpy-1.6.0-cp312-cp312-macosx_11_0_arm64.whl
```
These changes do not affect our support of older NumPy versions since the dependencies still list the following requirement: ``numpy >= 1.15``, see [here](https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice) for more details.
Issue link (if applicable): #2474
=> updating pyproject to support numpy 2.0

.github/workflows/build.yml, continuous_integration/install_dependencies.sh
The macos-11 label has been deprecated and will no longer be available after 28 June 2024.
To be merged after the 1.5.2 release.
=> [CI] Updates macos version

cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
The Gurobi QP interface has an unnecessary `np.array(..., copy=False)` invocation that doesn't play well with NumPy 2.0
=> Deal with NumPy 2.0 compatibility breaker in gurobi interface

.devcontainer/startup.sh, .github/workflows/test_backends.yml, .gitignore, continuous_integration/install_dependencies.sh, pyproject.toml
In light of future PRs for the n-dimensional cvxpy support, I would like to make use of [hypothesis](https://hypothesis.readthedocs.io/en/latest/index.html) for more extensive testing. In particular, hypothesis provides [numpy specific](https://hypothesis.readthedocs.io/en/latest/numpy.html#module-hypothesis.extra.numpy) test examples. NumPy also actually uses those tests (see image below).
I also updated the pyproject.toml to reflect this new optional dependency for the test suite (as well as adding one for the documentation). 
Users can now do the following to install everything at once:
```
pip install -e ".[testing]"
```
=> adding hypothesis dependency for testing

cvxpy/reductions/solvers/conic_solvers/conic_solver.py
Title explains what the PR is doing. (also, removing the ``remainder`` variable since it wasn't being used)
Issue link (if applicable): #2493
=> changing built-in divmod to numpy and specifying dtype=int64

cvxpy/atoms/affine/sum.py, cvxpy/atoms/atom.py, cvxpy/atoms/axis_atom.py, cvxpy/constraints/constraint.py, cvxpy/cvxcore/python/cppbackend.py, cvxpy/expressions/constants/constant.py, cvxpy/expressions/expression.py, cvxpy/expressions/leaf.py, cvxpy/lin_ops/canon_backend.py, cvxpy/lin_ops/lin_utils.py, cvxpy/problems/problem.py, cvxpy/reductions/solvers/solving_chain.py, cvxpy/settings.py, cvxpy/tests/test_atoms.py, cvxpy/tests/test_dqcp.py, cvxpy/tests/test_expression_methods.py, cvxpy/tests/test_expressions.py, cvxpy/tests/test_python_backends.py, cvxpy/tests/test_shape.py, cvxpy/utilities/canonical.py
This PR aims to add support for n-dimensional sum operations with the ability to pass in any axis, including multiple axes as well. In addition, a new function has been added to choose the correct backend depending on the dimensions of the underlying expressions of the problem. 
This PR is also a small step towards enabling full nd support in light of cvxpy 2.0, hence I have commented out the ValueErrors for related instances. 
Future todos to complement this PR:
- parametrized nd-sum
- keep the scipy backend implementation sparse (will need to do some indexing hacks).
=> Adding support for n-dimensional sum(axis, keepdims) operation

cvxpy/cvxcore/python/canonInterface.py
This PR fixes a bug that caused some benchmarks to fail. 
See the logs from asv here:
```
canonInterface.reduce_problem_data_tensor(
File "/Users/willizz/Documents/benchmarks/env/d7b296eeadace6ef7218f773ed071d5d/lib/python3.11/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 130, in reduce_problem_data_tensor
n_constr = A.shape[0] // (n_cols)
~~~~~~~~~~~^^~~~~~~~~~
OverflowError: Python integer 2738598423566 out of bounds for int32
asv: benchmark failed (exit status 1)
```
=> Avoid integer overflow error for ``nconstr`` in ``canonInterface.py``

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/test_backends.yml, README.md, continuous_integration/install_dependencies.sh, cvxpy/atoms/affine/reshape.py, cvxpy/expressions/leaf.py, doc/source/install/index.rst, pyproject.toml, sonar-project.properties
In light of the following PR #2488 which requires ``numpy>=1.20`` for the API function ``broadcast_shapes``,
we are both dropping support for python 3.8 (EOL in October 2024) and also bumping the minimum numpy version from ``1.19.3`` to ``1.20``. Thanks to @PTNobel for the suggestions.
=> updating numpy dependency to 1.20 and removing support for python 3.8

cvxpy/atoms/condition_number.py, cvxpy/atoms/gen_lambda_max.py, cvxpy/atoms/lambda_max.py, cvxpy/tests/test_conic_solvers.py
- The eigvals named argument of the scipy.linalg.eigvalsh has been removed in favor of subset_by_index.
- The .A attribute of sparse matrices has been removed in favor of .torray()
cf https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html
=> Fix scipy 1.14 incompatibilities

cvxpy/lin_ops/canon_backend.py, cvxpy/tests/test_expressions.py
This PR addresses a TODO in the nd sum PR. It implements a function ``get_row_sum_idx`` which computes the summands of the sum operation (similar to NumPy but symbolic). The column indices are obtained by flattening a range in fortran order. 
The idea of ``get_sum_row_idx`` is to group the entries that would correspond to a sum with the corresponding axis input. First we compute the out_dims by deleting the dims corresponding to the axis argument. Then we compute the indices corresponding to these out_dims. There will be duplicate values corresponding to the size of axis, those are the values that will be summed together. Hence the goal is to assign the same row values to all the duplicate entries in ``indices[out_dims]``. NumPy provides a …
=> sparse implementation for nd sums

cvxpy/lin_ops/canon_backend.py, cvxpy/tests/test_expressions.py
nd sums were not working in conjunction with sparse variables and it was because I had previously assumed that the tensor was always an identity matrix. @PTNobel gave the suggestion to form a sparse coefficient matrix to multiply the tensor with, thanks!
=> update nd-sum to be general for sparse variables

cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
We stopped officially supporting code for Clarabel v<0.5.0 a few releases ago, so we can drop this extra code.
=> Removes support for old CLARABEL versions

cvxpy/atoms/affine/reshape.py, cvxpy/constraints/exponential.py, cvxpy/constraints/power.py, cvxpy/constraints/second_order.py, cvxpy/tests/test_problem.py
In the latest release of NumPy (v2.1.0), the `order` argument to `np.reshape` became keyword-only, so the `cp.reshape` atom is failing.
The `newshape` argument is also deprecated, `shape` is preferred to align with the Array API.
I think the `order` change was unintended and might be reverted in a patch release (reported in numpy/numpy#27256). However, it is still worth fixing this in cvxpy to guard against future changes.
=> `np.reshape` needs order as keyword argument

cvxpy/lin_ops/canon_backend.py, cvxpy/tests/test_expressions.py, cvxpy/tests/test_python_backends.py
This PR adapts the SciPy backend sum function to support parametrized sums. 
I introduced a new helper function ``get_sum_coeff_matrix`` since I noticed that it was being reused for both cases (non-dpp and dpp). 
This PR keeps the old functionality the same and adds a general case for when ``axis != None``.
=> adding support for nd sum in parametrized expressions

cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py
Issue link (if applicable): `value.A` has been removed from scipy sparse arrays. This bug only happens when solving large problems.
=> Fix: `value.A` has been removed and is still used for large problems

cvxpy/tests/test_atoms.py, cvxpy/tests/test_benchmarks.py, cvxpy/tests/test_constraints.py, cvxpy/tests/test_derivative.py, cvxpy/tests/test_domain.py, cvxpy/tests/test_dpp.py, cvxpy/tests/test_dqcp.py, cvxpy/tests/test_grad.py, cvxpy/tests/test_monotonicity.py, cvxpy/tests/test_nonlinear_atoms.py, cvxpy/tests/test_perspective.py, cvxpy/tests/test_problem.py, cvxpy/tests/test_semidefinite_vars.py
Now that we are transitioning from ECOS to CLARABEL, I think it makes sense to change all our tests to use cp.CLARABEL by default. 
P.S. Some tests are failing (mostly in ``test_DQCP``), I believe this could be due to precision or some other missing parameter? 
I am not too familiar with Clarabel, @PTNobel could you have a look please?
=> Changing solver in tests from ECOS to CLARABEL

cvxpy/atoms/sum_largest.py, cvxpy/tests/test_atoms.py
This PR takes advantage of numpy's [argpartition](https://numpy.org/doc/stable/reference/generated/numpy.argpartition.html) function to partially sort the expression X. 
Since we only care about the $k$ largest (resp. smallest) values, we just need to make sure that the k-th element is sorted and all the values to its right (resp. left) are larger (resp. smaller). 
Algorithmic improvement (worst-case): ``O(nlogn)`` to ``O(nlogk)``.
Some small benchmarks:
```py
import time
def new(x, k):
indices = np.argpartition(-x, k)[:k]
return x[indices].sum()
def prev(x, k):
indices = np.argsort(-x)[:k]
return x[indices].sum()
x = np.random.rand(10_000_000)
for k in [100, 1000, 10_000]:
print('k:', k)
start = time.time()
prev(x, k) …
```
=> improve sum_largest to use partitionsort instead of standard sort

cvxpy/atoms/affine/index.py, cvxpy/tests/test_expressions.py, cvxpy/utilities/key_utils.py
When passing a list or an ndarray as an index, cvxpy currently shows the entire constant in the string representation which can get quite messy (example below):
```py
>>> import numpy as np
>>> import cvxpy as cp
>>> idx = np.arange(178)
>>> exp = cp.Variable((200, 10), name="exp")[idx, 6]
>>> print(exp)
exp(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
78,  79,  80,  81,  82,  83,  84,  85,  86,  87, …
```
=> improving special indexing string representation

cvxpy/expressions/leaf.py, cvxpy/reductions/matrix_stuffing.py
This PR aims to improve the processing of boolean and integer indices by avoiding an expensive list of tuple unpacking.
Results below:
```py
import time
def new(shape):
idx = np.arange(np.prod(shape))
multi_idx = np.unravel_index(idx, shape, order='F')
return np.ravel_multi_index(multi_idx, shape, order='F')
def prev(shape):
idx = np.ndindex(shape)
multi_idx = list(zip(*idx))
return np.ravel_multi_index(multi_idx, shape, order='F')
shape = (10000, 1000)
start = time.time()
prev(shape)
print('prev:', time.time() - start)
start = time.time()
new(shape)
print('new:', time.time() - start)
```
Output:
```
prev: 3.726440906524658
new: 0.06124114990234375
```
=> Improving indice processing for boolean and integer attributes

cvxpy/atoms/__init__.py, cvxpy/atoms/cvar.py, cvxpy/tests/test_atoms.py, doc/source/api_reference/cvxpy.atoms.other_atoms.rst, doc/source/tutorial/functions/index.rst
This PR creates the `cvar` atom (conditonal value at risk), which is implemented as a wrapper around the existing `dotsort` atom.
=> New CVaR atom

.github/workflows/build.yml, continuous_integration/install_dependencies.sh
Reduce duplication in github actions workflow for builds, and re-add "single action" configurations that produce coverage uploads and Source Distribution (sdist) files.
Fixes #2584.
=> Re-enable sdist publishing + clean up build workflows

continuous_integration/install_dependencies.sh
coptpy version 7.2.1 was released yesterday and it is causing failures on all our CI. (see logs below).
This PR pins the version that is being installed to avoid these CI failures.
P.S. We should probably reach out to the COPT team about this.
```bash
Fatal Python error: Segmentation fault
Current thread 0x00007fbb3e2f6180 (most recent call first):
File "/home/runner/work/cvxpy/cvxpy/cvxpy/reductions/solvers/qp_solvers/copt_qpif.py", line 166 in solve_via_data
File "/home/runner/work/cvxpy/cvxpy/cvxpy/reductions/solvers/solving_chain.py", line 516 in solve_via_data
File "/home/runner/work/cvxpy/cvxpy/cvxpy/problems/problem.py", line 1157 in _solve
File "/home/runner/work/cvxpy/cvxpy/cvxpy/problems/problem.py", line 573 in solve
File …
```
=> Pin coptpy version to 7.1.7

continuous_integration/install_dependencies.sh
Mosek can only be tested on merge (something to do with secrets not being available) and so this change wasn't detected in the PR branch CI.
=> CI: avoid installing Mosek for python3.13

.github/workflows/build.yml
This PR overrides #2575 to a newer version cibuildwheel that supports building wheels for python3.13.
=> CI: update cibuildwheel to 2.21.3

README.md, continuous_integration/install_dependencies.sh, cvxpy/problems/problem.py, cvxpy/reductions/solvers/solving_chain.py, cvxpy/tests/test_KKT.py, cvxpy/tests/test_atoms.py, cvxpy/tests/test_complex.py, cvxpy/tests/test_cone2cone.py, cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_dgp2dcp.py, cvxpy/tests/test_dpp.py, cvxpy/tests/test_dqcp.py, cvxpy/tests/test_examples.py, cvxpy/tests/test_linear_cone.py, cvxpy/tests/test_nonlinear_atoms.py, cvxpy/tests/test_power_tools.py, cvxpy/tests/test_problem.py, cvxpy/tests/test_suppfunc.py, pyproject.toml, requirements.txt
This PR deletes ECOS as a dependency, as discussed in the release of version 1.5 (which changed its default solver from ecos to clarabel). 
There are currently some minor regressions from this default solver change in our test suite (especially in a few DQCP tests). However, we believe it is not a big change for users to add, if necessary, an installation step for ecos. 
=> removing ECOS dependency

cvxpy/atoms/__init__.py, cvxpy/atoms/affine/concatenate.py, cvxpy/lin_ops/canon_backend.py, cvxpy/lin_ops/lin_op.py, cvxpy/lin_ops/lin_utils.py, cvxpy/reductions/complex2real/canonicalizers/__init__.py, cvxpy/tests/test_atoms.py, cvxpy/tests/test_expressions.py, cvxpy/tests/test_python_backends.py
Thank you for this amazing project!, I've been using it for a while and I decided to contribute. This PR aims to add `cp.concatenate` support as mentioned in here #2567. Note that so far I added it to the atoms and to the numpy/scipy backends. I haven't added it yet to the cpp/rust backends. I'd love to add it there, but before going too far, i'd like to know if this is needed/wanted and if my PR is in a good spot. I tried to follow numpy concatenate convention. I added several unit tests and also docstring documentation you can check to follow my ideas. 
**I pushed my changes after runnning ruff format command**, so as you can see there are some format changes that i'd like to avoid --- Do you have a command to do formatting that will sync with master branch?
=> Support concatenate on atoms

.github/workflows/build.yml, continuous_integration/install_dependencies.sh
Pyscipopt 5.2.1 is the latest version (released october 31 :ghost: 2024).
Also update the mac-os version to 13 in CI due to encountering the following error:
```
The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15.
```
=> CI: change pyscipopt installation to use pip and pin version

cvxpy/atoms/__init__.py, cvxpy/atoms/affine/concatenate.py, cvxpy/problems/problem.py, cvxpy/reductions/solvers/solving_chain.py, cvxpy/tests/test_atoms.py, cvxpy/tests/test_expressions.py, cvxpy/utilities/canonical.py
If an operator is not supported in CPP then select SCIPY backend. This allows you to define operators in numpy/scipy versions without having to program their analogue in cpp.
Also enables concatenate operator in the top level module.
**WIP**
Issue link : #2597  See for details
=> - Select scipy if any problem atom is not supported in cpp.

cvxpy/atoms/quantum_cond_entr.py, cvxpy/tests/test_quantum_rel_entr.py, examples/QI_demo.py
Minor fix to ensure `quantum_cond_entr` test passes
=> Fixes failing `quantum_rel_entr` tests

cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_qp_solvers.py
Thanks a lot for @simonbowly for pointing the fix.
Quote:
"So in cvxpy these cases:
```python
if solver_status != gurobipy.StatusConstClass.TIME_LIMIT:
```
should be replaced with just":
```python
if solver_status != gurobipy.GRB.TIME_LIMIT
```
=> Fix breaking tests due to gurobi interface update

.pre-commit-config.yaml, pyproject.toml
[changelog for ruff](https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#081)
This updates ruff and also removes a deprecation warning about select not being in a `lint` section of the `pyproject.toml`
Also migrate to `extend-exclude` as the default exclude is [pretty decent](https://docs.astral.sh/ruff/configuration/)
Also ignore [E721](https://docs.astral.sh/ruff/rules/type-comparison/); This is a newer check and fails in many files.
Keeping it ignored mimic behavior pre-upgrade.
Another PR seems appropriate to fix `is / is not` vs `==/!=`
=> build(pre-commit): Update ruff from 0.1.11 -> 0.8.1

continuous_integration/install_dependencies.sh
CI is failing on master for python 3.10 and 3.9 on MacOS. The error is odd because the tests crashes without any error messages on python's side. I did a bit of digging and found that the most likely solver that is causing this is [highspy](https://pypi.org/project/highspy/) which new version 1.9.0 was released two days ago (December 20th, 2024).
Update: instead of pinning highspy to 1.8, updating the scipy and numpy versions somehow fixes the issue.
=> Updating scipy and numpy versions for python < 3.12

examples/notebooks/WWW/socp.ipynb
=> Fixed a coding typo in socp.ipynb

README.md, continuous_integration/install_dependencies.sh, cvxpy/tests/test_quantum_rel_entr.py, doc/source/install/index.rst, pyproject.toml
This PR aims to fix some issues found with deprecated API on sparse_arrays compared to sparse_matrices (see #2689).
=> Updating SciPy dependency to >=1.11.0 and version for wheels to >=1.13.0

doc/source/install/index.rst, doc/source/tutorial/solvers/index.rst
This PR updates the highs solver link which is the old website hosted on the academic page of the project lead which now reads "The HiGHS website moved in 2022 to https://highs.dev/. Please update your link."
=> Update highs solver website links

cvxpy/expressions/expression.py
Add type hints to several `Expression` methods.
These type hints should reduce the number of instances where the mypy static type checker incorrectly raises type warnings, for example in this snippet
```
x = cp.Variable()
prob = cp.Problem(objective=cp.Minimize(x), constraints=[x == 1])
```
one would get the warning `Expected type 'list[Constraint] | None', got 'list[bool]' instead`.
In this case, we can fix the static analysis by adding `Equality` as the return type hint of the `Expression.__eq__` method. This PR implements this simple change and several other similar changes in the `Expression` class.
[Link to short discord discussion.](https://discordapp.com/channels/845323972962549790/1335428795192184832/1335428795192184832)
=> Improve type hinting for expressions

cvxpy/expressions/leaf.py, cvxpy/tests/test_attributes.py
This PR fixes two bugs. First, when assigning a sparse value, any order of nonzero indices is accepted, as long as the set of nonzero indices is correct. Previously, the sparsity pattern was rejected as invalid when the order of nonzero indices was not identical to that used when the `Leaf` was constructed. Second, when reading a sparse value and it is `None`, `None` will be returned. Previously, there was an error when attempting to read `_value.data`.
=> Assigning to and reading from sparse leaves

doc/source/examples/index.rst
This change adds links to interactive marimo examples for:
1. least squares
2. linear programs
3. quadratic programs
4. generic convex optimization (which points the reader to the DCP docs)
5. SDPs
6. minimum fuel optimal control
7. markowitz portfolio optimization
Examples 2, 3, 6, and 7 have interesting interactive components and visualizations that hopefully help the reader better understand the topic at hand.
Additionally, this change splits up "basic examples" into "basic examples" and "basic applications", to make the simpler application notebooks more discoverable. The SOCP example was moved into Advanced; it manually uses an `SOC` constraint, which feels very not basic to me.
This is purely a docs change, so these are vacuously true.
=> docs: add links to interactive marimo examples

cvxpy/reductions/solvers/conic_solvers/highs_conif.py, cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
Currently, when using the CVXPY interface to `highspy`, the message `Running HiGHS 1.9.0 (git hash: fa40bdf): Copyright (c) 2024 HiGHS under MIT licence terms` is logged to standard output even if `output_flag` is set to `False`. Here's a minimum working example:
```python
x = cp.Variable(nonneg=True)
problem = cp.Problem(cp.Minimize(x))
problem.solve(solver="HIGHS", output_flag=False)
```
This pull request swaps the order of `passOptions` and `passModel` to ensure that options are set prior to model instantiation, when the logging seems to be triggered.
=> Swap order of `passOptions` and `passModel` in HiGHS interface

.github/workflows/test_optional_solvers.yml, continuous_integration/install_dependencies.sh, continuous_integration/install_optional_solvers.sh
This PR creates a new file in `continuous_integration/` called `install_optional_solvers.sh`, which moves the installation of optional solvers from  `install_dependencies.sh` so that the failure of optional solver unit tests does not affect the cvxpy build. A new workflow is also created titled `test_optional_solvers.yml` which calls `install_optional_solvers.sh` and runs unit tests for the optional solvers.
=> Added workflow to install and test optional solvers

cvxpy/reductions/solvers/conic_solvers/ecos_bb_conif.py, cvxpy/reductions/solvers/conic_solvers/ecos_conif.py, cvxpy/reductions/solvers/conic_solvers/qoco_conif.py, pyproject.toml
After the sparse_array PR #2710 merged, qoco and ecos/ecos_bb unit tests started failing.
QOCO unit tests failed, since the python wrapper expects the row index and column pointer arrays to be int32, but with sparse_arrays they are int64. This PR uses the `safely_cast_index_arrays` function to cast these indices. Unfortunately, this function first appears in scipy v1.15.0, but cvxpy requires only scipy  >=1.11.0.
The ecos failures are due to the expectation that matrices passed to the ecos python wrapper are of type csc_matrix rather than csc_array. There are two potential solutions: open a PR in [ecos-python](https://github.com/embotech/ecos-python) to expect csc_array, but this might be an invasive change and break existing projects csc_matrix is passed into ecos-python. The second …
=> Fix failing optional solvers

cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py
CVXPY does not currently work with OSQP v1.0.0b1 and v1.0.0.b3 due to changes in the PR: https://github.com/cvxpy/cvxpy/pull/2710.
The failure method is similar to that observed by QOCO and ECOS due to the same PR (`TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'`), however QOCO and ECOS were fixed with the PR: https://github.com/cvxpy/cvxpy/pull/2720.
This current PR makes the changes that will allow OSQP v1.0.0b1 and v1.0.0.b3 to work with CVXPY v1.7.0.
=> Fix cvxpy with osqp v1.0.0

cvxpy/atoms/axis_atom.py, cvxpy/tests/test_grad.py
This PR fixes an indexing bug in the `_axis_grad` method of the `AxisAtom` class.
=> correct indexing in _axis_grad

cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py, cvxpy/tests/test_conic_solvers.py
Fixes a crash condition when making parametric updates using clarabel v0.10.0 and cvxpy v1.6.1.
The issue arises when updating data for a problem with a non-diagonal quadratic cost, since the internal update function in clarabel wants updated `P` data to be in upper triangular form.   This crash does *not* happen during solver initialization because in that case clarabel accepts non-triangular `P` and enforces the triangularity condition internally when copying the problem data.
=> fix clarabel crash on parametric update in v1.6.1

cvxpy/atoms/__init__.py, cvxpy/atoms/affine/binary_operators.py, cvxpy/atoms/affine/broadcast_to.py, cvxpy/atoms/affine/promote.py, cvxpy/expressions/expression.py, cvxpy/lin_ops/canon_backend.py, cvxpy/lin_ops/lin_op.py, cvxpy/lin_ops/lin_utils.py, cvxpy/problems/objective.py, cvxpy/problems/problem.py, cvxpy/reductions/complex2real/canonicalizers/__init__.py, cvxpy/tests/test_atoms.py, cvxpy/tests/test_expressions.py, cvxpy/tests/test_python_backends.py, cvxpy/utilities/canonical.py
This PR introduces the broadcast_to atom in hopes of fixing issues with broadcasting in higher dimensions. 
The broadcast_to atom is used internally inside of the expression class in its ``broadcast`` method.
This method is called in many places, including binary ops, basic ops and others.
The implementation of the atom follows other similar shape manipulation atoms such as vstack and concatenate. The idea is to form a set of indices which are reshaped to the expression's shape, then using numpy's API we are able to mimic the behavior of ``np.broadcast_to`` on cvxpy's tensor views in the backend. 
In the #2728 discussion, I brought up some issues with the difference in behavior for the backends. Those issues were resolved as follows: 
- only …
=> Adds new broadcast_to atom for nd broadcasting

cvxpy/expressions/leaf.py, cvxpy/tests/test_attributes.py
This part adds a special path for None values in the ``save_value`` method. This way it avoids an error while trying to index a NoneType. 
Issue link (if applicable): #2759
=> Bug: fix issue with infeasible sparse problems

cvxpy/reductions/solvers/conic_solvers/qoco_conif.py
Prior to this PR, the following problem would throw a setup error within QOCO.
```
x = cp.Variable(2)
objective = cp.Minimize(cp.quad_form(x, np.eye(2)))
constraints = [x[0]+x[1] == 4]
prob = cp.Problem(objective, constraints)
prob.solve(solver='QOCO', verbose=True)
```
If a problem data matrix is not present for a given problem, it should be passed to qoco's setup function as `None`. 
For example, in the problem above, the conic constraint matrix `G` should be passed to qoco's setup function as None, but in the problem, `data[s.G]` is not None, it is some CSC matrix with 0 rows.
This PR fixes this issue, by setting `A` and `G` to  `data[s.A]` and  `data[s.G]` respectively if their respective constraints are present (i.e. `p>0` and `m>0`).
=> Fix equality only constraints error in QOCO

cvxpy/tests/test_attributes.py
OSQP v1.0.0 was recently [released](https://github.com/osqp/osqp/releases/tag/v1.0.0). And one test started failing because the problem status changed. This PR aims to fix this issue to ensure the CI passes once again.
=> fix change in problem status for newest osqp version

.gitignore, cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py, cvxpy/tests/test_attributes.py
• OSQP v1.0+ renamed the 'polish' parameter to 'polishing'
• This PR detects the OSQP version and uses the appropriate parameter name
• Ensures compatibility with both older and newer versions of OSQP
https://github.com/osqp/osqp-python/issues/170
@vineetbansal @ianmcinerney
=> Fix OSQP polish parameter name for v1.0+

cvxpy/reductions/dcp2cone/dcp2cone.py, cvxpy/tests/test_quadratic.py
Fixes a bug where non-quadratic quad_over_lin was interpreted as quadratic when using a conic solver that supports use_quad_obj = True.
Issue link (if applicable): #2773
=> Fix bug with quad_over_lin and use_quad_obj = True

cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py, cvxpy/tests/test_quad_form.py
Not sure if this is the correct fix.
I think there were some changes to the OSQP interface which causes one of the test to fail.
The test in question uses the wrapper ``assume_PSD=True`` on a clearly non-PSD matrix, which causes the OSQP solver to fail. However, it seems like the error being raised is different with the new OSQP. 
=> change OSQP error type when passing non-psd A matrix

cvxpy/reductions/solvers/conic_solvers/highs_conif.py, cvxpy/reductions/solvers/qp_solvers/highs_qpif.py, cvxpy/tests/test_conic_solvers.py, doc/source/tutorial/solvers/index.rst, pyproject.toml
This PR adds a `highs_options` argument to solve (à-la `mosek_params`, `scipy_options`, etc.) to prevent the argument/option name clash issue observed in https://github.com/cvxpy/cvxpy/issues/2662 -- i.e., HiGHS option `solver="simplex"` clashing with solve argument `solver=cp.HIGHS`.
The main logic change/addition is `unpack_highs_options_inplace` function. 
---
(Out-of-scope) This function can be called at a higher level, generalizing this `solvername_options`/`solvername_params` (or more aptly `solver_opts`) unpacking logic and solving this issue for all solvers at the same time. A backwards compatible way to implement this logic would have been a significantly larger PR so I went with the suggestion here https://github.com/cvxpy/cvxpy/issues/2662#issuecomment-2660430851.
---
For some …
=> Implement highs_options to prevent option/argument name clashes 

cvxpy/problems/problem.py, cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_problem.py
Enables solver name to be non-upper case (e.g., HiGHS instead of HIGHS).
Issue link (if applicable): https://github.com/cvxpy/cvxpy/issues/2751
=> Make solver name more flexible

cvxpy/reductions/solvers/conic_solvers/highs_conif.py, cvxpy/reductions/solvers/qp_solvers/highs_qpif.py, cvxpy/tests/test_conic_solvers.py
Adds the ability to warm-start HiGHS for MIPs and LPs, solved via `cvxpy/reductions/solvers/conic_solvers/highs_conif.py`. 
This change essentially copies exactly the existing design for warm-starting HiGHS's QP solver (`cvxpy/reductions/solvers/qp_solvers/highs_qpif.py`). On that note, also updates the description there, which was out of date.
Not all solvers present on my machine, but HIGHS is.
```
================ 1200 passed, 356 skipped, 1412 warnings in 25.19s ================
```
Skipped—didn't seem worth it.
=> Add warm_start option to HIGHS MIP and LP solver

cvxpy/reductions/solvers/qp_solvers/piqp_qpif.py, cvxpy/tests/test_qp_solvers.py
In the next version of PIQP, the API is going to change due to the addition of general double-sided inequality constraints: [https://github.com/PREDICT-EPFL/piqp/pull/22](https://github.com/PREDICT-EPFL/piqp/pull/22)
To not break CVXPY for users using PIQP as a backend, this PR implements version depended logic to retain backwards compability. The the new version of PIQP will be publish after a new release of CVXPY.
Additionaly, the PR implements support for warm starting, i.e., reusing the problem strucutre and data if it doesn't change.
=> PIQP interface API changes and warm-start support

cvxpy/settings.py
As is the UNIX convention. See eg https://stackoverflow.com/questions/4919093/should-i-log-messages-to-stderr-or-stdout. Sending messages to stdout breaks scripts that wish to use cvxpy but also have requirements on their own stdout specification. For example, if `myscript` is required to output valid JSON then one cannot use cvxpy in `myscript`.
=> settings.py: send logging messages to stderr

continuous_integration/install_optional_solvers.sh
Our CI is ignoring most optional solvers on Python 3.13. I want to try and enable them, and if it doesn't work, document why.
=> Tries to remove the version limitations in CI

cvxpy/atoms/axis_atom.py, cvxpy/tests/test_shape.py
MrMonday on discord pointed out a bug with the ``shape_from_args`` method for the axis_atom.
I think there was already some logic for this before, but it might have been removed accidentally when we added the n-d sum and made changes to the axis_atom class. 
=> support negative axes in sum (and other axis_atoms)

cvxpy/expressions/leaf.py, cvxpy/reductions/solvers/conic_solvers/highs_conif.py, cvxpy/tests/solver_test_helpers.py, cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_problem.py
If the `value` of a variable is set during object creation but if the `bounds` set to be `[None,None]` then the value setter raises an `AttributeError: 'Variable' object has no attribute 'bounds'` because the bounds are not "sanitized" yet. 
This PR swaps the order of value assignment and the bound cleanup operation in `Leaf.__init__` and adds a tiny non-regression test.
(While at it I also fixed some of the obvious white-space issues.)
Issue link (if applicable): N/A
- [N/A] Add our license to new files.
- [N/A] Run the benchmarks to make sure your change doesn’t introduce a regression.
=> Set variable value after bound sanitization

cvxpy/tests/test_constant_atoms.py, cvxpy/tests/test_derivative.py
Removes the last two tests that depend on ECOS! I had to make a diffcp release to get one set of tests passing, but that should be on PyPI soon and then we can pass tests.
One test isn't working numerically, I want to spend a little time understanding what's happening and then I'll probably ping Paul.
=> Finish ecos removal

cvxpy/expressions/leaf.py, cvxpy/tests/test_attributes.py
This makes us only warn about `.value` for sparse leafs when it causes significant fill-in. I'm not sure about my exact metric for fill-in, right now I'm doing 3 x as many 0s as my cut off. I'm open to making it an absolute number of zeros being added or some mix of the two. (more than 100 0s added and 2x as much perhaps?)
@rileyjmurray this feels like something you'd care about.
Issue link (if applicable): https://github.com/cvxpy/cvxpy/discussions/2782
=> Only warns about `.value` for sparse leafs when it causes significant fillin

cvxpy/constraints/constraint.py
This PR fixes a docstring typo in `cvxpy/constraints/constraint.py`.
The description incorrectly stated that the residual is squared, but in fact it is not.
For example, the `violation` methods in other constraint classes such as [`SecondOrderCone`](https://github.com/cvxpy/cvxpy/blob/master/cvxpy/constraints/second_order.py#L105) and [`NonPos`](https://github.com/cvxpy/cvxpy/blob/master/cvxpy/constraints/nonpos.py#L95) compute the norm via `np.linalg.norm(x, ord=2)` without squaring the result.
=> Fix docstring in Constraint.violation: remove mention of squaring

cvxpy/atoms/quantum_cond_entr.py, cvxpy/atoms/quantum_rel_entr.py, cvxpy/atoms/von_neumann_entr.py, cvxpy/constraints/exponential.py, cvxpy/expressions/expression.py, cvxpy/tests/test_quantum_rel_entr.py, cvxpy/tests/test_von_neumann_entr.py
This started just as a plan to resolve #2644. I ended up making documentation changes in quite a few atoms related to quantum information and quadrature-based approximations of relative entropy cones.
More material changes:
* von_neumann_entr now checks that the input is Hermitian, rather than merely square.
* quantum_rel_entr's .value function now references an EVAL_TOL static class variable to determine how to handle small negative eigenvalues.
* adds a new Expression.cast function. This is just a wrapper around Expression.cast_to_const, which we use all over the place in ways that don't make sense given the function's name. I think it'd be good to replace Expression.cast_to_const with Expression.cast systematically, but that's better left to another PR.
I noticed that quantum relative …
=> Doc improvements for some atoms, plus an Expression.cast function.

.github/workflows/build.yml, .github/workflows/test_optional_solvers.yml, continuous_integration/install_dependencies.sh
This [official github blog](https://github.blog/changelog/2025-07-11-upcoming-changes-to-macos-hosted-runners-macos-latest-migration-and-xcode-support-policy-updates/#macos-13-is-closing-down) states that the ``macos-13`` action runners are being deprecated on September 1st, 2025. However, they are the last runners that are on x86 intel machines, see this [discussion](https://github.com/astropy/astropy/issues/18456). 
Issue link (if applicable): 
Per discussion in #2872
=> CI: update macOS runners to ``macos-14``

continuous_integration/install_optional_solvers.sh, cvxpy/reductions/solvers/conic_solvers/xpress_conif.py, cvxpy/reductions/solvers/qp_solvers/xpress_qpif.py, pyproject.toml
Fix various deprecation warnings in Xpress. Currently fixed the status mapping warnings. Still getting the following warnings:
`/home/govind/Desktop/git/cvxpy/cvxpy/reductions/solvers/qp_solvers/xpress_qpif.py:231: DeprecationWarning: Deprecated in Xpress 9.5: use problem.attributes.solvestatus and problem.attributes.solstatus instead
results_dict['status'] = self.prob_.getProbStatus()
/home/govind/Desktop/git/cvxpy/cvxpy/reductions/solvers/qp_solvers/xpress_qpif.py:232: DeprecationWarning: Deprecated in Xpress 9.5: use problem.attributes.solvestatus and problem.attributes.solstatus instead
results_dict['getProbStatusString'] = self.prob_.getProbStatusString()
/home/govind/Desktop/git/cvxpy/cvxpy/reductions/solvers/qp_solvers/xpress_qpif.py:233: DeprecationWarning: Deprecated in Xpress …
=> Fix status mapping issues

doc/source/api_reference/cvxpy.problems.rst
This will make `var_dict` visible in the automatically generated docs. This is a very convenient property for accessing variables by name.
=> Add `var_dict` to documentation

cvxpy/atoms/affine/partial_trace.py, cvxpy/atoms/affine/partial_transpose.py, cvxpy/atoms/axis_atom.py, cvxpy/tests/test_atoms.py, pyproject.toml
Addresses issue #2816 
- Replaced manual axis checks with:
- `normalize_axis_index` in `partial_trace.py` and `partial_transpose.py`
- `normalize_axis_index` and `normalize_axis_tuple` in `axis_atom.py`
- Removed redundant `ValueError` checks for out-of-bounds axes
- Removed tests that manually validated axis bounds (since NumPy now handles this)
Please see above. 
- [] Run the benchmarks to make sure your change doesn’t introduce a regression.
FYI I did not see the benchmark test.
=> Replace custom axis handling with numpy.array_utils.normalize_axis_*

cvxpy/reductions/solvers/conic_solvers/ecos_conif.py, cvxpy/reductions/solvers/qp_solvers/daqp_qpif.py, cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py, cvxpy/tests/test_problem.py
If solver hits max iters it should return `s.USER_LIMIT`.
Another question is if the user interrupts the solver with ctrl+C, should the solver return `s.SOLVER_ERROR` or `s.USER_LIMIT`. Some interfaces do one, others do the other. 
https://github.com/cvxpy/cvxpy/issues/2533
=> If solver hits max iters it should return s.USER_LIMIT

cvxpy/tests/test_conic_solvers.py, cvxpy/tests/test_qp_solvers.py
Check KNITRO license before running tests. 
This should prevent failed tests for optional solvers in CI.
=> Check KNITRO license before running tests

cvxpy/atoms/pnorm.py, cvxpy/tests/test_grad.py
Fixes issue #2896.
The gradient computation for `cp.harmonic_mean` was failing with `ValueError: scipy.sparse does not support dtype object`.
The issue occurred when computing gradients with `p=-1` (used by harmonic_mean), where `self.p` is a `Fraction` object. Computing `np.power(value, self.p - 1)` with Fraction exponents creates object dtype arrays that scipy.sparse rejects.
- Cast Fraction exponents to float in `_column_grad` to prevent dtype=object arrays
- Ensure consistent vector semantics with `ravel(order='F')` 
- Fix sign handling for `p>1` with negative values to prevent incorrect gradients
- Regression test using exact reproduction from issue #2896
- Test for negative p values including harmonic mean case (p=-1)
- Test for gradient sign correctness with p>1 and negative values …
=> Fix issue #2896: harmonic mean gradient computation dtype error

cvxpy/lin_ops/canon_backend.py, cvxpy/reductions/complex2real/canonicalizers/__init__.py, cvxpy/tests/test_complex.py, cvxpy/tests/test_convolution.py
Altough cvxpy.conv is supported, cvxpy.convolve is a different atom and thus requires to be explicitly specified in order to be supported.
Fixes #2946
Note: I am not familiar with the codebase, there may be some reason that cvxpy.convolve is not supported and is not supposed to be supported by the complex2real step.
=> Support for cvxpy.convolve into complex2real, fix sparse convolutions in Scipy

.github/workflows/test_backends.yml, continuous_integration/test_script.sh, cvxpy/atoms/__init__.py, cvxpy/atoms/affine/stack.py, cvxpy/tests/atoms/affine/test_stack.py, doc/source/api_reference/cvxpy.atoms.affine.rst
Add a NumPy-style `cp.stack` atom that inserts a new axis via reshape/concatenate, export it, cover it with unit tests, and document it in the affine atom reference.
Issue: https://github.com/cvxpy/cvxpy/issues/2752
=> Add cp.stack atom
